// Code generated by ent, DO NOT EDIT.

package subscriptionoperation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldLTE(FieldID, id))
}

// SubscriptionID applies equality check predicate on the "subscription_id" field. It's identical to SubscriptionIDEQ.
func SubscriptionID(v int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldEQ(FieldSubscriptionID, v))
}

// EntitlementID applies equality check predicate on the "entitlement_id" field. It's identical to EntitlementIDEQ.
func EntitlementID(v int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldEQ(FieldEntitlementID, v))
}

// Operation applies equality check predicate on the "operation" field. It's identical to OperationEQ.
func Operation(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldEQ(FieldOperation, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldEQ(FieldSourceType, v))
}

// SourceReference applies equality check predicate on the "source_reference" field. It's identical to SourceReferenceEQ.
func SourceReference(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldEQ(FieldSourceReference, v))
}

// ActorID applies equality check predicate on the "actor_id" field. It's identical to ActorIDEQ.
func ActorID(v int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldEQ(FieldActorID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldEQ(FieldCreatedAt, v))
}

// SubscriptionIDEQ applies the EQ predicate on the "subscription_id" field.
func SubscriptionIDEQ(v int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldEQ(FieldSubscriptionID, v))
}

// SubscriptionIDNEQ applies the NEQ predicate on the "subscription_id" field.
func SubscriptionIDNEQ(v int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldNEQ(FieldSubscriptionID, v))
}

// SubscriptionIDIn applies the In predicate on the "subscription_id" field.
func SubscriptionIDIn(vs ...int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDNotIn applies the NotIn predicate on the "subscription_id" field.
func SubscriptionIDNotIn(vs ...int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldNotIn(FieldSubscriptionID, vs...))
}

// EntitlementIDEQ applies the EQ predicate on the "entitlement_id" field.
func EntitlementIDEQ(v int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldEQ(FieldEntitlementID, v))
}

// EntitlementIDNEQ applies the NEQ predicate on the "entitlement_id" field.
func EntitlementIDNEQ(v int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldNEQ(FieldEntitlementID, v))
}

// EntitlementIDIn applies the In predicate on the "entitlement_id" field.
func EntitlementIDIn(vs ...int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldIn(FieldEntitlementID, vs...))
}

// EntitlementIDNotIn applies the NotIn predicate on the "entitlement_id" field.
func EntitlementIDNotIn(vs ...int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldNotIn(FieldEntitlementID, vs...))
}

// EntitlementIDGT applies the GT predicate on the "entitlement_id" field.
func EntitlementIDGT(v int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldGT(FieldEntitlementID, v))
}

// EntitlementIDGTE applies the GTE predicate on the "entitlement_id" field.
func EntitlementIDGTE(v int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldGTE(FieldEntitlementID, v))
}

// EntitlementIDLT applies the LT predicate on the "entitlement_id" field.
func EntitlementIDLT(v int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldLT(FieldEntitlementID, v))
}

// EntitlementIDLTE applies the LTE predicate on the "entitlement_id" field.
func EntitlementIDLTE(v int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldLTE(FieldEntitlementID, v))
}

// OperationEQ applies the EQ predicate on the "operation" field.
func OperationEQ(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldEQ(FieldOperation, v))
}

// OperationNEQ applies the NEQ predicate on the "operation" field.
func OperationNEQ(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldNEQ(FieldOperation, v))
}

// OperationIn applies the In predicate on the "operation" field.
func OperationIn(vs ...string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldIn(FieldOperation, vs...))
}

// OperationNotIn applies the NotIn predicate on the "operation" field.
func OperationNotIn(vs ...string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldNotIn(FieldOperation, vs...))
}

// OperationGT applies the GT predicate on the "operation" field.
func OperationGT(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldGT(FieldOperation, v))
}

// OperationGTE applies the GTE predicate on the "operation" field.
func OperationGTE(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldGTE(FieldOperation, v))
}

// OperationLT applies the LT predicate on the "operation" field.
func OperationLT(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldLT(FieldOperation, v))
}

// OperationLTE applies the LTE predicate on the "operation" field.
func OperationLTE(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldLTE(FieldOperation, v))
}

// OperationContains applies the Contains predicate on the "operation" field.
func OperationContains(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldContains(FieldOperation, v))
}

// OperationHasPrefix applies the HasPrefix predicate on the "operation" field.
func OperationHasPrefix(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldHasPrefix(FieldOperation, v))
}

// OperationHasSuffix applies the HasSuffix predicate on the "operation" field.
func OperationHasSuffix(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldHasSuffix(FieldOperation, v))
}

// OperationEqualFold applies the EqualFold predicate on the "operation" field.
func OperationEqualFold(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldEqualFold(FieldOperation, v))
}

// OperationContainsFold applies the ContainsFold predicate on the "operation" field.
func OperationContainsFold(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldContainsFold(FieldOperation, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldContainsFold(FieldSourceType, v))
}

// SourceReferenceEQ applies the EQ predicate on the "source_reference" field.
func SourceReferenceEQ(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldEQ(FieldSourceReference, v))
}

// SourceReferenceNEQ applies the NEQ predicate on the "source_reference" field.
func SourceReferenceNEQ(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldNEQ(FieldSourceReference, v))
}

// SourceReferenceIn applies the In predicate on the "source_reference" field.
func SourceReferenceIn(vs ...string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldIn(FieldSourceReference, vs...))
}

// SourceReferenceNotIn applies the NotIn predicate on the "source_reference" field.
func SourceReferenceNotIn(vs ...string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldNotIn(FieldSourceReference, vs...))
}

// SourceReferenceGT applies the GT predicate on the "source_reference" field.
func SourceReferenceGT(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldGT(FieldSourceReference, v))
}

// SourceReferenceGTE applies the GTE predicate on the "source_reference" field.
func SourceReferenceGTE(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldGTE(FieldSourceReference, v))
}

// SourceReferenceLT applies the LT predicate on the "source_reference" field.
func SourceReferenceLT(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldLT(FieldSourceReference, v))
}

// SourceReferenceLTE applies the LTE predicate on the "source_reference" field.
func SourceReferenceLTE(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldLTE(FieldSourceReference, v))
}

// SourceReferenceContains applies the Contains predicate on the "source_reference" field.
func SourceReferenceContains(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldContains(FieldSourceReference, v))
}

// SourceReferenceHasPrefix applies the HasPrefix predicate on the "source_reference" field.
func SourceReferenceHasPrefix(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldHasPrefix(FieldSourceReference, v))
}

// SourceReferenceHasSuffix applies the HasSuffix predicate on the "source_reference" field.
func SourceReferenceHasSuffix(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldHasSuffix(FieldSourceReference, v))
}

// SourceReferenceEqualFold applies the EqualFold predicate on the "source_reference" field.
func SourceReferenceEqualFold(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldEqualFold(FieldSourceReference, v))
}

// SourceReferenceContainsFold applies the ContainsFold predicate on the "source_reference" field.
func SourceReferenceContainsFold(v string) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldContainsFold(FieldSourceReference, v))
}

// ActorIDEQ applies the EQ predicate on the "actor_id" field.
func ActorIDEQ(v int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldEQ(FieldActorID, v))
}

// ActorIDNEQ applies the NEQ predicate on the "actor_id" field.
func ActorIDNEQ(v int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldNEQ(FieldActorID, v))
}

// ActorIDIn applies the In predicate on the "actor_id" field.
func ActorIDIn(vs ...int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldIn(FieldActorID, vs...))
}

// ActorIDNotIn applies the NotIn predicate on the "actor_id" field.
func ActorIDNotIn(vs ...int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldNotIn(FieldActorID, vs...))
}

// ActorIDGT applies the GT predicate on the "actor_id" field.
func ActorIDGT(v int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldGT(FieldActorID, v))
}

// ActorIDGTE applies the GTE predicate on the "actor_id" field.
func ActorIDGTE(v int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldGTE(FieldActorID, v))
}

// ActorIDLT applies the LT predicate on the "actor_id" field.
func ActorIDLT(v int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldLT(FieldActorID, v))
}

// ActorIDLTE applies the LTE predicate on the "actor_id" field.
func ActorIDLTE(v int64) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldLTE(FieldActorID, v))
}

// DetailIsNil applies the IsNil predicate on the "detail" field.
func DetailIsNil() predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldIsNull(FieldDetail))
}

// DetailNotNil applies the NotNil predicate on the "detail" field.
func DetailNotNil() predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldNotNull(FieldDetail))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.FieldLTE(FieldCreatedAt, v))
}

// HasSubscription applies the HasEdge predicate on the "subscription" edge.
func HasSubscription() predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SubscriptionTable, SubscriptionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubscriptionWith applies the HasEdge predicate on the "subscription" edge with a given conditions (other predicates).
func HasSubscriptionWith(preds ...predicate.UserSubscription) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(func(s *sql.Selector) {
		step := newSubscriptionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionOperation) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionOperation) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionOperation) predicate.SubscriptionOperation {
	return predicate.SubscriptionOperation(sql.NotPredicates(p))
}
