// Code generated by ent, DO NOT EDIT.

package usersubscriptionentitlement

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLTE(FieldID, id))
}

// UserSubscriptionID applies equality check predicate on the "user_subscription_id" field. It's identical to UserSubscriptionIDEQ.
func UserSubscriptionID(v int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldUserSubscriptionID, v))
}

// PlanID applies equality check predicate on the "plan_id" field. It's identical to PlanIDEQ.
func PlanID(v int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldPlanID, v))
}

// SourceOrderID applies equality check predicate on the "source_order_id" field. It's identical to SourceOrderIDEQ.
func SourceOrderID(v int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldSourceOrderID, v))
}

// LotIndex applies equality check predicate on the "lot_index" field. It's identical to LotIndexEQ.
func LotIndex(v int) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldLotIndex, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldSourceType, v))
}

// SourceReference applies equality check predicate on the "source_reference" field. It's identical to SourceReferenceEQ.
func SourceReference(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldSourceReference, v))
}

// PurchaseMode applies equality check predicate on the "purchase_mode" field. It's identical to PurchaseModeEQ.
func PurchaseMode(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldPurchaseMode, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldStatus, v))
}

// StartsAt applies equality check predicate on the "starts_at" field. It's identical to StartsAtEQ.
func StartsAt(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldStartsAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldExpiresAt, v))
}

// DailyLimitUsd applies equality check predicate on the "daily_limit_usd" field. It's identical to DailyLimitUsdEQ.
func DailyLimitUsd(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldDailyLimitUsd, v))
}

// WeeklyLimitUsd applies equality check predicate on the "weekly_limit_usd" field. It's identical to WeeklyLimitUsdEQ.
func WeeklyLimitUsd(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldWeeklyLimitUsd, v))
}

// MonthlyLimitUsd applies equality check predicate on the "monthly_limit_usd" field. It's identical to MonthlyLimitUsdEQ.
func MonthlyLimitUsd(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldMonthlyLimitUsd, v))
}

// DailyWindowStart applies equality check predicate on the "daily_window_start" field. It's identical to DailyWindowStartEQ.
func DailyWindowStart(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldDailyWindowStart, v))
}

// WeeklyWindowStart applies equality check predicate on the "weekly_window_start" field. It's identical to WeeklyWindowStartEQ.
func WeeklyWindowStart(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldWeeklyWindowStart, v))
}

// MonthlyWindowStart applies equality check predicate on the "monthly_window_start" field. It's identical to MonthlyWindowStartEQ.
func MonthlyWindowStart(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldMonthlyWindowStart, v))
}

// DailyUsageUsd applies equality check predicate on the "daily_usage_usd" field. It's identical to DailyUsageUsdEQ.
func DailyUsageUsd(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldDailyUsageUsd, v))
}

// WeeklyUsageUsd applies equality check predicate on the "weekly_usage_usd" field. It's identical to WeeklyUsageUsdEQ.
func WeeklyUsageUsd(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldWeeklyUsageUsd, v))
}

// MonthlyUsageUsd applies equality check predicate on the "monthly_usage_usd" field. It's identical to MonthlyUsageUsdEQ.
func MonthlyUsageUsd(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldMonthlyUsageUsd, v))
}

// LifetimeUsageUsd applies equality check predicate on the "lifetime_usage_usd" field. It's identical to LifetimeUsageUsdEQ.
func LifetimeUsageUsd(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldLifetimeUsageUsd, v))
}

// RefundedAt applies equality check predicate on the "refunded_at" field. It's identical to RefundedAtEQ.
func RefundedAt(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldRefundedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserSubscriptionIDEQ applies the EQ predicate on the "user_subscription_id" field.
func UserSubscriptionIDEQ(v int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldUserSubscriptionID, v))
}

// UserSubscriptionIDNEQ applies the NEQ predicate on the "user_subscription_id" field.
func UserSubscriptionIDNEQ(v int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldUserSubscriptionID, v))
}

// UserSubscriptionIDIn applies the In predicate on the "user_subscription_id" field.
func UserSubscriptionIDIn(vs ...int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldUserSubscriptionID, vs...))
}

// UserSubscriptionIDNotIn applies the NotIn predicate on the "user_subscription_id" field.
func UserSubscriptionIDNotIn(vs ...int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldUserSubscriptionID, vs...))
}

// PlanIDEQ applies the EQ predicate on the "plan_id" field.
func PlanIDEQ(v int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldPlanID, v))
}

// PlanIDNEQ applies the NEQ predicate on the "plan_id" field.
func PlanIDNEQ(v int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldPlanID, v))
}

// PlanIDIn applies the In predicate on the "plan_id" field.
func PlanIDIn(vs ...int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldPlanID, vs...))
}

// PlanIDNotIn applies the NotIn predicate on the "plan_id" field.
func PlanIDNotIn(vs ...int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldPlanID, vs...))
}

// PlanIDIsNil applies the IsNil predicate on the "plan_id" field.
func PlanIDIsNil() predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIsNull(FieldPlanID))
}

// PlanIDNotNil applies the NotNil predicate on the "plan_id" field.
func PlanIDNotNil() predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotNull(FieldPlanID))
}

// SourceOrderIDEQ applies the EQ predicate on the "source_order_id" field.
func SourceOrderIDEQ(v int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldSourceOrderID, v))
}

// SourceOrderIDNEQ applies the NEQ predicate on the "source_order_id" field.
func SourceOrderIDNEQ(v int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldSourceOrderID, v))
}

// SourceOrderIDIn applies the In predicate on the "source_order_id" field.
func SourceOrderIDIn(vs ...int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldSourceOrderID, vs...))
}

// SourceOrderIDNotIn applies the NotIn predicate on the "source_order_id" field.
func SourceOrderIDNotIn(vs ...int64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldSourceOrderID, vs...))
}

// SourceOrderIDIsNil applies the IsNil predicate on the "source_order_id" field.
func SourceOrderIDIsNil() predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIsNull(FieldSourceOrderID))
}

// SourceOrderIDNotNil applies the NotNil predicate on the "source_order_id" field.
func SourceOrderIDNotNil() predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotNull(FieldSourceOrderID))
}

// LotIndexEQ applies the EQ predicate on the "lot_index" field.
func LotIndexEQ(v int) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldLotIndex, v))
}

// LotIndexNEQ applies the NEQ predicate on the "lot_index" field.
func LotIndexNEQ(v int) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldLotIndex, v))
}

// LotIndexIn applies the In predicate on the "lot_index" field.
func LotIndexIn(vs ...int) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldLotIndex, vs...))
}

// LotIndexNotIn applies the NotIn predicate on the "lot_index" field.
func LotIndexNotIn(vs ...int) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldLotIndex, vs...))
}

// LotIndexGT applies the GT predicate on the "lot_index" field.
func LotIndexGT(v int) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGT(FieldLotIndex, v))
}

// LotIndexGTE applies the GTE predicate on the "lot_index" field.
func LotIndexGTE(v int) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGTE(FieldLotIndex, v))
}

// LotIndexLT applies the LT predicate on the "lot_index" field.
func LotIndexLT(v int) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLT(FieldLotIndex, v))
}

// LotIndexLTE applies the LTE predicate on the "lot_index" field.
func LotIndexLTE(v int) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLTE(FieldLotIndex, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldContainsFold(FieldSourceType, v))
}

// SourceReferenceEQ applies the EQ predicate on the "source_reference" field.
func SourceReferenceEQ(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldSourceReference, v))
}

// SourceReferenceNEQ applies the NEQ predicate on the "source_reference" field.
func SourceReferenceNEQ(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldSourceReference, v))
}

// SourceReferenceIn applies the In predicate on the "source_reference" field.
func SourceReferenceIn(vs ...string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldSourceReference, vs...))
}

// SourceReferenceNotIn applies the NotIn predicate on the "source_reference" field.
func SourceReferenceNotIn(vs ...string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldSourceReference, vs...))
}

// SourceReferenceGT applies the GT predicate on the "source_reference" field.
func SourceReferenceGT(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGT(FieldSourceReference, v))
}

// SourceReferenceGTE applies the GTE predicate on the "source_reference" field.
func SourceReferenceGTE(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGTE(FieldSourceReference, v))
}

// SourceReferenceLT applies the LT predicate on the "source_reference" field.
func SourceReferenceLT(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLT(FieldSourceReference, v))
}

// SourceReferenceLTE applies the LTE predicate on the "source_reference" field.
func SourceReferenceLTE(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLTE(FieldSourceReference, v))
}

// SourceReferenceContains applies the Contains predicate on the "source_reference" field.
func SourceReferenceContains(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldContains(FieldSourceReference, v))
}

// SourceReferenceHasPrefix applies the HasPrefix predicate on the "source_reference" field.
func SourceReferenceHasPrefix(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldHasPrefix(FieldSourceReference, v))
}

// SourceReferenceHasSuffix applies the HasSuffix predicate on the "source_reference" field.
func SourceReferenceHasSuffix(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldHasSuffix(FieldSourceReference, v))
}

// SourceReferenceEqualFold applies the EqualFold predicate on the "source_reference" field.
func SourceReferenceEqualFold(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEqualFold(FieldSourceReference, v))
}

// SourceReferenceContainsFold applies the ContainsFold predicate on the "source_reference" field.
func SourceReferenceContainsFold(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldContainsFold(FieldSourceReference, v))
}

// PurchaseModeEQ applies the EQ predicate on the "purchase_mode" field.
func PurchaseModeEQ(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldPurchaseMode, v))
}

// PurchaseModeNEQ applies the NEQ predicate on the "purchase_mode" field.
func PurchaseModeNEQ(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldPurchaseMode, v))
}

// PurchaseModeIn applies the In predicate on the "purchase_mode" field.
func PurchaseModeIn(vs ...string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldPurchaseMode, vs...))
}

// PurchaseModeNotIn applies the NotIn predicate on the "purchase_mode" field.
func PurchaseModeNotIn(vs ...string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldPurchaseMode, vs...))
}

// PurchaseModeGT applies the GT predicate on the "purchase_mode" field.
func PurchaseModeGT(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGT(FieldPurchaseMode, v))
}

// PurchaseModeGTE applies the GTE predicate on the "purchase_mode" field.
func PurchaseModeGTE(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGTE(FieldPurchaseMode, v))
}

// PurchaseModeLT applies the LT predicate on the "purchase_mode" field.
func PurchaseModeLT(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLT(FieldPurchaseMode, v))
}

// PurchaseModeLTE applies the LTE predicate on the "purchase_mode" field.
func PurchaseModeLTE(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLTE(FieldPurchaseMode, v))
}

// PurchaseModeContains applies the Contains predicate on the "purchase_mode" field.
func PurchaseModeContains(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldContains(FieldPurchaseMode, v))
}

// PurchaseModeHasPrefix applies the HasPrefix predicate on the "purchase_mode" field.
func PurchaseModeHasPrefix(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldHasPrefix(FieldPurchaseMode, v))
}

// PurchaseModeHasSuffix applies the HasSuffix predicate on the "purchase_mode" field.
func PurchaseModeHasSuffix(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldHasSuffix(FieldPurchaseMode, v))
}

// PurchaseModeEqualFold applies the EqualFold predicate on the "purchase_mode" field.
func PurchaseModeEqualFold(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEqualFold(FieldPurchaseMode, v))
}

// PurchaseModeContainsFold applies the ContainsFold predicate on the "purchase_mode" field.
func PurchaseModeContainsFold(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldContainsFold(FieldPurchaseMode, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldContainsFold(FieldStatus, v))
}

// StartsAtEQ applies the EQ predicate on the "starts_at" field.
func StartsAtEQ(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldStartsAt, v))
}

// StartsAtNEQ applies the NEQ predicate on the "starts_at" field.
func StartsAtNEQ(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldStartsAt, v))
}

// StartsAtIn applies the In predicate on the "starts_at" field.
func StartsAtIn(vs ...time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldStartsAt, vs...))
}

// StartsAtNotIn applies the NotIn predicate on the "starts_at" field.
func StartsAtNotIn(vs ...time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldStartsAt, vs...))
}

// StartsAtGT applies the GT predicate on the "starts_at" field.
func StartsAtGT(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGT(FieldStartsAt, v))
}

// StartsAtGTE applies the GTE predicate on the "starts_at" field.
func StartsAtGTE(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGTE(FieldStartsAt, v))
}

// StartsAtLT applies the LT predicate on the "starts_at" field.
func StartsAtLT(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLT(FieldStartsAt, v))
}

// StartsAtLTE applies the LTE predicate on the "starts_at" field.
func StartsAtLTE(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLTE(FieldStartsAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLTE(FieldExpiresAt, v))
}

// DailyLimitUsdEQ applies the EQ predicate on the "daily_limit_usd" field.
func DailyLimitUsdEQ(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldDailyLimitUsd, v))
}

// DailyLimitUsdNEQ applies the NEQ predicate on the "daily_limit_usd" field.
func DailyLimitUsdNEQ(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldDailyLimitUsd, v))
}

// DailyLimitUsdIn applies the In predicate on the "daily_limit_usd" field.
func DailyLimitUsdIn(vs ...float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldDailyLimitUsd, vs...))
}

// DailyLimitUsdNotIn applies the NotIn predicate on the "daily_limit_usd" field.
func DailyLimitUsdNotIn(vs ...float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldDailyLimitUsd, vs...))
}

// DailyLimitUsdGT applies the GT predicate on the "daily_limit_usd" field.
func DailyLimitUsdGT(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGT(FieldDailyLimitUsd, v))
}

// DailyLimitUsdGTE applies the GTE predicate on the "daily_limit_usd" field.
func DailyLimitUsdGTE(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGTE(FieldDailyLimitUsd, v))
}

// DailyLimitUsdLT applies the LT predicate on the "daily_limit_usd" field.
func DailyLimitUsdLT(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLT(FieldDailyLimitUsd, v))
}

// DailyLimitUsdLTE applies the LTE predicate on the "daily_limit_usd" field.
func DailyLimitUsdLTE(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLTE(FieldDailyLimitUsd, v))
}

// DailyLimitUsdIsNil applies the IsNil predicate on the "daily_limit_usd" field.
func DailyLimitUsdIsNil() predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIsNull(FieldDailyLimitUsd))
}

// DailyLimitUsdNotNil applies the NotNil predicate on the "daily_limit_usd" field.
func DailyLimitUsdNotNil() predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotNull(FieldDailyLimitUsd))
}

// WeeklyLimitUsdEQ applies the EQ predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdEQ(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdNEQ applies the NEQ predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdNEQ(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdIn applies the In predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdIn(vs ...float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldWeeklyLimitUsd, vs...))
}

// WeeklyLimitUsdNotIn applies the NotIn predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdNotIn(vs ...float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldWeeklyLimitUsd, vs...))
}

// WeeklyLimitUsdGT applies the GT predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdGT(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGT(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdGTE applies the GTE predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdGTE(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGTE(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdLT applies the LT predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdLT(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLT(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdLTE applies the LTE predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdLTE(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLTE(FieldWeeklyLimitUsd, v))
}

// WeeklyLimitUsdIsNil applies the IsNil predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdIsNil() predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIsNull(FieldWeeklyLimitUsd))
}

// WeeklyLimitUsdNotNil applies the NotNil predicate on the "weekly_limit_usd" field.
func WeeklyLimitUsdNotNil() predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotNull(FieldWeeklyLimitUsd))
}

// MonthlyLimitUsdEQ applies the EQ predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdEQ(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdNEQ applies the NEQ predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdNEQ(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdIn applies the In predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdIn(vs ...float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldMonthlyLimitUsd, vs...))
}

// MonthlyLimitUsdNotIn applies the NotIn predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdNotIn(vs ...float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldMonthlyLimitUsd, vs...))
}

// MonthlyLimitUsdGT applies the GT predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdGT(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGT(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdGTE applies the GTE predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdGTE(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGTE(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdLT applies the LT predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdLT(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLT(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdLTE applies the LTE predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdLTE(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLTE(FieldMonthlyLimitUsd, v))
}

// MonthlyLimitUsdIsNil applies the IsNil predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdIsNil() predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIsNull(FieldMonthlyLimitUsd))
}

// MonthlyLimitUsdNotNil applies the NotNil predicate on the "monthly_limit_usd" field.
func MonthlyLimitUsdNotNil() predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotNull(FieldMonthlyLimitUsd))
}

// DailyWindowStartEQ applies the EQ predicate on the "daily_window_start" field.
func DailyWindowStartEQ(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldDailyWindowStart, v))
}

// DailyWindowStartNEQ applies the NEQ predicate on the "daily_window_start" field.
func DailyWindowStartNEQ(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldDailyWindowStart, v))
}

// DailyWindowStartIn applies the In predicate on the "daily_window_start" field.
func DailyWindowStartIn(vs ...time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldDailyWindowStart, vs...))
}

// DailyWindowStartNotIn applies the NotIn predicate on the "daily_window_start" field.
func DailyWindowStartNotIn(vs ...time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldDailyWindowStart, vs...))
}

// DailyWindowStartGT applies the GT predicate on the "daily_window_start" field.
func DailyWindowStartGT(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGT(FieldDailyWindowStart, v))
}

// DailyWindowStartGTE applies the GTE predicate on the "daily_window_start" field.
func DailyWindowStartGTE(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGTE(FieldDailyWindowStart, v))
}

// DailyWindowStartLT applies the LT predicate on the "daily_window_start" field.
func DailyWindowStartLT(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLT(FieldDailyWindowStart, v))
}

// DailyWindowStartLTE applies the LTE predicate on the "daily_window_start" field.
func DailyWindowStartLTE(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLTE(FieldDailyWindowStart, v))
}

// DailyWindowStartIsNil applies the IsNil predicate on the "daily_window_start" field.
func DailyWindowStartIsNil() predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIsNull(FieldDailyWindowStart))
}

// DailyWindowStartNotNil applies the NotNil predicate on the "daily_window_start" field.
func DailyWindowStartNotNil() predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotNull(FieldDailyWindowStart))
}

// WeeklyWindowStartEQ applies the EQ predicate on the "weekly_window_start" field.
func WeeklyWindowStartEQ(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartNEQ applies the NEQ predicate on the "weekly_window_start" field.
func WeeklyWindowStartNEQ(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartIn applies the In predicate on the "weekly_window_start" field.
func WeeklyWindowStartIn(vs ...time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldWeeklyWindowStart, vs...))
}

// WeeklyWindowStartNotIn applies the NotIn predicate on the "weekly_window_start" field.
func WeeklyWindowStartNotIn(vs ...time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldWeeklyWindowStart, vs...))
}

// WeeklyWindowStartGT applies the GT predicate on the "weekly_window_start" field.
func WeeklyWindowStartGT(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGT(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartGTE applies the GTE predicate on the "weekly_window_start" field.
func WeeklyWindowStartGTE(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGTE(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartLT applies the LT predicate on the "weekly_window_start" field.
func WeeklyWindowStartLT(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLT(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartLTE applies the LTE predicate on the "weekly_window_start" field.
func WeeklyWindowStartLTE(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLTE(FieldWeeklyWindowStart, v))
}

// WeeklyWindowStartIsNil applies the IsNil predicate on the "weekly_window_start" field.
func WeeklyWindowStartIsNil() predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIsNull(FieldWeeklyWindowStart))
}

// WeeklyWindowStartNotNil applies the NotNil predicate on the "weekly_window_start" field.
func WeeklyWindowStartNotNil() predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotNull(FieldWeeklyWindowStart))
}

// MonthlyWindowStartEQ applies the EQ predicate on the "monthly_window_start" field.
func MonthlyWindowStartEQ(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartNEQ applies the NEQ predicate on the "monthly_window_start" field.
func MonthlyWindowStartNEQ(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartIn applies the In predicate on the "monthly_window_start" field.
func MonthlyWindowStartIn(vs ...time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldMonthlyWindowStart, vs...))
}

// MonthlyWindowStartNotIn applies the NotIn predicate on the "monthly_window_start" field.
func MonthlyWindowStartNotIn(vs ...time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldMonthlyWindowStart, vs...))
}

// MonthlyWindowStartGT applies the GT predicate on the "monthly_window_start" field.
func MonthlyWindowStartGT(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGT(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartGTE applies the GTE predicate on the "monthly_window_start" field.
func MonthlyWindowStartGTE(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGTE(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartLT applies the LT predicate on the "monthly_window_start" field.
func MonthlyWindowStartLT(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLT(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartLTE applies the LTE predicate on the "monthly_window_start" field.
func MonthlyWindowStartLTE(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLTE(FieldMonthlyWindowStart, v))
}

// MonthlyWindowStartIsNil applies the IsNil predicate on the "monthly_window_start" field.
func MonthlyWindowStartIsNil() predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIsNull(FieldMonthlyWindowStart))
}

// MonthlyWindowStartNotNil applies the NotNil predicate on the "monthly_window_start" field.
func MonthlyWindowStartNotNil() predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotNull(FieldMonthlyWindowStart))
}

// DailyUsageUsdEQ applies the EQ predicate on the "daily_usage_usd" field.
func DailyUsageUsdEQ(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldDailyUsageUsd, v))
}

// DailyUsageUsdNEQ applies the NEQ predicate on the "daily_usage_usd" field.
func DailyUsageUsdNEQ(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldDailyUsageUsd, v))
}

// DailyUsageUsdIn applies the In predicate on the "daily_usage_usd" field.
func DailyUsageUsdIn(vs ...float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldDailyUsageUsd, vs...))
}

// DailyUsageUsdNotIn applies the NotIn predicate on the "daily_usage_usd" field.
func DailyUsageUsdNotIn(vs ...float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldDailyUsageUsd, vs...))
}

// DailyUsageUsdGT applies the GT predicate on the "daily_usage_usd" field.
func DailyUsageUsdGT(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGT(FieldDailyUsageUsd, v))
}

// DailyUsageUsdGTE applies the GTE predicate on the "daily_usage_usd" field.
func DailyUsageUsdGTE(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGTE(FieldDailyUsageUsd, v))
}

// DailyUsageUsdLT applies the LT predicate on the "daily_usage_usd" field.
func DailyUsageUsdLT(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLT(FieldDailyUsageUsd, v))
}

// DailyUsageUsdLTE applies the LTE predicate on the "daily_usage_usd" field.
func DailyUsageUsdLTE(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLTE(FieldDailyUsageUsd, v))
}

// WeeklyUsageUsdEQ applies the EQ predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdEQ(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdNEQ applies the NEQ predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdNEQ(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdIn applies the In predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdIn(vs ...float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldWeeklyUsageUsd, vs...))
}

// WeeklyUsageUsdNotIn applies the NotIn predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdNotIn(vs ...float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldWeeklyUsageUsd, vs...))
}

// WeeklyUsageUsdGT applies the GT predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdGT(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGT(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdGTE applies the GTE predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdGTE(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGTE(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdLT applies the LT predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdLT(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLT(FieldWeeklyUsageUsd, v))
}

// WeeklyUsageUsdLTE applies the LTE predicate on the "weekly_usage_usd" field.
func WeeklyUsageUsdLTE(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLTE(FieldWeeklyUsageUsd, v))
}

// MonthlyUsageUsdEQ applies the EQ predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdEQ(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdNEQ applies the NEQ predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdNEQ(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdIn applies the In predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdIn(vs ...float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldMonthlyUsageUsd, vs...))
}

// MonthlyUsageUsdNotIn applies the NotIn predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdNotIn(vs ...float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldMonthlyUsageUsd, vs...))
}

// MonthlyUsageUsdGT applies the GT predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdGT(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGT(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdGTE applies the GTE predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdGTE(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGTE(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdLT applies the LT predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdLT(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLT(FieldMonthlyUsageUsd, v))
}

// MonthlyUsageUsdLTE applies the LTE predicate on the "monthly_usage_usd" field.
func MonthlyUsageUsdLTE(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLTE(FieldMonthlyUsageUsd, v))
}

// LifetimeUsageUsdEQ applies the EQ predicate on the "lifetime_usage_usd" field.
func LifetimeUsageUsdEQ(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldLifetimeUsageUsd, v))
}

// LifetimeUsageUsdNEQ applies the NEQ predicate on the "lifetime_usage_usd" field.
func LifetimeUsageUsdNEQ(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldLifetimeUsageUsd, v))
}

// LifetimeUsageUsdIn applies the In predicate on the "lifetime_usage_usd" field.
func LifetimeUsageUsdIn(vs ...float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldLifetimeUsageUsd, vs...))
}

// LifetimeUsageUsdNotIn applies the NotIn predicate on the "lifetime_usage_usd" field.
func LifetimeUsageUsdNotIn(vs ...float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldLifetimeUsageUsd, vs...))
}

// LifetimeUsageUsdGT applies the GT predicate on the "lifetime_usage_usd" field.
func LifetimeUsageUsdGT(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGT(FieldLifetimeUsageUsd, v))
}

// LifetimeUsageUsdGTE applies the GTE predicate on the "lifetime_usage_usd" field.
func LifetimeUsageUsdGTE(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGTE(FieldLifetimeUsageUsd, v))
}

// LifetimeUsageUsdLT applies the LT predicate on the "lifetime_usage_usd" field.
func LifetimeUsageUsdLT(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLT(FieldLifetimeUsageUsd, v))
}

// LifetimeUsageUsdLTE applies the LTE predicate on the "lifetime_usage_usd" field.
func LifetimeUsageUsdLTE(v float64) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLTE(FieldLifetimeUsageUsd, v))
}

// RefundedAtEQ applies the EQ predicate on the "refunded_at" field.
func RefundedAtEQ(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldRefundedAt, v))
}

// RefundedAtNEQ applies the NEQ predicate on the "refunded_at" field.
func RefundedAtNEQ(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldRefundedAt, v))
}

// RefundedAtIn applies the In predicate on the "refunded_at" field.
func RefundedAtIn(vs ...time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldRefundedAt, vs...))
}

// RefundedAtNotIn applies the NotIn predicate on the "refunded_at" field.
func RefundedAtNotIn(vs ...time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldRefundedAt, vs...))
}

// RefundedAtGT applies the GT predicate on the "refunded_at" field.
func RefundedAtGT(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGT(FieldRefundedAt, v))
}

// RefundedAtGTE applies the GTE predicate on the "refunded_at" field.
func RefundedAtGTE(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGTE(FieldRefundedAt, v))
}

// RefundedAtLT applies the LT predicate on the "refunded_at" field.
func RefundedAtLT(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLT(FieldRefundedAt, v))
}

// RefundedAtLTE applies the LTE predicate on the "refunded_at" field.
func RefundedAtLTE(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLTE(FieldRefundedAt, v))
}

// RefundedAtIsNil applies the IsNil predicate on the "refunded_at" field.
func RefundedAtIsNil() predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIsNull(FieldRefundedAt))
}

// RefundedAtNotNil applies the NotNil predicate on the "refunded_at" field.
func RefundedAtNotNil() predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotNull(FieldRefundedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasSubscription applies the HasEdge predicate on the "subscription" edge.
func HasSubscription() predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SubscriptionTable, SubscriptionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubscriptionWith applies the HasEdge predicate on the "subscription" edge with a given conditions (other predicates).
func HasSubscriptionWith(preds ...predicate.UserSubscription) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(func(s *sql.Selector) {
		step := newSubscriptionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPlan applies the HasEdge predicate on the "plan" edge.
func HasPlan() predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PlanTable, PlanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlanWith applies the HasEdge predicate on the "plan" edge with a given conditions (other predicates).
func HasPlanWith(preds ...predicate.SubscriptionPlan) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(func(s *sql.Selector) {
		step := newPlanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSourceOrder applies the HasEdge predicate on the "source_order" edge.
func HasSourceOrder() predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SourceOrderTable, SourceOrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceOrderWith applies the HasEdge predicate on the "source_order" edge with a given conditions (other predicates).
func HasSourceOrderWith(preds ...predicate.PaymentOrder) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(func(s *sql.Selector) {
		step := newSourceOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOrderLines applies the HasEdge predicate on the "order_lines" edge.
func HasOrderLines() predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OrderLinesTable, OrderLinesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrderLinesWith applies the HasEdge predicate on the "order_lines" edge with a given conditions (other predicates).
func HasOrderLinesWith(preds ...predicate.SubscriptionEntitlementOrder) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(func(s *sql.Selector) {
		step := newOrderLinesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserSubscriptionEntitlement) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserSubscriptionEntitlement) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserSubscriptionEntitlement) predicate.UserSubscriptionEntitlement {
	return predicate.UserSubscriptionEntitlement(sql.NotPredicates(p))
}
