// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionrefund"
)

// SubscriptionRefundDelete is the builder for deleting a SubscriptionRefund entity.
type SubscriptionRefundDelete struct {
	config
	hooks    []Hook
	mutation *SubscriptionRefundMutation
}

// Where appends a list predicates to the SubscriptionRefundDelete builder.
func (_d *SubscriptionRefundDelete) Where(ps ...predicate.SubscriptionRefund) *SubscriptionRefundDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SubscriptionRefundDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SubscriptionRefundDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SubscriptionRefundDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(subscriptionrefund.Table, sqlgraph.NewFieldSpec(subscriptionrefund.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SubscriptionRefundDeleteOne is the builder for deleting a single SubscriptionRefund entity.
type SubscriptionRefundDeleteOne struct {
	_d *SubscriptionRefundDelete
}

// Where appends a list predicates to the SubscriptionRefundDelete builder.
func (_d *SubscriptionRefundDeleteOne) Where(ps ...predicate.SubscriptionRefund) *SubscriptionRefundDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SubscriptionRefundDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{subscriptionrefund.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SubscriptionRefundDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
