// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionrequest"
)

// SubscriptionRequestUpdate is the builder for updating SubscriptionRequest entities.
type SubscriptionRequestUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionRequestMutation
}

// Where appends a list predicates to the SubscriptionRequestUpdate builder.
func (_u *SubscriptionRequestUpdate) Where(ps ...predicate.SubscriptionRequest) *SubscriptionRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestKey sets the "request_key" field.
func (_u *SubscriptionRequestUpdate) SetRequestKey(v string) *SubscriptionRequestUpdate {
	_u.mutation.SetRequestKey(v)
	return _u
}

// SetNillableRequestKey sets the "request_key" field if the given value is not nil.
func (_u *SubscriptionRequestUpdate) SetNillableRequestKey(v *string) *SubscriptionRequestUpdate {
	if v != nil {
		_u.SetRequestKey(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionRequestUpdate) SetSubscriptionID(v int64) *SubscriptionRequestUpdate {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionRequestUpdate) SetNillableSubscriptionID(v *int64) *SubscriptionRequestUpdate {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *SubscriptionRequestUpdate) AddSubscriptionID(v int64) *SubscriptionRequestUpdate {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *SubscriptionRequestUpdate) SetAPIKeyID(v int64) *SubscriptionRequestUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *SubscriptionRequestUpdate) SetNillableAPIKeyID(v *int64) *SubscriptionRequestUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *SubscriptionRequestUpdate) AddAPIKeyID(v int64) *SubscriptionRequestUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionRequestUpdate) SetStatus(v string) *SubscriptionRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionRequestUpdate) SetNillableStatus(v *string) *SubscriptionRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLots sets the "lots" field.
func (_u *SubscriptionRequestUpdate) SetLots(v jsontext.Value) *SubscriptionRequestUpdate {
	_u.mutation.SetLots(v)
	return _u
}

// AppendLots appends value to the "lots" field.
func (_u *SubscriptionRequestUpdate) AppendLots(v jsontext.Value) *SubscriptionRequestUpdate {
	_u.mutation.AppendLots(v)
	return _u
}

// SetAdmittedAt sets the "admitted_at" field.
func (_u *SubscriptionRequestUpdate) SetAdmittedAt(v time.Time) *SubscriptionRequestUpdate {
	_u.mutation.SetAdmittedAt(v)
	return _u
}

// SetNillableAdmittedAt sets the "admitted_at" field if the given value is not nil.
func (_u *SubscriptionRequestUpdate) SetNillableAdmittedAt(v *time.Time) *SubscriptionRequestUpdate {
	if v != nil {
		_u.SetAdmittedAt(*v)
	}
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *SubscriptionRequestUpdate) SetSettledAt(v time.Time) *SubscriptionRequestUpdate {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *SubscriptionRequestUpdate) SetNillableSettledAt(v *time.Time) *SubscriptionRequestUpdate {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (_u *SubscriptionRequestUpdate) ClearSettledAt() *SubscriptionRequestUpdate {
	_u.mutation.ClearSettledAt()
	return _u
}

// SetBillingRequestID sets the "billing_request_id" field.
func (_u *SubscriptionRequestUpdate) SetBillingRequestID(v string) *SubscriptionRequestUpdate {
	_u.mutation.SetBillingRequestID(v)
	return _u
}

// SetNillableBillingRequestID sets the "billing_request_id" field if the given value is not nil.
func (_u *SubscriptionRequestUpdate) SetNillableBillingRequestID(v *string) *SubscriptionRequestUpdate {
	if v != nil {
		_u.SetBillingRequestID(*v)
	}
	return _u
}

// SetCostUsd sets the "cost_usd" field.
func (_u *SubscriptionRequestUpdate) SetCostUsd(v float64) *SubscriptionRequestUpdate {
	_u.mutation.ResetCostUsd()
	_u.mutation.SetCostUsd(v)
	return _u
}

// SetNillableCostUsd sets the "cost_usd" field if the given value is not nil.
func (_u *SubscriptionRequestUpdate) SetNillableCostUsd(v *float64) *SubscriptionRequestUpdate {
	if v != nil {
		_u.SetCostUsd(*v)
	}
	return _u
}

// AddCostUsd adds value to the "cost_usd" field.
func (_u *SubscriptionRequestUpdate) AddCostUsd(v float64) *SubscriptionRequestUpdate {
	_u.mutation.AddCostUsd(v)
	return _u
}

// Mutation returns the SubscriptionRequestMutation object of the builder.
func (_u *SubscriptionRequestUpdate) Mutation() *SubscriptionRequestMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionRequestUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SubscriptionRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(subscriptionrequest.Table, subscriptionrequest.Columns, sqlgraph.NewFieldSpec(subscriptionrequest.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestKey(); ok {
		_spec.SetField(subscriptionrequest.FieldRequestKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(subscriptionrequest.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(subscriptionrequest.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(subscriptionrequest.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(subscriptionrequest.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionrequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Lots(); ok {
		_spec.SetField(subscriptionrequest.FieldLots, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLots(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, subscriptionrequest.FieldLots, value)
		})
	}
	if value, ok := _u.mutation.AdmittedAt(); ok {
		_spec.SetField(subscriptionrequest.FieldAdmittedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(subscriptionrequest.FieldSettledAt, field.TypeTime, value)
	}
	if _u.mutation.SettledAtCleared() {
		_spec.ClearField(subscriptionrequest.FieldSettledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.BillingRequestID(); ok {
		_spec.SetField(subscriptionrequest.FieldBillingRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CostUsd(); ok {
		_spec.SetField(subscriptionrequest.FieldCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostUsd(); ok {
		_spec.AddField(subscriptionrequest.FieldCostUsd, field.TypeFloat64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionRequestUpdateOne is the builder for updating a single SubscriptionRequest entity.
type SubscriptionRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionRequestMutation
}

// SetRequestKey sets the "request_key" field.
func (_u *SubscriptionRequestUpdateOne) SetRequestKey(v string) *SubscriptionRequestUpdateOne {
	_u.mutation.SetRequestKey(v)
	return _u
}

// SetNillableRequestKey sets the "request_key" field if the given value is not nil.
func (_u *SubscriptionRequestUpdateOne) SetNillableRequestKey(v *string) *SubscriptionRequestUpdateOne {
	if v != nil {
		_u.SetRequestKey(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionRequestUpdateOne) SetSubscriptionID(v int64) *SubscriptionRequestUpdateOne {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionRequestUpdateOne) SetNillableSubscriptionID(v *int64) *SubscriptionRequestUpdateOne {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *SubscriptionRequestUpdateOne) AddSubscriptionID(v int64) *SubscriptionRequestUpdateOne {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *SubscriptionRequestUpdateOne) SetAPIKeyID(v int64) *SubscriptionRequestUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *SubscriptionRequestUpdateOne) SetNillableAPIKeyID(v *int64) *SubscriptionRequestUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *SubscriptionRequestUpdateOne) AddAPIKeyID(v int64) *SubscriptionRequestUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionRequestUpdateOne) SetStatus(v string) *SubscriptionRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionRequestUpdateOne) SetNillableStatus(v *string) *SubscriptionRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLots sets the "lots" field.
func (_u *SubscriptionRequestUpdateOne) SetLots(v jsontext.Value) *SubscriptionRequestUpdateOne {
	_u.mutation.SetLots(v)
	return _u
}

// AppendLots appends value to the "lots" field.
func (_u *SubscriptionRequestUpdateOne) AppendLots(v jsontext.Value) *SubscriptionRequestUpdateOne {
	_u.mutation.AppendLots(v)
	return _u
}

// SetAdmittedAt sets the "admitted_at" field.
func (_u *SubscriptionRequestUpdateOne) SetAdmittedAt(v time.Time) *SubscriptionRequestUpdateOne {
	_u.mutation.SetAdmittedAt(v)
	return _u
}

// SetNillableAdmittedAt sets the "admitted_at" field if the given value is not nil.
func (_u *SubscriptionRequestUpdateOne) SetNillableAdmittedAt(v *time.Time) *SubscriptionRequestUpdateOne {
	if v != nil {
		_u.SetAdmittedAt(*v)
	}
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *SubscriptionRequestUpdateOne) SetSettledAt(v time.Time) *SubscriptionRequestUpdateOne {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *SubscriptionRequestUpdateOne) SetNillableSettledAt(v *time.Time) *SubscriptionRequestUpdateOne {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (_u *SubscriptionRequestUpdateOne) ClearSettledAt() *SubscriptionRequestUpdateOne {
	_u.mutation.ClearSettledAt()
	return _u
}

// SetBillingRequestID sets the "billing_request_id" field.
func (_u *SubscriptionRequestUpdateOne) SetBillingRequestID(v string) *SubscriptionRequestUpdateOne {
	_u.mutation.SetBillingRequestID(v)
	return _u
}

// SetNillableBillingRequestID sets the "billing_request_id" field if the given value is not nil.
func (_u *SubscriptionRequestUpdateOne) SetNillableBillingRequestID(v *string) *SubscriptionRequestUpdateOne {
	if v != nil {
		_u.SetBillingRequestID(*v)
	}
	return _u
}

// SetCostUsd sets the "cost_usd" field.
func (_u *SubscriptionRequestUpdateOne) SetCostUsd(v float64) *SubscriptionRequestUpdateOne {
	_u.mutation.ResetCostUsd()
	_u.mutation.SetCostUsd(v)
	return _u
}

// SetNillableCostUsd sets the "cost_usd" field if the given value is not nil.
func (_u *SubscriptionRequestUpdateOne) SetNillableCostUsd(v *float64) *SubscriptionRequestUpdateOne {
	if v != nil {
		_u.SetCostUsd(*v)
	}
	return _u
}

// AddCostUsd adds value to the "cost_usd" field.
func (_u *SubscriptionRequestUpdateOne) AddCostUsd(v float64) *SubscriptionRequestUpdateOne {
	_u.mutation.AddCostUsd(v)
	return _u
}

// Mutation returns the SubscriptionRequestMutation object of the builder.
func (_u *SubscriptionRequestUpdateOne) Mutation() *SubscriptionRequestMutation {
	return _u.mutation
}

// Where appends a list predicates to the SubscriptionRequestUpdate builder.
func (_u *SubscriptionRequestUpdateOne) Where(ps ...predicate.SubscriptionRequest) *SubscriptionRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionRequestUpdateOne) Select(field string, fields ...string) *SubscriptionRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionRequest entity.
func (_u *SubscriptionRequestUpdateOne) Save(ctx context.Context) (*SubscriptionRequest, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionRequestUpdateOne) SaveX(ctx context.Context) *SubscriptionRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SubscriptionRequestUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionRequest, err error) {
	_spec := sqlgraph.NewUpdateSpec(subscriptionrequest.Table, subscriptionrequest.Columns, sqlgraph.NewFieldSpec(subscriptionrequest.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionrequest.FieldID)
		for _, f := range fields {
			if !subscriptionrequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestKey(); ok {
		_spec.SetField(subscriptionrequest.FieldRequestKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(subscriptionrequest.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(subscriptionrequest.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(subscriptionrequest.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(subscriptionrequest.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionrequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Lots(); ok {
		_spec.SetField(subscriptionrequest.FieldLots, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLots(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, subscriptionrequest.FieldLots, value)
		})
	}
	if value, ok := _u.mutation.AdmittedAt(); ok {
		_spec.SetField(subscriptionrequest.FieldAdmittedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(subscriptionrequest.FieldSettledAt, field.TypeTime, value)
	}
	if _u.mutation.SettledAtCleared() {
		_spec.ClearField(subscriptionrequest.FieldSettledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.BillingRequestID(); ok {
		_spec.SetField(subscriptionrequest.FieldBillingRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.CostUsd(); ok {
		_spec.SetField(subscriptionrequest.FieldCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostUsd(); ok {
		_spec.AddField(subscriptionrequest.FieldCostUsd, field.TypeFloat64, value)
	}
	_node = &SubscriptionRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
