// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionoperation"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// SubscriptionOperationUpdate is the builder for updating SubscriptionOperation entities.
type SubscriptionOperationUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionOperationMutation
}

// Where appends a list predicates to the SubscriptionOperationUpdate builder.
func (_u *SubscriptionOperationUpdate) Where(ps ...predicate.SubscriptionOperation) *SubscriptionOperationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionOperationUpdate) SetSubscriptionID(v int64) *SubscriptionOperationUpdate {
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionOperationUpdate) SetNillableSubscriptionID(v *int64) *SubscriptionOperationUpdate {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// SetEntitlementID sets the "entitlement_id" field.
func (_u *SubscriptionOperationUpdate) SetEntitlementID(v int64) *SubscriptionOperationUpdate {
	_u.mutation.ResetEntitlementID()
	_u.mutation.SetEntitlementID(v)
	return _u
}

// SetNillableEntitlementID sets the "entitlement_id" field if the given value is not nil.
func (_u *SubscriptionOperationUpdate) SetNillableEntitlementID(v *int64) *SubscriptionOperationUpdate {
	if v != nil {
		_u.SetEntitlementID(*v)
	}
	return _u
}

// AddEntitlementID adds value to the "entitlement_id" field.
func (_u *SubscriptionOperationUpdate) AddEntitlementID(v int64) *SubscriptionOperationUpdate {
	_u.mutation.AddEntitlementID(v)
	return _u
}

// SetOperation sets the "operation" field.
func (_u *SubscriptionOperationUpdate) SetOperation(v string) *SubscriptionOperationUpdate {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *SubscriptionOperationUpdate) SetNillableOperation(v *string) *SubscriptionOperationUpdate {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *SubscriptionOperationUpdate) SetSourceType(v string) *SubscriptionOperationUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *SubscriptionOperationUpdate) SetNillableSourceType(v *string) *SubscriptionOperationUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceReference sets the "source_reference" field.
func (_u *SubscriptionOperationUpdate) SetSourceReference(v string) *SubscriptionOperationUpdate {
	_u.mutation.SetSourceReference(v)
	return _u
}

// SetNillableSourceReference sets the "source_reference" field if the given value is not nil.
func (_u *SubscriptionOperationUpdate) SetNillableSourceReference(v *string) *SubscriptionOperationUpdate {
	if v != nil {
		_u.SetSourceReference(*v)
	}
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *SubscriptionOperationUpdate) SetActorID(v int64) *SubscriptionOperationUpdate {
	_u.mutation.ResetActorID()
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *SubscriptionOperationUpdate) SetNillableActorID(v *int64) *SubscriptionOperationUpdate {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// AddActorID adds value to the "actor_id" field.
func (_u *SubscriptionOperationUpdate) AddActorID(v int64) *SubscriptionOperationUpdate {
	_u.mutation.AddActorID(v)
	return _u
}

// SetDetail sets the "detail" field.
func (_u *SubscriptionOperationUpdate) SetDetail(v map[string]interface{}) *SubscriptionOperationUpdate {
	_u.mutation.SetDetail(v)
	return _u
}

// ClearDetail clears the value of the "detail" field.
func (_u *SubscriptionOperationUpdate) ClearDetail() *SubscriptionOperationUpdate {
	_u.mutation.ClearDetail()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SubscriptionOperationUpdate) SetCreatedAt(v time.Time) *SubscriptionOperationUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SubscriptionOperationUpdate) SetNillableCreatedAt(v *time.Time) *SubscriptionOperationUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionOperationUpdate) SetSubscription(v *UserSubscription) *SubscriptionOperationUpdate {
	return _u.SetSubscriptionID(v.ID)
}

// Mutation returns the SubscriptionOperationMutation object of the builder.
func (_u *SubscriptionOperationUpdate) Mutation() *SubscriptionOperationMutation {
	return _u.mutation
}

// ClearSubscription clears the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionOperationUpdate) ClearSubscription() *SubscriptionOperationUpdate {
	_u.mutation.ClearSubscription()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionOperationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionOperationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionOperationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionOperationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionOperationUpdate) check() error {
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionOperation.subscription"`)
	}
	return nil
}

func (_u *SubscriptionOperationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionoperation.Table, subscriptionoperation.Columns, sqlgraph.NewFieldSpec(subscriptionoperation.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EntitlementID(); ok {
		_spec.SetField(subscriptionoperation.FieldEntitlementID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEntitlementID(); ok {
		_spec.AddField(subscriptionoperation.FieldEntitlementID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(subscriptionoperation.FieldOperation, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(subscriptionoperation.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceReference(); ok {
		_spec.SetField(subscriptionoperation.FieldSourceReference, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(subscriptionoperation.FieldActorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActorID(); ok {
		_spec.AddField(subscriptionoperation.FieldActorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(subscriptionoperation.FieldDetail, field.TypeJSON, value)
	}
	if _u.mutation.DetailCleared() {
		_spec.ClearField(subscriptionoperation.FieldDetail, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionoperation.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionoperation.SubscriptionTable,
			Columns: []string{subscriptionoperation.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionoperation.SubscriptionTable,
			Columns: []string{subscriptionoperation.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionoperation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionOperationUpdateOne is the builder for updating a single SubscriptionOperation entity.
type SubscriptionOperationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionOperationMutation
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionOperationUpdateOne) SetSubscriptionID(v int64) *SubscriptionOperationUpdateOne {
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionOperationUpdateOne) SetNillableSubscriptionID(v *int64) *SubscriptionOperationUpdateOne {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// SetEntitlementID sets the "entitlement_id" field.
func (_u *SubscriptionOperationUpdateOne) SetEntitlementID(v int64) *SubscriptionOperationUpdateOne {
	_u.mutation.ResetEntitlementID()
	_u.mutation.SetEntitlementID(v)
	return _u
}

// SetNillableEntitlementID sets the "entitlement_id" field if the given value is not nil.
func (_u *SubscriptionOperationUpdateOne) SetNillableEntitlementID(v *int64) *SubscriptionOperationUpdateOne {
	if v != nil {
		_u.SetEntitlementID(*v)
	}
	return _u
}

// AddEntitlementID adds value to the "entitlement_id" field.
func (_u *SubscriptionOperationUpdateOne) AddEntitlementID(v int64) *SubscriptionOperationUpdateOne {
	_u.mutation.AddEntitlementID(v)
	return _u
}

// SetOperation sets the "operation" field.
func (_u *SubscriptionOperationUpdateOne) SetOperation(v string) *SubscriptionOperationUpdateOne {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *SubscriptionOperationUpdateOne) SetNillableOperation(v *string) *SubscriptionOperationUpdateOne {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *SubscriptionOperationUpdateOne) SetSourceType(v string) *SubscriptionOperationUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *SubscriptionOperationUpdateOne) SetNillableSourceType(v *string) *SubscriptionOperationUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceReference sets the "source_reference" field.
func (_u *SubscriptionOperationUpdateOne) SetSourceReference(v string) *SubscriptionOperationUpdateOne {
	_u.mutation.SetSourceReference(v)
	return _u
}

// SetNillableSourceReference sets the "source_reference" field if the given value is not nil.
func (_u *SubscriptionOperationUpdateOne) SetNillableSourceReference(v *string) *SubscriptionOperationUpdateOne {
	if v != nil {
		_u.SetSourceReference(*v)
	}
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *SubscriptionOperationUpdateOne) SetActorID(v int64) *SubscriptionOperationUpdateOne {
	_u.mutation.ResetActorID()
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *SubscriptionOperationUpdateOne) SetNillableActorID(v *int64) *SubscriptionOperationUpdateOne {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// AddActorID adds value to the "actor_id" field.
func (_u *SubscriptionOperationUpdateOne) AddActorID(v int64) *SubscriptionOperationUpdateOne {
	_u.mutation.AddActorID(v)
	return _u
}

// SetDetail sets the "detail" field.
func (_u *SubscriptionOperationUpdateOne) SetDetail(v map[string]interface{}) *SubscriptionOperationUpdateOne {
	_u.mutation.SetDetail(v)
	return _u
}

// ClearDetail clears the value of the "detail" field.
func (_u *SubscriptionOperationUpdateOne) ClearDetail() *SubscriptionOperationUpdateOne {
	_u.mutation.ClearDetail()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SubscriptionOperationUpdateOne) SetCreatedAt(v time.Time) *SubscriptionOperationUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SubscriptionOperationUpdateOne) SetNillableCreatedAt(v *time.Time) *SubscriptionOperationUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionOperationUpdateOne) SetSubscription(v *UserSubscription) *SubscriptionOperationUpdateOne {
	return _u.SetSubscriptionID(v.ID)
}

// Mutation returns the SubscriptionOperationMutation object of the builder.
func (_u *SubscriptionOperationUpdateOne) Mutation() *SubscriptionOperationMutation {
	return _u.mutation
}

// ClearSubscription clears the "subscription" edge to the UserSubscription entity.
func (_u *SubscriptionOperationUpdateOne) ClearSubscription() *SubscriptionOperationUpdateOne {
	_u.mutation.ClearSubscription()
	return _u
}

// Where appends a list predicates to the SubscriptionOperationUpdate builder.
func (_u *SubscriptionOperationUpdateOne) Where(ps ...predicate.SubscriptionOperation) *SubscriptionOperationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionOperationUpdateOne) Select(field string, fields ...string) *SubscriptionOperationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionOperation entity.
func (_u *SubscriptionOperationUpdateOne) Save(ctx context.Context) (*SubscriptionOperation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionOperationUpdateOne) SaveX(ctx context.Context) *SubscriptionOperation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionOperationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionOperationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionOperationUpdateOne) check() error {
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionOperation.subscription"`)
	}
	return nil
}

func (_u *SubscriptionOperationUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionOperation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionoperation.Table, subscriptionoperation.Columns, sqlgraph.NewFieldSpec(subscriptionoperation.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionOperation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionoperation.FieldID)
		for _, f := range fields {
			if !subscriptionoperation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionoperation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EntitlementID(); ok {
		_spec.SetField(subscriptionoperation.FieldEntitlementID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEntitlementID(); ok {
		_spec.AddField(subscriptionoperation.FieldEntitlementID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(subscriptionoperation.FieldOperation, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(subscriptionoperation.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceReference(); ok {
		_spec.SetField(subscriptionoperation.FieldSourceReference, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(subscriptionoperation.FieldActorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActorID(); ok {
		_spec.AddField(subscriptionoperation.FieldActorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(subscriptionoperation.FieldDetail, field.TypeJSON, value)
	}
	if _u.mutation.DetailCleared() {
		_spec.ClearField(subscriptionoperation.FieldDetail, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionoperation.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionoperation.SubscriptionTable,
			Columns: []string{subscriptionoperation.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionoperation.SubscriptionTable,
			Columns: []string{subscriptionoperation.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubscriptionOperation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionoperation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
