// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionrefund"
)

// SubscriptionRefundUpdate is the builder for updating SubscriptionRefund entities.
type SubscriptionRefundUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionRefundMutation
}

// Where appends a list predicates to the SubscriptionRefundUpdate builder.
func (_u *SubscriptionRefundUpdate) Where(ps ...predicate.SubscriptionRefund) *SubscriptionRefundUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *SubscriptionRefundUpdate) SetOrderID(v int64) *SubscriptionRefundUpdate {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *SubscriptionRefundUpdate) SetNillableOrderID(v *int64) *SubscriptionRefundUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *SubscriptionRefundUpdate) AddOrderID(v int64) *SubscriptionRefundUpdate {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionRefundUpdate) SetSubscriptionID(v int64) *SubscriptionRefundUpdate {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionRefundUpdate) SetNillableSubscriptionID(v *int64) *SubscriptionRefundUpdate {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *SubscriptionRefundUpdate) AddSubscriptionID(v int64) *SubscriptionRefundUpdate {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionRefundUpdate) SetStatus(v string) *SubscriptionRefundUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionRefundUpdate) SetNillableStatus(v *string) *SubscriptionRefundUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSnapshot sets the "snapshot" field.
func (_u *SubscriptionRefundUpdate) SetSnapshot(v jsontext.Value) *SubscriptionRefundUpdate {
	_u.mutation.SetSnapshot(v)
	return _u
}

// AppendSnapshot appends value to the "snapshot" field.
func (_u *SubscriptionRefundUpdate) AppendSnapshot(v jsontext.Value) *SubscriptionRefundUpdate {
	_u.mutation.AppendSnapshot(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SubscriptionRefundUpdate) SetCreatedAt(v time.Time) *SubscriptionRefundUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SubscriptionRefundUpdate) SetNillableCreatedAt(v *time.Time) *SubscriptionRefundUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionRefundUpdate) SetUpdatedAt(v time.Time) *SubscriptionRefundUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SubscriptionRefundMutation object of the builder.
func (_u *SubscriptionRefundUpdate) Mutation() *SubscriptionRefundMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionRefundUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionRefundUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionRefundUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionRefundUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionRefundUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionrefund.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SubscriptionRefundUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(subscriptionrefund.Table, subscriptionrefund.Columns, sqlgraph.NewFieldSpec(subscriptionrefund.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(subscriptionrefund.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(subscriptionrefund.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(subscriptionrefund.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(subscriptionrefund.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionrefund.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Snapshot(); ok {
		_spec.SetField(subscriptionrefund.FieldSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSnapshot(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, subscriptionrefund.FieldSnapshot, value)
		})
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionrefund.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionrefund.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionrefund.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionRefundUpdateOne is the builder for updating a single SubscriptionRefund entity.
type SubscriptionRefundUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionRefundMutation
}

// SetOrderID sets the "order_id" field.
func (_u *SubscriptionRefundUpdateOne) SetOrderID(v int64) *SubscriptionRefundUpdateOne {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *SubscriptionRefundUpdateOne) SetNillableOrderID(v *int64) *SubscriptionRefundUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *SubscriptionRefundUpdateOne) AddOrderID(v int64) *SubscriptionRefundUpdateOne {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionRefundUpdateOne) SetSubscriptionID(v int64) *SubscriptionRefundUpdateOne {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionRefundUpdateOne) SetNillableSubscriptionID(v *int64) *SubscriptionRefundUpdateOne {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *SubscriptionRefundUpdateOne) AddSubscriptionID(v int64) *SubscriptionRefundUpdateOne {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionRefundUpdateOne) SetStatus(v string) *SubscriptionRefundUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionRefundUpdateOne) SetNillableStatus(v *string) *SubscriptionRefundUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSnapshot sets the "snapshot" field.
func (_u *SubscriptionRefundUpdateOne) SetSnapshot(v jsontext.Value) *SubscriptionRefundUpdateOne {
	_u.mutation.SetSnapshot(v)
	return _u
}

// AppendSnapshot appends value to the "snapshot" field.
func (_u *SubscriptionRefundUpdateOne) AppendSnapshot(v jsontext.Value) *SubscriptionRefundUpdateOne {
	_u.mutation.AppendSnapshot(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SubscriptionRefundUpdateOne) SetCreatedAt(v time.Time) *SubscriptionRefundUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SubscriptionRefundUpdateOne) SetNillableCreatedAt(v *time.Time) *SubscriptionRefundUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionRefundUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionRefundUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SubscriptionRefundMutation object of the builder.
func (_u *SubscriptionRefundUpdateOne) Mutation() *SubscriptionRefundMutation {
	return _u.mutation
}

// Where appends a list predicates to the SubscriptionRefundUpdate builder.
func (_u *SubscriptionRefundUpdateOne) Where(ps ...predicate.SubscriptionRefund) *SubscriptionRefundUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionRefundUpdateOne) Select(field string, fields ...string) *SubscriptionRefundUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionRefund entity.
func (_u *SubscriptionRefundUpdateOne) Save(ctx context.Context) (*SubscriptionRefund, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionRefundUpdateOne) SaveX(ctx context.Context) *SubscriptionRefund {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionRefundUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionRefundUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionRefundUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionrefund.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SubscriptionRefundUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionRefund, err error) {
	_spec := sqlgraph.NewUpdateSpec(subscriptionrefund.Table, subscriptionrefund.Columns, sqlgraph.NewFieldSpec(subscriptionrefund.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionRefund.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionrefund.FieldID)
		for _, f := range fields {
			if !subscriptionrefund.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionrefund.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(subscriptionrefund.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(subscriptionrefund.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(subscriptionrefund.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(subscriptionrefund.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionrefund.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Snapshot(); ok {
		_spec.SetField(subscriptionrefund.FieldSnapshot, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSnapshot(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, subscriptionrefund.FieldSnapshot, value)
		})
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionrefund.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionrefund.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SubscriptionRefund{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionrefund.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
