// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionentitlementorder"
	"github.com/Wei-Shaw/sub2api/ent/usersubscriptionentitlement"
)

// SubscriptionEntitlementOrderCreate is the builder for creating a SubscriptionEntitlementOrder entity.
type SubscriptionEntitlementOrderCreate struct {
	config
	mutation *SubscriptionEntitlementOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetEntitlementID sets the "entitlement_id" field.
func (_c *SubscriptionEntitlementOrderCreate) SetEntitlementID(v int64) *SubscriptionEntitlementOrderCreate {
	_c.mutation.SetEntitlementID(v)
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *SubscriptionEntitlementOrderCreate) SetOrderID(v int64) *SubscriptionEntitlementOrderCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetLotIndex sets the "lot_index" field.
func (_c *SubscriptionEntitlementOrderCreate) SetLotIndex(v int) *SubscriptionEntitlementOrderCreate {
	_c.mutation.SetLotIndex(v)
	return _c
}

// SetNillableLotIndex sets the "lot_index" field if the given value is not nil.
func (_c *SubscriptionEntitlementOrderCreate) SetNillableLotIndex(v *int) *SubscriptionEntitlementOrderCreate {
	if v != nil {
		_c.SetLotIndex(*v)
	}
	return _c
}

// SetOperation sets the "operation" field.
func (_c *SubscriptionEntitlementOrderCreate) SetOperation(v string) *SubscriptionEntitlementOrderCreate {
	_c.mutation.SetOperation(v)
	return _c
}

// SetDaysAdded sets the "days_added" field.
func (_c *SubscriptionEntitlementOrderCreate) SetDaysAdded(v int) *SubscriptionEntitlementOrderCreate {
	_c.mutation.SetDaysAdded(v)
	return _c
}

// SetNillableDaysAdded sets the "days_added" field if the given value is not nil.
func (_c *SubscriptionEntitlementOrderCreate) SetNillableDaysAdded(v *int) *SubscriptionEntitlementOrderCreate {
	if v != nil {
		_c.SetDaysAdded(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionEntitlementOrderCreate) SetCreatedAt(v time.Time) *SubscriptionEntitlementOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionEntitlementOrderCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionEntitlementOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetEntitlement sets the "entitlement" edge to the UserSubscriptionEntitlement entity.
func (_c *SubscriptionEntitlementOrderCreate) SetEntitlement(v *UserSubscriptionEntitlement) *SubscriptionEntitlementOrderCreate {
	return _c.SetEntitlementID(v.ID)
}

// SetOrder sets the "order" edge to the PaymentOrder entity.
func (_c *SubscriptionEntitlementOrderCreate) SetOrder(v *PaymentOrder) *SubscriptionEntitlementOrderCreate {
	return _c.SetOrderID(v.ID)
}

// Mutation returns the SubscriptionEntitlementOrderMutation object of the builder.
func (_c *SubscriptionEntitlementOrderCreate) Mutation() *SubscriptionEntitlementOrderMutation {
	return _c.mutation
}

// Save creates the SubscriptionEntitlementOrder in the database.
func (_c *SubscriptionEntitlementOrderCreate) Save(ctx context.Context) (*SubscriptionEntitlementOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionEntitlementOrderCreate) SaveX(ctx context.Context) *SubscriptionEntitlementOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionEntitlementOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionEntitlementOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionEntitlementOrderCreate) defaults() {
	if _, ok := _c.mutation.LotIndex(); !ok {
		v := subscriptionentitlementorder.DefaultLotIndex
		_c.mutation.SetLotIndex(v)
	}
	if _, ok := _c.mutation.DaysAdded(); !ok {
		v := subscriptionentitlementorder.DefaultDaysAdded
		_c.mutation.SetDaysAdded(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subscriptionentitlementorder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionEntitlementOrderCreate) check() error {
	if _, ok := _c.mutation.EntitlementID(); !ok {
		return &ValidationError{Name: "entitlement_id", err: errors.New(`ent: missing required field "SubscriptionEntitlementOrder.entitlement_id"`)}
	}
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "SubscriptionEntitlementOrder.order_id"`)}
	}
	if _, ok := _c.mutation.LotIndex(); !ok {
		return &ValidationError{Name: "lot_index", err: errors.New(`ent: missing required field "SubscriptionEntitlementOrder.lot_index"`)}
	}
	if _, ok := _c.mutation.Operation(); !ok {
		return &ValidationError{Name: "operation", err: errors.New(`ent: missing required field "SubscriptionEntitlementOrder.operation"`)}
	}
	if v, ok := _c.mutation.Operation(); ok {
		if err := subscriptionentitlementorder.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEntitlementOrder.operation": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DaysAdded(); !ok {
		return &ValidationError{Name: "days_added", err: errors.New(`ent: missing required field "SubscriptionEntitlementOrder.days_added"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubscriptionEntitlementOrder.created_at"`)}
	}
	if len(_c.mutation.EntitlementIDs()) == 0 {
		return &ValidationError{Name: "entitlement", err: errors.New(`ent: missing required edge "SubscriptionEntitlementOrder.entitlement"`)}
	}
	if len(_c.mutation.OrderIDs()) == 0 {
		return &ValidationError{Name: "order", err: errors.New(`ent: missing required edge "SubscriptionEntitlementOrder.order"`)}
	}
	return nil
}

func (_c *SubscriptionEntitlementOrderCreate) sqlSave(ctx context.Context) (*SubscriptionEntitlementOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionEntitlementOrderCreate) createSpec() (*SubscriptionEntitlementOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionEntitlementOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionentitlementorder.Table, sqlgraph.NewFieldSpec(subscriptionentitlementorder.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.LotIndex(); ok {
		_spec.SetField(subscriptionentitlementorder.FieldLotIndex, field.TypeInt, value)
		_node.LotIndex = value
	}
	if value, ok := _c.mutation.Operation(); ok {
		_spec.SetField(subscriptionentitlementorder.FieldOperation, field.TypeString, value)
		_node.Operation = value
	}
	if value, ok := _c.mutation.DaysAdded(); ok {
		_spec.SetField(subscriptionentitlementorder.FieldDaysAdded, field.TypeInt, value)
		_node.DaysAdded = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionentitlementorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.EntitlementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionentitlementorder.EntitlementTable,
			Columns: []string{subscriptionentitlementorder.EntitlementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscriptionentitlement.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EntitlementID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionentitlementorder.OrderTable,
			Columns: []string{subscriptionentitlementorder.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionEntitlementOrder.Create().
//		SetEntitlementID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionEntitlementOrderUpsert) {
//			SetEntitlementID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionEntitlementOrderCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionEntitlementOrderUpsertOne {
	_c.conflict = opts
	return &SubscriptionEntitlementOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionEntitlementOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionEntitlementOrderCreate) OnConflictColumns(columns ...string) *SubscriptionEntitlementOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionEntitlementOrderUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionEntitlementOrderUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionEntitlementOrder node.
	SubscriptionEntitlementOrderUpsertOne struct {
		create *SubscriptionEntitlementOrderCreate
	}

	// SubscriptionEntitlementOrderUpsert is the "OnConflict" setter.
	SubscriptionEntitlementOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetEntitlementID sets the "entitlement_id" field.
func (u *SubscriptionEntitlementOrderUpsert) SetEntitlementID(v int64) *SubscriptionEntitlementOrderUpsert {
	u.Set(subscriptionentitlementorder.FieldEntitlementID, v)
	return u
}

// UpdateEntitlementID sets the "entitlement_id" field to the value that was provided on create.
func (u *SubscriptionEntitlementOrderUpsert) UpdateEntitlementID() *SubscriptionEntitlementOrderUpsert {
	u.SetExcluded(subscriptionentitlementorder.FieldEntitlementID)
	return u
}

// SetOrderID sets the "order_id" field.
func (u *SubscriptionEntitlementOrderUpsert) SetOrderID(v int64) *SubscriptionEntitlementOrderUpsert {
	u.Set(subscriptionentitlementorder.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *SubscriptionEntitlementOrderUpsert) UpdateOrderID() *SubscriptionEntitlementOrderUpsert {
	u.SetExcluded(subscriptionentitlementorder.FieldOrderID)
	return u
}

// SetLotIndex sets the "lot_index" field.
func (u *SubscriptionEntitlementOrderUpsert) SetLotIndex(v int) *SubscriptionEntitlementOrderUpsert {
	u.Set(subscriptionentitlementorder.FieldLotIndex, v)
	return u
}

// UpdateLotIndex sets the "lot_index" field to the value that was provided on create.
func (u *SubscriptionEntitlementOrderUpsert) UpdateLotIndex() *SubscriptionEntitlementOrderUpsert {
	u.SetExcluded(subscriptionentitlementorder.FieldLotIndex)
	return u
}

// AddLotIndex adds v to the "lot_index" field.
func (u *SubscriptionEntitlementOrderUpsert) AddLotIndex(v int) *SubscriptionEntitlementOrderUpsert {
	u.Add(subscriptionentitlementorder.FieldLotIndex, v)
	return u
}

// SetOperation sets the "operation" field.
func (u *SubscriptionEntitlementOrderUpsert) SetOperation(v string) *SubscriptionEntitlementOrderUpsert {
	u.Set(subscriptionentitlementorder.FieldOperation, v)
	return u
}

// UpdateOperation sets the "operation" field to the value that was provided on create.
func (u *SubscriptionEntitlementOrderUpsert) UpdateOperation() *SubscriptionEntitlementOrderUpsert {
	u.SetExcluded(subscriptionentitlementorder.FieldOperation)
	return u
}

// SetDaysAdded sets the "days_added" field.
func (u *SubscriptionEntitlementOrderUpsert) SetDaysAdded(v int) *SubscriptionEntitlementOrderUpsert {
	u.Set(subscriptionentitlementorder.FieldDaysAdded, v)
	return u
}

// UpdateDaysAdded sets the "days_added" field to the value that was provided on create.
func (u *SubscriptionEntitlementOrderUpsert) UpdateDaysAdded() *SubscriptionEntitlementOrderUpsert {
	u.SetExcluded(subscriptionentitlementorder.FieldDaysAdded)
	return u
}

// AddDaysAdded adds v to the "days_added" field.
func (u *SubscriptionEntitlementOrderUpsert) AddDaysAdded(v int) *SubscriptionEntitlementOrderUpsert {
	u.Add(subscriptionentitlementorder.FieldDaysAdded, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionEntitlementOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionEntitlementOrderUpsertOne) UpdateNewValues() *SubscriptionEntitlementOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscriptionentitlementorder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionEntitlementOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionEntitlementOrderUpsertOne) Ignore() *SubscriptionEntitlementOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionEntitlementOrderUpsertOne) DoNothing() *SubscriptionEntitlementOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionEntitlementOrderCreate.OnConflict
// documentation for more info.
func (u *SubscriptionEntitlementOrderUpsertOne) Update(set func(*SubscriptionEntitlementOrderUpsert)) *SubscriptionEntitlementOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionEntitlementOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetEntitlementID sets the "entitlement_id" field.
func (u *SubscriptionEntitlementOrderUpsertOne) SetEntitlementID(v int64) *SubscriptionEntitlementOrderUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.SetEntitlementID(v)
	})
}

// UpdateEntitlementID sets the "entitlement_id" field to the value that was provided on create.
func (u *SubscriptionEntitlementOrderUpsertOne) UpdateEntitlementID() *SubscriptionEntitlementOrderUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.UpdateEntitlementID()
	})
}

// SetOrderID sets the "order_id" field.
func (u *SubscriptionEntitlementOrderUpsertOne) SetOrderID(v int64) *SubscriptionEntitlementOrderUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *SubscriptionEntitlementOrderUpsertOne) UpdateOrderID() *SubscriptionEntitlementOrderUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.UpdateOrderID()
	})
}

// SetLotIndex sets the "lot_index" field.
func (u *SubscriptionEntitlementOrderUpsertOne) SetLotIndex(v int) *SubscriptionEntitlementOrderUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.SetLotIndex(v)
	})
}

// AddLotIndex adds v to the "lot_index" field.
func (u *SubscriptionEntitlementOrderUpsertOne) AddLotIndex(v int) *SubscriptionEntitlementOrderUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.AddLotIndex(v)
	})
}

// UpdateLotIndex sets the "lot_index" field to the value that was provided on create.
func (u *SubscriptionEntitlementOrderUpsertOne) UpdateLotIndex() *SubscriptionEntitlementOrderUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.UpdateLotIndex()
	})
}

// SetOperation sets the "operation" field.
func (u *SubscriptionEntitlementOrderUpsertOne) SetOperation(v string) *SubscriptionEntitlementOrderUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.SetOperation(v)
	})
}

// UpdateOperation sets the "operation" field to the value that was provided on create.
func (u *SubscriptionEntitlementOrderUpsertOne) UpdateOperation() *SubscriptionEntitlementOrderUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.UpdateOperation()
	})
}

// SetDaysAdded sets the "days_added" field.
func (u *SubscriptionEntitlementOrderUpsertOne) SetDaysAdded(v int) *SubscriptionEntitlementOrderUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.SetDaysAdded(v)
	})
}

// AddDaysAdded adds v to the "days_added" field.
func (u *SubscriptionEntitlementOrderUpsertOne) AddDaysAdded(v int) *SubscriptionEntitlementOrderUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.AddDaysAdded(v)
	})
}

// UpdateDaysAdded sets the "days_added" field to the value that was provided on create.
func (u *SubscriptionEntitlementOrderUpsertOne) UpdateDaysAdded() *SubscriptionEntitlementOrderUpsertOne {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.UpdateDaysAdded()
	})
}

// Exec executes the query.
func (u *SubscriptionEntitlementOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionEntitlementOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionEntitlementOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionEntitlementOrderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionEntitlementOrderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionEntitlementOrderCreateBulk is the builder for creating many SubscriptionEntitlementOrder entities in bulk.
type SubscriptionEntitlementOrderCreateBulk struct {
	config
	err      error
	builders []*SubscriptionEntitlementOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionEntitlementOrder entities in the database.
func (_c *SubscriptionEntitlementOrderCreateBulk) Save(ctx context.Context) ([]*SubscriptionEntitlementOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionEntitlementOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionEntitlementOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionEntitlementOrderCreateBulk) SaveX(ctx context.Context) []*SubscriptionEntitlementOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionEntitlementOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionEntitlementOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionEntitlementOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionEntitlementOrderUpsert) {
//			SetEntitlementID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionEntitlementOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionEntitlementOrderUpsertBulk {
	_c.conflict = opts
	return &SubscriptionEntitlementOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionEntitlementOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionEntitlementOrderCreateBulk) OnConflictColumns(columns ...string) *SubscriptionEntitlementOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionEntitlementOrderUpsertBulk{
		create: _c,
	}
}

// SubscriptionEntitlementOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionEntitlementOrder nodes.
type SubscriptionEntitlementOrderUpsertBulk struct {
	create *SubscriptionEntitlementOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionEntitlementOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionEntitlementOrderUpsertBulk) UpdateNewValues() *SubscriptionEntitlementOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscriptionentitlementorder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionEntitlementOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionEntitlementOrderUpsertBulk) Ignore() *SubscriptionEntitlementOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionEntitlementOrderUpsertBulk) DoNothing() *SubscriptionEntitlementOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionEntitlementOrderCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionEntitlementOrderUpsertBulk) Update(set func(*SubscriptionEntitlementOrderUpsert)) *SubscriptionEntitlementOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionEntitlementOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetEntitlementID sets the "entitlement_id" field.
func (u *SubscriptionEntitlementOrderUpsertBulk) SetEntitlementID(v int64) *SubscriptionEntitlementOrderUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.SetEntitlementID(v)
	})
}

// UpdateEntitlementID sets the "entitlement_id" field to the value that was provided on create.
func (u *SubscriptionEntitlementOrderUpsertBulk) UpdateEntitlementID() *SubscriptionEntitlementOrderUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.UpdateEntitlementID()
	})
}

// SetOrderID sets the "order_id" field.
func (u *SubscriptionEntitlementOrderUpsertBulk) SetOrderID(v int64) *SubscriptionEntitlementOrderUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *SubscriptionEntitlementOrderUpsertBulk) UpdateOrderID() *SubscriptionEntitlementOrderUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.UpdateOrderID()
	})
}

// SetLotIndex sets the "lot_index" field.
func (u *SubscriptionEntitlementOrderUpsertBulk) SetLotIndex(v int) *SubscriptionEntitlementOrderUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.SetLotIndex(v)
	})
}

// AddLotIndex adds v to the "lot_index" field.
func (u *SubscriptionEntitlementOrderUpsertBulk) AddLotIndex(v int) *SubscriptionEntitlementOrderUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.AddLotIndex(v)
	})
}

// UpdateLotIndex sets the "lot_index" field to the value that was provided on create.
func (u *SubscriptionEntitlementOrderUpsertBulk) UpdateLotIndex() *SubscriptionEntitlementOrderUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.UpdateLotIndex()
	})
}

// SetOperation sets the "operation" field.
func (u *SubscriptionEntitlementOrderUpsertBulk) SetOperation(v string) *SubscriptionEntitlementOrderUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.SetOperation(v)
	})
}

// UpdateOperation sets the "operation" field to the value that was provided on create.
func (u *SubscriptionEntitlementOrderUpsertBulk) UpdateOperation() *SubscriptionEntitlementOrderUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.UpdateOperation()
	})
}

// SetDaysAdded sets the "days_added" field.
func (u *SubscriptionEntitlementOrderUpsertBulk) SetDaysAdded(v int) *SubscriptionEntitlementOrderUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.SetDaysAdded(v)
	})
}

// AddDaysAdded adds v to the "days_added" field.
func (u *SubscriptionEntitlementOrderUpsertBulk) AddDaysAdded(v int) *SubscriptionEntitlementOrderUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.AddDaysAdded(v)
	})
}

// UpdateDaysAdded sets the "days_added" field to the value that was provided on create.
func (u *SubscriptionEntitlementOrderUpsertBulk) UpdateDaysAdded() *SubscriptionEntitlementOrderUpsertBulk {
	return u.Update(func(s *SubscriptionEntitlementOrderUpsert) {
		s.UpdateDaysAdded()
	})
}

// Exec executes the query.
func (u *SubscriptionEntitlementOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionEntitlementOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionEntitlementOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionEntitlementOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
