// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionentitlementorder"
	"github.com/Wei-Shaw/sub2api/ent/usersubscriptionentitlement"
)

// SubscriptionEntitlementOrderUpdate is the builder for updating SubscriptionEntitlementOrder entities.
type SubscriptionEntitlementOrderUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionEntitlementOrderMutation
}

// Where appends a list predicates to the SubscriptionEntitlementOrderUpdate builder.
func (_u *SubscriptionEntitlementOrderUpdate) Where(ps ...predicate.SubscriptionEntitlementOrder) *SubscriptionEntitlementOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEntitlementID sets the "entitlement_id" field.
func (_u *SubscriptionEntitlementOrderUpdate) SetEntitlementID(v int64) *SubscriptionEntitlementOrderUpdate {
	_u.mutation.SetEntitlementID(v)
	return _u
}

// SetNillableEntitlementID sets the "entitlement_id" field if the given value is not nil.
func (_u *SubscriptionEntitlementOrderUpdate) SetNillableEntitlementID(v *int64) *SubscriptionEntitlementOrderUpdate {
	if v != nil {
		_u.SetEntitlementID(*v)
	}
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *SubscriptionEntitlementOrderUpdate) SetOrderID(v int64) *SubscriptionEntitlementOrderUpdate {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *SubscriptionEntitlementOrderUpdate) SetNillableOrderID(v *int64) *SubscriptionEntitlementOrderUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// SetLotIndex sets the "lot_index" field.
func (_u *SubscriptionEntitlementOrderUpdate) SetLotIndex(v int) *SubscriptionEntitlementOrderUpdate {
	_u.mutation.ResetLotIndex()
	_u.mutation.SetLotIndex(v)
	return _u
}

// SetNillableLotIndex sets the "lot_index" field if the given value is not nil.
func (_u *SubscriptionEntitlementOrderUpdate) SetNillableLotIndex(v *int) *SubscriptionEntitlementOrderUpdate {
	if v != nil {
		_u.SetLotIndex(*v)
	}
	return _u
}

// AddLotIndex adds value to the "lot_index" field.
func (_u *SubscriptionEntitlementOrderUpdate) AddLotIndex(v int) *SubscriptionEntitlementOrderUpdate {
	_u.mutation.AddLotIndex(v)
	return _u
}

// SetOperation sets the "operation" field.
func (_u *SubscriptionEntitlementOrderUpdate) SetOperation(v string) *SubscriptionEntitlementOrderUpdate {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *SubscriptionEntitlementOrderUpdate) SetNillableOperation(v *string) *SubscriptionEntitlementOrderUpdate {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetDaysAdded sets the "days_added" field.
func (_u *SubscriptionEntitlementOrderUpdate) SetDaysAdded(v int) *SubscriptionEntitlementOrderUpdate {
	_u.mutation.ResetDaysAdded()
	_u.mutation.SetDaysAdded(v)
	return _u
}

// SetNillableDaysAdded sets the "days_added" field if the given value is not nil.
func (_u *SubscriptionEntitlementOrderUpdate) SetNillableDaysAdded(v *int) *SubscriptionEntitlementOrderUpdate {
	if v != nil {
		_u.SetDaysAdded(*v)
	}
	return _u
}

// AddDaysAdded adds value to the "days_added" field.
func (_u *SubscriptionEntitlementOrderUpdate) AddDaysAdded(v int) *SubscriptionEntitlementOrderUpdate {
	_u.mutation.AddDaysAdded(v)
	return _u
}

// SetBeforeExpiresAt sets the "before_expires_at" field.
func (_u *SubscriptionEntitlementOrderUpdate) SetBeforeExpiresAt(v time.Time) *SubscriptionEntitlementOrderUpdate {
	_u.mutation.SetBeforeExpiresAt(v)
	return _u
}

// SetNillableBeforeExpiresAt sets the "before_expires_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementOrderUpdate) SetNillableBeforeExpiresAt(v *time.Time) *SubscriptionEntitlementOrderUpdate {
	if v != nil {
		_u.SetBeforeExpiresAt(*v)
	}
	return _u
}

// ClearBeforeExpiresAt clears the value of the "before_expires_at" field.
func (_u *SubscriptionEntitlementOrderUpdate) ClearBeforeExpiresAt() *SubscriptionEntitlementOrderUpdate {
	_u.mutation.ClearBeforeExpiresAt()
	return _u
}

// SetAfterExpiresAt sets the "after_expires_at" field.
func (_u *SubscriptionEntitlementOrderUpdate) SetAfterExpiresAt(v time.Time) *SubscriptionEntitlementOrderUpdate {
	_u.mutation.SetAfterExpiresAt(v)
	return _u
}

// SetNillableAfterExpiresAt sets the "after_expires_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementOrderUpdate) SetNillableAfterExpiresAt(v *time.Time) *SubscriptionEntitlementOrderUpdate {
	if v != nil {
		_u.SetAfterExpiresAt(*v)
	}
	return _u
}

// ClearAfterExpiresAt clears the value of the "after_expires_at" field.
func (_u *SubscriptionEntitlementOrderUpdate) ClearAfterExpiresAt() *SubscriptionEntitlementOrderUpdate {
	_u.mutation.ClearAfterExpiresAt()
	return _u
}

// SetReversedAt sets the "reversed_at" field.
func (_u *SubscriptionEntitlementOrderUpdate) SetReversedAt(v time.Time) *SubscriptionEntitlementOrderUpdate {
	_u.mutation.SetReversedAt(v)
	return _u
}

// SetNillableReversedAt sets the "reversed_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementOrderUpdate) SetNillableReversedAt(v *time.Time) *SubscriptionEntitlementOrderUpdate {
	if v != nil {
		_u.SetReversedAt(*v)
	}
	return _u
}

// ClearReversedAt clears the value of the "reversed_at" field.
func (_u *SubscriptionEntitlementOrderUpdate) ClearReversedAt() *SubscriptionEntitlementOrderUpdate {
	_u.mutation.ClearReversedAt()
	return _u
}

// SetEntitlement sets the "entitlement" edge to the UserSubscriptionEntitlement entity.
func (_u *SubscriptionEntitlementOrderUpdate) SetEntitlement(v *UserSubscriptionEntitlement) *SubscriptionEntitlementOrderUpdate {
	return _u.SetEntitlementID(v.ID)
}

// SetOrder sets the "order" edge to the PaymentOrder entity.
func (_u *SubscriptionEntitlementOrderUpdate) SetOrder(v *PaymentOrder) *SubscriptionEntitlementOrderUpdate {
	return _u.SetOrderID(v.ID)
}

// Mutation returns the SubscriptionEntitlementOrderMutation object of the builder.
func (_u *SubscriptionEntitlementOrderUpdate) Mutation() *SubscriptionEntitlementOrderMutation {
	return _u.mutation
}

// ClearEntitlement clears the "entitlement" edge to the UserSubscriptionEntitlement entity.
func (_u *SubscriptionEntitlementOrderUpdate) ClearEntitlement() *SubscriptionEntitlementOrderUpdate {
	_u.mutation.ClearEntitlement()
	return _u
}

// ClearOrder clears the "order" edge to the PaymentOrder entity.
func (_u *SubscriptionEntitlementOrderUpdate) ClearOrder() *SubscriptionEntitlementOrderUpdate {
	_u.mutation.ClearOrder()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionEntitlementOrderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionEntitlementOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionEntitlementOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionEntitlementOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionEntitlementOrderUpdate) check() error {
	if v, ok := _u.mutation.Operation(); ok {
		if err := subscriptionentitlementorder.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEntitlementOrder.operation": %w`, err)}
		}
	}
	if _u.mutation.EntitlementCleared() && len(_u.mutation.EntitlementIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionEntitlementOrder.entitlement"`)
	}
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionEntitlementOrder.order"`)
	}
	return nil
}

func (_u *SubscriptionEntitlementOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionentitlementorder.Table, subscriptionentitlementorder.Columns, sqlgraph.NewFieldSpec(subscriptionentitlementorder.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LotIndex(); ok {
		_spec.SetField(subscriptionentitlementorder.FieldLotIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLotIndex(); ok {
		_spec.AddField(subscriptionentitlementorder.FieldLotIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(subscriptionentitlementorder.FieldOperation, field.TypeString, value)
	}
	if value, ok := _u.mutation.DaysAdded(); ok {
		_spec.SetField(subscriptionentitlementorder.FieldDaysAdded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDaysAdded(); ok {
		_spec.AddField(subscriptionentitlementorder.FieldDaysAdded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BeforeExpiresAt(); ok {
		_spec.SetField(subscriptionentitlementorder.FieldBeforeExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.BeforeExpiresAtCleared() {
		_spec.ClearField(subscriptionentitlementorder.FieldBeforeExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AfterExpiresAt(); ok {
		_spec.SetField(subscriptionentitlementorder.FieldAfterExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.AfterExpiresAtCleared() {
		_spec.ClearField(subscriptionentitlementorder.FieldAfterExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReversedAt(); ok {
		_spec.SetField(subscriptionentitlementorder.FieldReversedAt, field.TypeTime, value)
	}
	if _u.mutation.ReversedAtCleared() {
		_spec.ClearField(subscriptionentitlementorder.FieldReversedAt, field.TypeTime)
	}
	if _u.mutation.EntitlementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionentitlementorder.EntitlementTable,
			Columns: []string{subscriptionentitlementorder.EntitlementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscriptionentitlement.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntitlementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionentitlementorder.EntitlementTable,
			Columns: []string{subscriptionentitlementorder.EntitlementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscriptionentitlement.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionentitlementorder.OrderTable,
			Columns: []string{subscriptionentitlementorder.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionentitlementorder.OrderTable,
			Columns: []string{subscriptionentitlementorder.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionentitlementorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionEntitlementOrderUpdateOne is the builder for updating a single SubscriptionEntitlementOrder entity.
type SubscriptionEntitlementOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionEntitlementOrderMutation
}

// SetEntitlementID sets the "entitlement_id" field.
func (_u *SubscriptionEntitlementOrderUpdateOne) SetEntitlementID(v int64) *SubscriptionEntitlementOrderUpdateOne {
	_u.mutation.SetEntitlementID(v)
	return _u
}

// SetNillableEntitlementID sets the "entitlement_id" field if the given value is not nil.
func (_u *SubscriptionEntitlementOrderUpdateOne) SetNillableEntitlementID(v *int64) *SubscriptionEntitlementOrderUpdateOne {
	if v != nil {
		_u.SetEntitlementID(*v)
	}
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *SubscriptionEntitlementOrderUpdateOne) SetOrderID(v int64) *SubscriptionEntitlementOrderUpdateOne {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *SubscriptionEntitlementOrderUpdateOne) SetNillableOrderID(v *int64) *SubscriptionEntitlementOrderUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// SetLotIndex sets the "lot_index" field.
func (_u *SubscriptionEntitlementOrderUpdateOne) SetLotIndex(v int) *SubscriptionEntitlementOrderUpdateOne {
	_u.mutation.ResetLotIndex()
	_u.mutation.SetLotIndex(v)
	return _u
}

// SetNillableLotIndex sets the "lot_index" field if the given value is not nil.
func (_u *SubscriptionEntitlementOrderUpdateOne) SetNillableLotIndex(v *int) *SubscriptionEntitlementOrderUpdateOne {
	if v != nil {
		_u.SetLotIndex(*v)
	}
	return _u
}

// AddLotIndex adds value to the "lot_index" field.
func (_u *SubscriptionEntitlementOrderUpdateOne) AddLotIndex(v int) *SubscriptionEntitlementOrderUpdateOne {
	_u.mutation.AddLotIndex(v)
	return _u
}

// SetOperation sets the "operation" field.
func (_u *SubscriptionEntitlementOrderUpdateOne) SetOperation(v string) *SubscriptionEntitlementOrderUpdateOne {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *SubscriptionEntitlementOrderUpdateOne) SetNillableOperation(v *string) *SubscriptionEntitlementOrderUpdateOne {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetDaysAdded sets the "days_added" field.
func (_u *SubscriptionEntitlementOrderUpdateOne) SetDaysAdded(v int) *SubscriptionEntitlementOrderUpdateOne {
	_u.mutation.ResetDaysAdded()
	_u.mutation.SetDaysAdded(v)
	return _u
}

// SetNillableDaysAdded sets the "days_added" field if the given value is not nil.
func (_u *SubscriptionEntitlementOrderUpdateOne) SetNillableDaysAdded(v *int) *SubscriptionEntitlementOrderUpdateOne {
	if v != nil {
		_u.SetDaysAdded(*v)
	}
	return _u
}

// AddDaysAdded adds value to the "days_added" field.
func (_u *SubscriptionEntitlementOrderUpdateOne) AddDaysAdded(v int) *SubscriptionEntitlementOrderUpdateOne {
	_u.mutation.AddDaysAdded(v)
	return _u
}

// SetBeforeExpiresAt sets the "before_expires_at" field.
func (_u *SubscriptionEntitlementOrderUpdateOne) SetBeforeExpiresAt(v time.Time) *SubscriptionEntitlementOrderUpdateOne {
	_u.mutation.SetBeforeExpiresAt(v)
	return _u
}

// SetNillableBeforeExpiresAt sets the "before_expires_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementOrderUpdateOne) SetNillableBeforeExpiresAt(v *time.Time) *SubscriptionEntitlementOrderUpdateOne {
	if v != nil {
		_u.SetBeforeExpiresAt(*v)
	}
	return _u
}

// ClearBeforeExpiresAt clears the value of the "before_expires_at" field.
func (_u *SubscriptionEntitlementOrderUpdateOne) ClearBeforeExpiresAt() *SubscriptionEntitlementOrderUpdateOne {
	_u.mutation.ClearBeforeExpiresAt()
	return _u
}

// SetAfterExpiresAt sets the "after_expires_at" field.
func (_u *SubscriptionEntitlementOrderUpdateOne) SetAfterExpiresAt(v time.Time) *SubscriptionEntitlementOrderUpdateOne {
	_u.mutation.SetAfterExpiresAt(v)
	return _u
}

// SetNillableAfterExpiresAt sets the "after_expires_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementOrderUpdateOne) SetNillableAfterExpiresAt(v *time.Time) *SubscriptionEntitlementOrderUpdateOne {
	if v != nil {
		_u.SetAfterExpiresAt(*v)
	}
	return _u
}

// ClearAfterExpiresAt clears the value of the "after_expires_at" field.
func (_u *SubscriptionEntitlementOrderUpdateOne) ClearAfterExpiresAt() *SubscriptionEntitlementOrderUpdateOne {
	_u.mutation.ClearAfterExpiresAt()
	return _u
}

// SetReversedAt sets the "reversed_at" field.
func (_u *SubscriptionEntitlementOrderUpdateOne) SetReversedAt(v time.Time) *SubscriptionEntitlementOrderUpdateOne {
	_u.mutation.SetReversedAt(v)
	return _u
}

// SetNillableReversedAt sets the "reversed_at" field if the given value is not nil.
func (_u *SubscriptionEntitlementOrderUpdateOne) SetNillableReversedAt(v *time.Time) *SubscriptionEntitlementOrderUpdateOne {
	if v != nil {
		_u.SetReversedAt(*v)
	}
	return _u
}

// ClearReversedAt clears the value of the "reversed_at" field.
func (_u *SubscriptionEntitlementOrderUpdateOne) ClearReversedAt() *SubscriptionEntitlementOrderUpdateOne {
	_u.mutation.ClearReversedAt()
	return _u
}

// SetEntitlement sets the "entitlement" edge to the UserSubscriptionEntitlement entity.
func (_u *SubscriptionEntitlementOrderUpdateOne) SetEntitlement(v *UserSubscriptionEntitlement) *SubscriptionEntitlementOrderUpdateOne {
	return _u.SetEntitlementID(v.ID)
}

// SetOrder sets the "order" edge to the PaymentOrder entity.
func (_u *SubscriptionEntitlementOrderUpdateOne) SetOrder(v *PaymentOrder) *SubscriptionEntitlementOrderUpdateOne {
	return _u.SetOrderID(v.ID)
}

// Mutation returns the SubscriptionEntitlementOrderMutation object of the builder.
func (_u *SubscriptionEntitlementOrderUpdateOne) Mutation() *SubscriptionEntitlementOrderMutation {
	return _u.mutation
}

// ClearEntitlement clears the "entitlement" edge to the UserSubscriptionEntitlement entity.
func (_u *SubscriptionEntitlementOrderUpdateOne) ClearEntitlement() *SubscriptionEntitlementOrderUpdateOne {
	_u.mutation.ClearEntitlement()
	return _u
}

// ClearOrder clears the "order" edge to the PaymentOrder entity.
func (_u *SubscriptionEntitlementOrderUpdateOne) ClearOrder() *SubscriptionEntitlementOrderUpdateOne {
	_u.mutation.ClearOrder()
	return _u
}

// Where appends a list predicates to the SubscriptionEntitlementOrderUpdate builder.
func (_u *SubscriptionEntitlementOrderUpdateOne) Where(ps ...predicate.SubscriptionEntitlementOrder) *SubscriptionEntitlementOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionEntitlementOrderUpdateOne) Select(field string, fields ...string) *SubscriptionEntitlementOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionEntitlementOrder entity.
func (_u *SubscriptionEntitlementOrderUpdateOne) Save(ctx context.Context) (*SubscriptionEntitlementOrder, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionEntitlementOrderUpdateOne) SaveX(ctx context.Context) *SubscriptionEntitlementOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionEntitlementOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionEntitlementOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionEntitlementOrderUpdateOne) check() error {
	if v, ok := _u.mutation.Operation(); ok {
		if err := subscriptionentitlementorder.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "SubscriptionEntitlementOrder.operation": %w`, err)}
		}
	}
	if _u.mutation.EntitlementCleared() && len(_u.mutation.EntitlementIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionEntitlementOrder.entitlement"`)
	}
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubscriptionEntitlementOrder.order"`)
	}
	return nil
}

func (_u *SubscriptionEntitlementOrderUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionEntitlementOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionentitlementorder.Table, subscriptionentitlementorder.Columns, sqlgraph.NewFieldSpec(subscriptionentitlementorder.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionEntitlementOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionentitlementorder.FieldID)
		for _, f := range fields {
			if !subscriptionentitlementorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionentitlementorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LotIndex(); ok {
		_spec.SetField(subscriptionentitlementorder.FieldLotIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLotIndex(); ok {
		_spec.AddField(subscriptionentitlementorder.FieldLotIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(subscriptionentitlementorder.FieldOperation, field.TypeString, value)
	}
	if value, ok := _u.mutation.DaysAdded(); ok {
		_spec.SetField(subscriptionentitlementorder.FieldDaysAdded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDaysAdded(); ok {
		_spec.AddField(subscriptionentitlementorder.FieldDaysAdded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BeforeExpiresAt(); ok {
		_spec.SetField(subscriptionentitlementorder.FieldBeforeExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.BeforeExpiresAtCleared() {
		_spec.ClearField(subscriptionentitlementorder.FieldBeforeExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AfterExpiresAt(); ok {
		_spec.SetField(subscriptionentitlementorder.FieldAfterExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.AfterExpiresAtCleared() {
		_spec.ClearField(subscriptionentitlementorder.FieldAfterExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReversedAt(); ok {
		_spec.SetField(subscriptionentitlementorder.FieldReversedAt, field.TypeTime, value)
	}
	if _u.mutation.ReversedAtCleared() {
		_spec.ClearField(subscriptionentitlementorder.FieldReversedAt, field.TypeTime)
	}
	if _u.mutation.EntitlementCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionentitlementorder.EntitlementTable,
			Columns: []string{subscriptionentitlementorder.EntitlementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscriptionentitlement.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntitlementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionentitlementorder.EntitlementTable,
			Columns: []string{subscriptionentitlementorder.EntitlementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscriptionentitlement.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionentitlementorder.OrderTable,
			Columns: []string{subscriptionentitlementorder.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscriptionentitlementorder.OrderTable,
			Columns: []string{subscriptionentitlementorder.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubscriptionEntitlementOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionentitlementorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
