// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionentitlementorder"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplan"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
	"github.com/Wei-Shaw/sub2api/ent/usersubscriptionentitlement"
)

// UserSubscriptionEntitlementUpdate is the builder for updating UserSubscriptionEntitlement entities.
type UserSubscriptionEntitlementUpdate struct {
	config
	hooks    []Hook
	mutation *UserSubscriptionEntitlementMutation
}

// Where appends a list predicates to the UserSubscriptionEntitlementUpdate builder.
func (_u *UserSubscriptionEntitlementUpdate) Where(ps ...predicate.UserSubscriptionEntitlement) *UserSubscriptionEntitlementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserSubscriptionID sets the "user_subscription_id" field.
func (_u *UserSubscriptionEntitlementUpdate) SetUserSubscriptionID(v int64) *UserSubscriptionEntitlementUpdate {
	_u.mutation.SetUserSubscriptionID(v)
	return _u
}

// SetNillableUserSubscriptionID sets the "user_subscription_id" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdate) SetNillableUserSubscriptionID(v *int64) *UserSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetUserSubscriptionID(*v)
	}
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *UserSubscriptionEntitlementUpdate) SetPlanID(v int64) *UserSubscriptionEntitlementUpdate {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdate) SetNillablePlanID(v *int64) *UserSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// ClearPlanID clears the value of the "plan_id" field.
func (_u *UserSubscriptionEntitlementUpdate) ClearPlanID() *UserSubscriptionEntitlementUpdate {
	_u.mutation.ClearPlanID()
	return _u
}

// SetSourceOrderID sets the "source_order_id" field.
func (_u *UserSubscriptionEntitlementUpdate) SetSourceOrderID(v int64) *UserSubscriptionEntitlementUpdate {
	_u.mutation.SetSourceOrderID(v)
	return _u
}

// SetNillableSourceOrderID sets the "source_order_id" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdate) SetNillableSourceOrderID(v *int64) *UserSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetSourceOrderID(*v)
	}
	return _u
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (_u *UserSubscriptionEntitlementUpdate) ClearSourceOrderID() *UserSubscriptionEntitlementUpdate {
	_u.mutation.ClearSourceOrderID()
	return _u
}

// SetLotIndex sets the "lot_index" field.
func (_u *UserSubscriptionEntitlementUpdate) SetLotIndex(v int) *UserSubscriptionEntitlementUpdate {
	_u.mutation.ResetLotIndex()
	_u.mutation.SetLotIndex(v)
	return _u
}

// SetNillableLotIndex sets the "lot_index" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdate) SetNillableLotIndex(v *int) *UserSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetLotIndex(*v)
	}
	return _u
}

// AddLotIndex adds value to the "lot_index" field.
func (_u *UserSubscriptionEntitlementUpdate) AddLotIndex(v int) *UserSubscriptionEntitlementUpdate {
	_u.mutation.AddLotIndex(v)
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *UserSubscriptionEntitlementUpdate) SetSourceType(v string) *UserSubscriptionEntitlementUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdate) SetNillableSourceType(v *string) *UserSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceReference sets the "source_reference" field.
func (_u *UserSubscriptionEntitlementUpdate) SetSourceReference(v string) *UserSubscriptionEntitlementUpdate {
	_u.mutation.SetSourceReference(v)
	return _u
}

// SetNillableSourceReference sets the "source_reference" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdate) SetNillableSourceReference(v *string) *UserSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetSourceReference(*v)
	}
	return _u
}

// SetPurchaseMode sets the "purchase_mode" field.
func (_u *UserSubscriptionEntitlementUpdate) SetPurchaseMode(v string) *UserSubscriptionEntitlementUpdate {
	_u.mutation.SetPurchaseMode(v)
	return _u
}

// SetNillablePurchaseMode sets the "purchase_mode" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdate) SetNillablePurchaseMode(v *string) *UserSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetPurchaseMode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserSubscriptionEntitlementUpdate) SetStatus(v string) *UserSubscriptionEntitlementUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdate) SetNillableStatus(v *string) *UserSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *UserSubscriptionEntitlementUpdate) SetStartsAt(v time.Time) *UserSubscriptionEntitlementUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdate) SetNillableStartsAt(v *time.Time) *UserSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserSubscriptionEntitlementUpdate) SetExpiresAt(v time.Time) *UserSubscriptionEntitlementUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdate) SetNillableExpiresAt(v *time.Time) *UserSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_u *UserSubscriptionEntitlementUpdate) SetDailyLimitUsd(v float64) *UserSubscriptionEntitlementUpdate {
	_u.mutation.ResetDailyLimitUsd()
	_u.mutation.SetDailyLimitUsd(v)
	return _u
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdate) SetNillableDailyLimitUsd(v *float64) *UserSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetDailyLimitUsd(*v)
	}
	return _u
}

// AddDailyLimitUsd adds value to the "daily_limit_usd" field.
func (_u *UserSubscriptionEntitlementUpdate) AddDailyLimitUsd(v float64) *UserSubscriptionEntitlementUpdate {
	_u.mutation.AddDailyLimitUsd(v)
	return _u
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (_u *UserSubscriptionEntitlementUpdate) ClearDailyLimitUsd() *UserSubscriptionEntitlementUpdate {
	_u.mutation.ClearDailyLimitUsd()
	return _u
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (_u *UserSubscriptionEntitlementUpdate) SetWeeklyLimitUsd(v float64) *UserSubscriptionEntitlementUpdate {
	_u.mutation.ResetWeeklyLimitUsd()
	_u.mutation.SetWeeklyLimitUsd(v)
	return _u
}

// SetNillableWeeklyLimitUsd sets the "weekly_limit_usd" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdate) SetNillableWeeklyLimitUsd(v *float64) *UserSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetWeeklyLimitUsd(*v)
	}
	return _u
}

// AddWeeklyLimitUsd adds value to the "weekly_limit_usd" field.
func (_u *UserSubscriptionEntitlementUpdate) AddWeeklyLimitUsd(v float64) *UserSubscriptionEntitlementUpdate {
	_u.mutation.AddWeeklyLimitUsd(v)
	return _u
}

// ClearWeeklyLimitUsd clears the value of the "weekly_limit_usd" field.
func (_u *UserSubscriptionEntitlementUpdate) ClearWeeklyLimitUsd() *UserSubscriptionEntitlementUpdate {
	_u.mutation.ClearWeeklyLimitUsd()
	return _u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_u *UserSubscriptionEntitlementUpdate) SetMonthlyLimitUsd(v float64) *UserSubscriptionEntitlementUpdate {
	_u.mutation.ResetMonthlyLimitUsd()
	_u.mutation.SetMonthlyLimitUsd(v)
	return _u
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdate) SetNillableMonthlyLimitUsd(v *float64) *UserSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetMonthlyLimitUsd(*v)
	}
	return _u
}

// AddMonthlyLimitUsd adds value to the "monthly_limit_usd" field.
func (_u *UserSubscriptionEntitlementUpdate) AddMonthlyLimitUsd(v float64) *UserSubscriptionEntitlementUpdate {
	_u.mutation.AddMonthlyLimitUsd(v)
	return _u
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (_u *UserSubscriptionEntitlementUpdate) ClearMonthlyLimitUsd() *UserSubscriptionEntitlementUpdate {
	_u.mutation.ClearMonthlyLimitUsd()
	return _u
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (_u *UserSubscriptionEntitlementUpdate) SetDailyWindowStart(v time.Time) *UserSubscriptionEntitlementUpdate {
	_u.mutation.SetDailyWindowStart(v)
	return _u
}

// SetNillableDailyWindowStart sets the "daily_window_start" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdate) SetNillableDailyWindowStart(v *time.Time) *UserSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetDailyWindowStart(*v)
	}
	return _u
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (_u *UserSubscriptionEntitlementUpdate) ClearDailyWindowStart() *UserSubscriptionEntitlementUpdate {
	_u.mutation.ClearDailyWindowStart()
	return _u
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (_u *UserSubscriptionEntitlementUpdate) SetWeeklyWindowStart(v time.Time) *UserSubscriptionEntitlementUpdate {
	_u.mutation.SetWeeklyWindowStart(v)
	return _u
}

// SetNillableWeeklyWindowStart sets the "weekly_window_start" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdate) SetNillableWeeklyWindowStart(v *time.Time) *UserSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetWeeklyWindowStart(*v)
	}
	return _u
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (_u *UserSubscriptionEntitlementUpdate) ClearWeeklyWindowStart() *UserSubscriptionEntitlementUpdate {
	_u.mutation.ClearWeeklyWindowStart()
	return _u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_u *UserSubscriptionEntitlementUpdate) SetMonthlyWindowStart(v time.Time) *UserSubscriptionEntitlementUpdate {
	_u.mutation.SetMonthlyWindowStart(v)
	return _u
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdate) SetNillableMonthlyWindowStart(v *time.Time) *UserSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetMonthlyWindowStart(*v)
	}
	return _u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (_u *UserSubscriptionEntitlementUpdate) ClearMonthlyWindowStart() *UserSubscriptionEntitlementUpdate {
	_u.mutation.ClearMonthlyWindowStart()
	return _u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_u *UserSubscriptionEntitlementUpdate) SetDailyUsageUsd(v float64) *UserSubscriptionEntitlementUpdate {
	_u.mutation.ResetDailyUsageUsd()
	_u.mutation.SetDailyUsageUsd(v)
	return _u
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdate) SetNillableDailyUsageUsd(v *float64) *UserSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetDailyUsageUsd(*v)
	}
	return _u
}

// AddDailyUsageUsd adds value to the "daily_usage_usd" field.
func (_u *UserSubscriptionEntitlementUpdate) AddDailyUsageUsd(v float64) *UserSubscriptionEntitlementUpdate {
	_u.mutation.AddDailyUsageUsd(v)
	return _u
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (_u *UserSubscriptionEntitlementUpdate) SetWeeklyUsageUsd(v float64) *UserSubscriptionEntitlementUpdate {
	_u.mutation.ResetWeeklyUsageUsd()
	_u.mutation.SetWeeklyUsageUsd(v)
	return _u
}

// SetNillableWeeklyUsageUsd sets the "weekly_usage_usd" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdate) SetNillableWeeklyUsageUsd(v *float64) *UserSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetWeeklyUsageUsd(*v)
	}
	return _u
}

// AddWeeklyUsageUsd adds value to the "weekly_usage_usd" field.
func (_u *UserSubscriptionEntitlementUpdate) AddWeeklyUsageUsd(v float64) *UserSubscriptionEntitlementUpdate {
	_u.mutation.AddWeeklyUsageUsd(v)
	return _u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_u *UserSubscriptionEntitlementUpdate) SetMonthlyUsageUsd(v float64) *UserSubscriptionEntitlementUpdate {
	_u.mutation.ResetMonthlyUsageUsd()
	_u.mutation.SetMonthlyUsageUsd(v)
	return _u
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdate) SetNillableMonthlyUsageUsd(v *float64) *UserSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetMonthlyUsageUsd(*v)
	}
	return _u
}

// AddMonthlyUsageUsd adds value to the "monthly_usage_usd" field.
func (_u *UserSubscriptionEntitlementUpdate) AddMonthlyUsageUsd(v float64) *UserSubscriptionEntitlementUpdate {
	_u.mutation.AddMonthlyUsageUsd(v)
	return _u
}

// SetLifetimeUsageUsd sets the "lifetime_usage_usd" field.
func (_u *UserSubscriptionEntitlementUpdate) SetLifetimeUsageUsd(v float64) *UserSubscriptionEntitlementUpdate {
	_u.mutation.ResetLifetimeUsageUsd()
	_u.mutation.SetLifetimeUsageUsd(v)
	return _u
}

// SetNillableLifetimeUsageUsd sets the "lifetime_usage_usd" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdate) SetNillableLifetimeUsageUsd(v *float64) *UserSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetLifetimeUsageUsd(*v)
	}
	return _u
}

// AddLifetimeUsageUsd adds value to the "lifetime_usage_usd" field.
func (_u *UserSubscriptionEntitlementUpdate) AddLifetimeUsageUsd(v float64) *UserSubscriptionEntitlementUpdate {
	_u.mutation.AddLifetimeUsageUsd(v)
	return _u
}

// SetRefundedAt sets the "refunded_at" field.
func (_u *UserSubscriptionEntitlementUpdate) SetRefundedAt(v time.Time) *UserSubscriptionEntitlementUpdate {
	_u.mutation.SetRefundedAt(v)
	return _u
}

// SetNillableRefundedAt sets the "refunded_at" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdate) SetNillableRefundedAt(v *time.Time) *UserSubscriptionEntitlementUpdate {
	if v != nil {
		_u.SetRefundedAt(*v)
	}
	return _u
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (_u *UserSubscriptionEntitlementUpdate) ClearRefundedAt() *UserSubscriptionEntitlementUpdate {
	_u.mutation.ClearRefundedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserSubscriptionEntitlementUpdate) SetUpdatedAt(v time.Time) *UserSubscriptionEntitlementUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSubscriptionID sets the "subscription" edge to the UserSubscription entity by ID.
func (_u *UserSubscriptionEntitlementUpdate) SetSubscriptionID(id int64) *UserSubscriptionEntitlementUpdate {
	_u.mutation.SetSubscriptionID(id)
	return _u
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_u *UserSubscriptionEntitlementUpdate) SetSubscription(v *UserSubscription) *UserSubscriptionEntitlementUpdate {
	return _u.SetSubscriptionID(v.ID)
}

// SetPlan sets the "plan" edge to the SubscriptionPlan entity.
func (_u *UserSubscriptionEntitlementUpdate) SetPlan(v *SubscriptionPlan) *UserSubscriptionEntitlementUpdate {
	return _u.SetPlanID(v.ID)
}

// SetSourceOrder sets the "source_order" edge to the PaymentOrder entity.
func (_u *UserSubscriptionEntitlementUpdate) SetSourceOrder(v *PaymentOrder) *UserSubscriptionEntitlementUpdate {
	return _u.SetSourceOrderID(v.ID)
}

// AddOrderLineIDs adds the "order_lines" edge to the SubscriptionEntitlementOrder entity by IDs.
func (_u *UserSubscriptionEntitlementUpdate) AddOrderLineIDs(ids ...int64) *UserSubscriptionEntitlementUpdate {
	_u.mutation.AddOrderLineIDs(ids...)
	return _u
}

// AddOrderLines adds the "order_lines" edges to the SubscriptionEntitlementOrder entity.
func (_u *UserSubscriptionEntitlementUpdate) AddOrderLines(v ...*SubscriptionEntitlementOrder) *UserSubscriptionEntitlementUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrderLineIDs(ids...)
}

// Mutation returns the UserSubscriptionEntitlementMutation object of the builder.
func (_u *UserSubscriptionEntitlementUpdate) Mutation() *UserSubscriptionEntitlementMutation {
	return _u.mutation
}

// ClearSubscription clears the "subscription" edge to the UserSubscription entity.
func (_u *UserSubscriptionEntitlementUpdate) ClearSubscription() *UserSubscriptionEntitlementUpdate {
	_u.mutation.ClearSubscription()
	return _u
}

// ClearPlan clears the "plan" edge to the SubscriptionPlan entity.
func (_u *UserSubscriptionEntitlementUpdate) ClearPlan() *UserSubscriptionEntitlementUpdate {
	_u.mutation.ClearPlan()
	return _u
}

// ClearSourceOrder clears the "source_order" edge to the PaymentOrder entity.
func (_u *UserSubscriptionEntitlementUpdate) ClearSourceOrder() *UserSubscriptionEntitlementUpdate {
	_u.mutation.ClearSourceOrder()
	return _u
}

// ClearOrderLines clears all "order_lines" edges to the SubscriptionEntitlementOrder entity.
func (_u *UserSubscriptionEntitlementUpdate) ClearOrderLines() *UserSubscriptionEntitlementUpdate {
	_u.mutation.ClearOrderLines()
	return _u
}

// RemoveOrderLineIDs removes the "order_lines" edge to SubscriptionEntitlementOrder entities by IDs.
func (_u *UserSubscriptionEntitlementUpdate) RemoveOrderLineIDs(ids ...int64) *UserSubscriptionEntitlementUpdate {
	_u.mutation.RemoveOrderLineIDs(ids...)
	return _u
}

// RemoveOrderLines removes "order_lines" edges to SubscriptionEntitlementOrder entities.
func (_u *UserSubscriptionEntitlementUpdate) RemoveOrderLines(v ...*SubscriptionEntitlementOrder) *UserSubscriptionEntitlementUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrderLineIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserSubscriptionEntitlementUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserSubscriptionEntitlementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserSubscriptionEntitlementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserSubscriptionEntitlementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserSubscriptionEntitlementUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usersubscriptionentitlement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserSubscriptionEntitlementUpdate) check() error {
	if v, ok := _u.mutation.PurchaseMode(); ok {
		if err := usersubscriptionentitlement.PurchaseModeValidator(v); err != nil {
			return &ValidationError{Name: "purchase_mode", err: fmt.Errorf(`ent: validator failed for field "UserSubscriptionEntitlement.purchase_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := usersubscriptionentitlement.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserSubscriptionEntitlement.status": %w`, err)}
		}
	}
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserSubscriptionEntitlement.subscription"`)
	}
	return nil
}

func (_u *UserSubscriptionEntitlementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usersubscriptionentitlement.Table, usersubscriptionentitlement.Columns, sqlgraph.NewFieldSpec(usersubscriptionentitlement.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LotIndex(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldLotIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLotIndex(); ok {
		_spec.AddField(usersubscriptionentitlement.FieldLotIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceReference(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldSourceReference, field.TypeString, value)
	}
	if value, ok := _u.mutation.PurchaseMode(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldPurchaseMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DailyLimitUsd(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyLimitUsd(); ok {
		_spec.AddField(usersubscriptionentitlement.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.DailyLimitUsdCleared() {
		_spec.ClearField(usersubscriptionentitlement.FieldDailyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.WeeklyLimitUsd(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldWeeklyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyLimitUsd(); ok {
		_spec.AddField(usersubscriptionentitlement.FieldWeeklyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.WeeklyLimitUsdCleared() {
		_spec.ClearField(usersubscriptionentitlement.FieldWeeklyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyLimitUsd(); ok {
		_spec.AddField(usersubscriptionentitlement.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.MonthlyLimitUsdCleared() {
		_spec.ClearField(usersubscriptionentitlement.FieldMonthlyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DailyWindowStart(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldDailyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.DailyWindowStartCleared() {
		_spec.ClearField(usersubscriptionentitlement.FieldDailyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.WeeklyWindowStart(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldWeeklyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.WeeklyWindowStartCleared() {
		_spec.ClearField(usersubscriptionentitlement.FieldWeeklyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldMonthlyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.MonthlyWindowStartCleared() {
		_spec.ClearField(usersubscriptionentitlement.FieldMonthlyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.DailyUsageUsd(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyUsageUsd(); ok {
		_spec.AddField(usersubscriptionentitlement.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WeeklyUsageUsd(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyUsageUsd(); ok {
		_spec.AddField(usersubscriptionentitlement.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyUsageUsd(); ok {
		_spec.AddField(usersubscriptionentitlement.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.LifetimeUsageUsd(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldLifetimeUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLifetimeUsageUsd(); ok {
		_spec.AddField(usersubscriptionentitlement.FieldLifetimeUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RefundedAt(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldRefundedAt, field.TypeTime, value)
	}
	if _u.mutation.RefundedAtCleared() {
		_spec.ClearField(usersubscriptionentitlement.FieldRefundedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptionentitlement.SubscriptionTable,
			Columns: []string{usersubscriptionentitlement.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptionentitlement.SubscriptionTable,
			Columns: []string{usersubscriptionentitlement.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptionentitlement.PlanTable,
			Columns: []string{usersubscriptionentitlement.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptionentitlement.PlanTable,
			Columns: []string{usersubscriptionentitlement.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptionentitlement.SourceOrderTable,
			Columns: []string{usersubscriptionentitlement.SourceOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptionentitlement.SourceOrderTable,
			Columns: []string{usersubscriptionentitlement.SourceOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrderLinesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usersubscriptionentitlement.OrderLinesTable,
			Columns: []string{usersubscriptionentitlement.OrderLinesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionentitlementorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrderLinesIDs(); len(nodes) > 0 && !_u.mutation.OrderLinesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usersubscriptionentitlement.OrderLinesTable,
			Columns: []string{usersubscriptionentitlement.OrderLinesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionentitlementorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderLinesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usersubscriptionentitlement.OrderLinesTable,
			Columns: []string{usersubscriptionentitlement.OrderLinesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionentitlementorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersubscriptionentitlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserSubscriptionEntitlementUpdateOne is the builder for updating a single UserSubscriptionEntitlement entity.
type UserSubscriptionEntitlementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserSubscriptionEntitlementMutation
}

// SetUserSubscriptionID sets the "user_subscription_id" field.
func (_u *UserSubscriptionEntitlementUpdateOne) SetUserSubscriptionID(v int64) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.SetUserSubscriptionID(v)
	return _u
}

// SetNillableUserSubscriptionID sets the "user_subscription_id" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdateOne) SetNillableUserSubscriptionID(v *int64) *UserSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetUserSubscriptionID(*v)
	}
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *UserSubscriptionEntitlementUpdateOne) SetPlanID(v int64) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdateOne) SetNillablePlanID(v *int64) *UserSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// ClearPlanID clears the value of the "plan_id" field.
func (_u *UserSubscriptionEntitlementUpdateOne) ClearPlanID() *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.ClearPlanID()
	return _u
}

// SetSourceOrderID sets the "source_order_id" field.
func (_u *UserSubscriptionEntitlementUpdateOne) SetSourceOrderID(v int64) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.SetSourceOrderID(v)
	return _u
}

// SetNillableSourceOrderID sets the "source_order_id" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdateOne) SetNillableSourceOrderID(v *int64) *UserSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetSourceOrderID(*v)
	}
	return _u
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (_u *UserSubscriptionEntitlementUpdateOne) ClearSourceOrderID() *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.ClearSourceOrderID()
	return _u
}

// SetLotIndex sets the "lot_index" field.
func (_u *UserSubscriptionEntitlementUpdateOne) SetLotIndex(v int) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.ResetLotIndex()
	_u.mutation.SetLotIndex(v)
	return _u
}

// SetNillableLotIndex sets the "lot_index" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdateOne) SetNillableLotIndex(v *int) *UserSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetLotIndex(*v)
	}
	return _u
}

// AddLotIndex adds value to the "lot_index" field.
func (_u *UserSubscriptionEntitlementUpdateOne) AddLotIndex(v int) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.AddLotIndex(v)
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *UserSubscriptionEntitlementUpdateOne) SetSourceType(v string) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdateOne) SetNillableSourceType(v *string) *UserSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceReference sets the "source_reference" field.
func (_u *UserSubscriptionEntitlementUpdateOne) SetSourceReference(v string) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.SetSourceReference(v)
	return _u
}

// SetNillableSourceReference sets the "source_reference" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdateOne) SetNillableSourceReference(v *string) *UserSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetSourceReference(*v)
	}
	return _u
}

// SetPurchaseMode sets the "purchase_mode" field.
func (_u *UserSubscriptionEntitlementUpdateOne) SetPurchaseMode(v string) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.SetPurchaseMode(v)
	return _u
}

// SetNillablePurchaseMode sets the "purchase_mode" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdateOne) SetNillablePurchaseMode(v *string) *UserSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetPurchaseMode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserSubscriptionEntitlementUpdateOne) SetStatus(v string) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdateOne) SetNillableStatus(v *string) *UserSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *UserSubscriptionEntitlementUpdateOne) SetStartsAt(v time.Time) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdateOne) SetNillableStartsAt(v *time.Time) *UserSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserSubscriptionEntitlementUpdateOne) SetExpiresAt(v time.Time) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdateOne) SetNillableExpiresAt(v *time.Time) *UserSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_u *UserSubscriptionEntitlementUpdateOne) SetDailyLimitUsd(v float64) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.ResetDailyLimitUsd()
	_u.mutation.SetDailyLimitUsd(v)
	return _u
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdateOne) SetNillableDailyLimitUsd(v *float64) *UserSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetDailyLimitUsd(*v)
	}
	return _u
}

// AddDailyLimitUsd adds value to the "daily_limit_usd" field.
func (_u *UserSubscriptionEntitlementUpdateOne) AddDailyLimitUsd(v float64) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.AddDailyLimitUsd(v)
	return _u
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (_u *UserSubscriptionEntitlementUpdateOne) ClearDailyLimitUsd() *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.ClearDailyLimitUsd()
	return _u
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (_u *UserSubscriptionEntitlementUpdateOne) SetWeeklyLimitUsd(v float64) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.ResetWeeklyLimitUsd()
	_u.mutation.SetWeeklyLimitUsd(v)
	return _u
}

// SetNillableWeeklyLimitUsd sets the "weekly_limit_usd" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdateOne) SetNillableWeeklyLimitUsd(v *float64) *UserSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetWeeklyLimitUsd(*v)
	}
	return _u
}

// AddWeeklyLimitUsd adds value to the "weekly_limit_usd" field.
func (_u *UserSubscriptionEntitlementUpdateOne) AddWeeklyLimitUsd(v float64) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.AddWeeklyLimitUsd(v)
	return _u
}

// ClearWeeklyLimitUsd clears the value of the "weekly_limit_usd" field.
func (_u *UserSubscriptionEntitlementUpdateOne) ClearWeeklyLimitUsd() *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.ClearWeeklyLimitUsd()
	return _u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_u *UserSubscriptionEntitlementUpdateOne) SetMonthlyLimitUsd(v float64) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.ResetMonthlyLimitUsd()
	_u.mutation.SetMonthlyLimitUsd(v)
	return _u
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdateOne) SetNillableMonthlyLimitUsd(v *float64) *UserSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetMonthlyLimitUsd(*v)
	}
	return _u
}

// AddMonthlyLimitUsd adds value to the "monthly_limit_usd" field.
func (_u *UserSubscriptionEntitlementUpdateOne) AddMonthlyLimitUsd(v float64) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.AddMonthlyLimitUsd(v)
	return _u
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (_u *UserSubscriptionEntitlementUpdateOne) ClearMonthlyLimitUsd() *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.ClearMonthlyLimitUsd()
	return _u
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (_u *UserSubscriptionEntitlementUpdateOne) SetDailyWindowStart(v time.Time) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.SetDailyWindowStart(v)
	return _u
}

// SetNillableDailyWindowStart sets the "daily_window_start" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdateOne) SetNillableDailyWindowStart(v *time.Time) *UserSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetDailyWindowStart(*v)
	}
	return _u
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (_u *UserSubscriptionEntitlementUpdateOne) ClearDailyWindowStart() *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.ClearDailyWindowStart()
	return _u
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (_u *UserSubscriptionEntitlementUpdateOne) SetWeeklyWindowStart(v time.Time) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.SetWeeklyWindowStart(v)
	return _u
}

// SetNillableWeeklyWindowStart sets the "weekly_window_start" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdateOne) SetNillableWeeklyWindowStart(v *time.Time) *UserSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetWeeklyWindowStart(*v)
	}
	return _u
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (_u *UserSubscriptionEntitlementUpdateOne) ClearWeeklyWindowStart() *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.ClearWeeklyWindowStart()
	return _u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_u *UserSubscriptionEntitlementUpdateOne) SetMonthlyWindowStart(v time.Time) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.SetMonthlyWindowStart(v)
	return _u
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdateOne) SetNillableMonthlyWindowStart(v *time.Time) *UserSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetMonthlyWindowStart(*v)
	}
	return _u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (_u *UserSubscriptionEntitlementUpdateOne) ClearMonthlyWindowStart() *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.ClearMonthlyWindowStart()
	return _u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_u *UserSubscriptionEntitlementUpdateOne) SetDailyUsageUsd(v float64) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.ResetDailyUsageUsd()
	_u.mutation.SetDailyUsageUsd(v)
	return _u
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdateOne) SetNillableDailyUsageUsd(v *float64) *UserSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetDailyUsageUsd(*v)
	}
	return _u
}

// AddDailyUsageUsd adds value to the "daily_usage_usd" field.
func (_u *UserSubscriptionEntitlementUpdateOne) AddDailyUsageUsd(v float64) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.AddDailyUsageUsd(v)
	return _u
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (_u *UserSubscriptionEntitlementUpdateOne) SetWeeklyUsageUsd(v float64) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.ResetWeeklyUsageUsd()
	_u.mutation.SetWeeklyUsageUsd(v)
	return _u
}

// SetNillableWeeklyUsageUsd sets the "weekly_usage_usd" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdateOne) SetNillableWeeklyUsageUsd(v *float64) *UserSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetWeeklyUsageUsd(*v)
	}
	return _u
}

// AddWeeklyUsageUsd adds value to the "weekly_usage_usd" field.
func (_u *UserSubscriptionEntitlementUpdateOne) AddWeeklyUsageUsd(v float64) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.AddWeeklyUsageUsd(v)
	return _u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_u *UserSubscriptionEntitlementUpdateOne) SetMonthlyUsageUsd(v float64) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.ResetMonthlyUsageUsd()
	_u.mutation.SetMonthlyUsageUsd(v)
	return _u
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdateOne) SetNillableMonthlyUsageUsd(v *float64) *UserSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetMonthlyUsageUsd(*v)
	}
	return _u
}

// AddMonthlyUsageUsd adds value to the "monthly_usage_usd" field.
func (_u *UserSubscriptionEntitlementUpdateOne) AddMonthlyUsageUsd(v float64) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.AddMonthlyUsageUsd(v)
	return _u
}

// SetLifetimeUsageUsd sets the "lifetime_usage_usd" field.
func (_u *UserSubscriptionEntitlementUpdateOne) SetLifetimeUsageUsd(v float64) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.ResetLifetimeUsageUsd()
	_u.mutation.SetLifetimeUsageUsd(v)
	return _u
}

// SetNillableLifetimeUsageUsd sets the "lifetime_usage_usd" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdateOne) SetNillableLifetimeUsageUsd(v *float64) *UserSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetLifetimeUsageUsd(*v)
	}
	return _u
}

// AddLifetimeUsageUsd adds value to the "lifetime_usage_usd" field.
func (_u *UserSubscriptionEntitlementUpdateOne) AddLifetimeUsageUsd(v float64) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.AddLifetimeUsageUsd(v)
	return _u
}

// SetRefundedAt sets the "refunded_at" field.
func (_u *UserSubscriptionEntitlementUpdateOne) SetRefundedAt(v time.Time) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.SetRefundedAt(v)
	return _u
}

// SetNillableRefundedAt sets the "refunded_at" field if the given value is not nil.
func (_u *UserSubscriptionEntitlementUpdateOne) SetNillableRefundedAt(v *time.Time) *UserSubscriptionEntitlementUpdateOne {
	if v != nil {
		_u.SetRefundedAt(*v)
	}
	return _u
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (_u *UserSubscriptionEntitlementUpdateOne) ClearRefundedAt() *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.ClearRefundedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserSubscriptionEntitlementUpdateOne) SetUpdatedAt(v time.Time) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSubscriptionID sets the "subscription" edge to the UserSubscription entity by ID.
func (_u *UserSubscriptionEntitlementUpdateOne) SetSubscriptionID(id int64) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.SetSubscriptionID(id)
	return _u
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_u *UserSubscriptionEntitlementUpdateOne) SetSubscription(v *UserSubscription) *UserSubscriptionEntitlementUpdateOne {
	return _u.SetSubscriptionID(v.ID)
}

// SetPlan sets the "plan" edge to the SubscriptionPlan entity.
func (_u *UserSubscriptionEntitlementUpdateOne) SetPlan(v *SubscriptionPlan) *UserSubscriptionEntitlementUpdateOne {
	return _u.SetPlanID(v.ID)
}

// SetSourceOrder sets the "source_order" edge to the PaymentOrder entity.
func (_u *UserSubscriptionEntitlementUpdateOne) SetSourceOrder(v *PaymentOrder) *UserSubscriptionEntitlementUpdateOne {
	return _u.SetSourceOrderID(v.ID)
}

// AddOrderLineIDs adds the "order_lines" edge to the SubscriptionEntitlementOrder entity by IDs.
func (_u *UserSubscriptionEntitlementUpdateOne) AddOrderLineIDs(ids ...int64) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.AddOrderLineIDs(ids...)
	return _u
}

// AddOrderLines adds the "order_lines" edges to the SubscriptionEntitlementOrder entity.
func (_u *UserSubscriptionEntitlementUpdateOne) AddOrderLines(v ...*SubscriptionEntitlementOrder) *UserSubscriptionEntitlementUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrderLineIDs(ids...)
}

// Mutation returns the UserSubscriptionEntitlementMutation object of the builder.
func (_u *UserSubscriptionEntitlementUpdateOne) Mutation() *UserSubscriptionEntitlementMutation {
	return _u.mutation
}

// ClearSubscription clears the "subscription" edge to the UserSubscription entity.
func (_u *UserSubscriptionEntitlementUpdateOne) ClearSubscription() *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.ClearSubscription()
	return _u
}

// ClearPlan clears the "plan" edge to the SubscriptionPlan entity.
func (_u *UserSubscriptionEntitlementUpdateOne) ClearPlan() *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.ClearPlan()
	return _u
}

// ClearSourceOrder clears the "source_order" edge to the PaymentOrder entity.
func (_u *UserSubscriptionEntitlementUpdateOne) ClearSourceOrder() *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.ClearSourceOrder()
	return _u
}

// ClearOrderLines clears all "order_lines" edges to the SubscriptionEntitlementOrder entity.
func (_u *UserSubscriptionEntitlementUpdateOne) ClearOrderLines() *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.ClearOrderLines()
	return _u
}

// RemoveOrderLineIDs removes the "order_lines" edge to SubscriptionEntitlementOrder entities by IDs.
func (_u *UserSubscriptionEntitlementUpdateOne) RemoveOrderLineIDs(ids ...int64) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.RemoveOrderLineIDs(ids...)
	return _u
}

// RemoveOrderLines removes "order_lines" edges to SubscriptionEntitlementOrder entities.
func (_u *UserSubscriptionEntitlementUpdateOne) RemoveOrderLines(v ...*SubscriptionEntitlementOrder) *UserSubscriptionEntitlementUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrderLineIDs(ids...)
}

// Where appends a list predicates to the UserSubscriptionEntitlementUpdate builder.
func (_u *UserSubscriptionEntitlementUpdateOne) Where(ps ...predicate.UserSubscriptionEntitlement) *UserSubscriptionEntitlementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserSubscriptionEntitlementUpdateOne) Select(field string, fields ...string) *UserSubscriptionEntitlementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserSubscriptionEntitlement entity.
func (_u *UserSubscriptionEntitlementUpdateOne) Save(ctx context.Context) (*UserSubscriptionEntitlement, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserSubscriptionEntitlementUpdateOne) SaveX(ctx context.Context) *UserSubscriptionEntitlement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserSubscriptionEntitlementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserSubscriptionEntitlementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserSubscriptionEntitlementUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usersubscriptionentitlement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserSubscriptionEntitlementUpdateOne) check() error {
	if v, ok := _u.mutation.PurchaseMode(); ok {
		if err := usersubscriptionentitlement.PurchaseModeValidator(v); err != nil {
			return &ValidationError{Name: "purchase_mode", err: fmt.Errorf(`ent: validator failed for field "UserSubscriptionEntitlement.purchase_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := usersubscriptionentitlement.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserSubscriptionEntitlement.status": %w`, err)}
		}
	}
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserSubscriptionEntitlement.subscription"`)
	}
	return nil
}

func (_u *UserSubscriptionEntitlementUpdateOne) sqlSave(ctx context.Context) (_node *UserSubscriptionEntitlement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usersubscriptionentitlement.Table, usersubscriptionentitlement.Columns, sqlgraph.NewFieldSpec(usersubscriptionentitlement.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserSubscriptionEntitlement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usersubscriptionentitlement.FieldID)
		for _, f := range fields {
			if !usersubscriptionentitlement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usersubscriptionentitlement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LotIndex(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldLotIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLotIndex(); ok {
		_spec.AddField(usersubscriptionentitlement.FieldLotIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceReference(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldSourceReference, field.TypeString, value)
	}
	if value, ok := _u.mutation.PurchaseMode(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldPurchaseMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DailyLimitUsd(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyLimitUsd(); ok {
		_spec.AddField(usersubscriptionentitlement.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.DailyLimitUsdCleared() {
		_spec.ClearField(usersubscriptionentitlement.FieldDailyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.WeeklyLimitUsd(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldWeeklyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyLimitUsd(); ok {
		_spec.AddField(usersubscriptionentitlement.FieldWeeklyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.WeeklyLimitUsdCleared() {
		_spec.ClearField(usersubscriptionentitlement.FieldWeeklyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyLimitUsd(); ok {
		_spec.AddField(usersubscriptionentitlement.FieldMonthlyLimitUsd, field.TypeFloat64, value)
	}
	if _u.mutation.MonthlyLimitUsdCleared() {
		_spec.ClearField(usersubscriptionentitlement.FieldMonthlyLimitUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DailyWindowStart(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldDailyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.DailyWindowStartCleared() {
		_spec.ClearField(usersubscriptionentitlement.FieldDailyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.WeeklyWindowStart(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldWeeklyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.WeeklyWindowStartCleared() {
		_spec.ClearField(usersubscriptionentitlement.FieldWeeklyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldMonthlyWindowStart, field.TypeTime, value)
	}
	if _u.mutation.MonthlyWindowStartCleared() {
		_spec.ClearField(usersubscriptionentitlement.FieldMonthlyWindowStart, field.TypeTime)
	}
	if value, ok := _u.mutation.DailyUsageUsd(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyUsageUsd(); ok {
		_spec.AddField(usersubscriptionentitlement.FieldDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WeeklyUsageUsd(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyUsageUsd(); ok {
		_spec.AddField(usersubscriptionentitlement.FieldWeeklyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMonthlyUsageUsd(); ok {
		_spec.AddField(usersubscriptionentitlement.FieldMonthlyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.LifetimeUsageUsd(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldLifetimeUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLifetimeUsageUsd(); ok {
		_spec.AddField(usersubscriptionentitlement.FieldLifetimeUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RefundedAt(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldRefundedAt, field.TypeTime, value)
	}
	if _u.mutation.RefundedAtCleared() {
		_spec.ClearField(usersubscriptionentitlement.FieldRefundedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptionentitlement.SubscriptionTable,
			Columns: []string{usersubscriptionentitlement.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptionentitlement.SubscriptionTable,
			Columns: []string{usersubscriptionentitlement.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptionentitlement.PlanTable,
			Columns: []string{usersubscriptionentitlement.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptionentitlement.PlanTable,
			Columns: []string{usersubscriptionentitlement.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceOrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptionentitlement.SourceOrderTable,
			Columns: []string{usersubscriptionentitlement.SourceOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptionentitlement.SourceOrderTable,
			Columns: []string{usersubscriptionentitlement.SourceOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrderLinesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usersubscriptionentitlement.OrderLinesTable,
			Columns: []string{usersubscriptionentitlement.OrderLinesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionentitlementorder.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrderLinesIDs(); len(nodes) > 0 && !_u.mutation.OrderLinesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usersubscriptionentitlement.OrderLinesTable,
			Columns: []string{usersubscriptionentitlement.OrderLinesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionentitlementorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderLinesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usersubscriptionentitlement.OrderLinesTable,
			Columns: []string{usersubscriptionentitlement.OrderLinesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionentitlementorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserSubscriptionEntitlement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersubscriptionentitlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
