// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
	"github.com/Wei-Shaw/sub2api/ent/usersubscriptiongroup"
)

// UserSubscriptionGroupCreate is the builder for creating a UserSubscriptionGroup entity.
type UserSubscriptionGroupCreate struct {
	config
	mutation *UserSubscriptionGroupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserSubscriptionID sets the "user_subscription_id" field.
func (_c *UserSubscriptionGroupCreate) SetUserSubscriptionID(v int64) *UserSubscriptionGroupCreate {
	_c.mutation.SetUserSubscriptionID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *UserSubscriptionGroupCreate) SetGroupID(v int64) *UserSubscriptionGroupCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserSubscriptionGroupCreate) SetCreatedAt(v time.Time) *UserSubscriptionGroupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserSubscriptionGroupCreate) SetNillableCreatedAt(v *time.Time) *UserSubscriptionGroupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetSubscriptionID sets the "subscription" edge to the UserSubscription entity by ID.
func (_c *UserSubscriptionGroupCreate) SetSubscriptionID(id int64) *UserSubscriptionGroupCreate {
	_c.mutation.SetSubscriptionID(id)
	return _c
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_c *UserSubscriptionGroupCreate) SetSubscription(v *UserSubscription) *UserSubscriptionGroupCreate {
	return _c.SetSubscriptionID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *UserSubscriptionGroupCreate) SetGroup(v *Group) *UserSubscriptionGroupCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the UserSubscriptionGroupMutation object of the builder.
func (_c *UserSubscriptionGroupCreate) Mutation() *UserSubscriptionGroupMutation {
	return _c.mutation
}

// Save creates the UserSubscriptionGroup in the database.
func (_c *UserSubscriptionGroupCreate) Save(ctx context.Context) (*UserSubscriptionGroup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserSubscriptionGroupCreate) SaveX(ctx context.Context) *UserSubscriptionGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserSubscriptionGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserSubscriptionGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserSubscriptionGroupCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usersubscriptiongroup.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserSubscriptionGroupCreate) check() error {
	if _, ok := _c.mutation.UserSubscriptionID(); !ok {
		return &ValidationError{Name: "user_subscription_id", err: errors.New(`ent: missing required field "UserSubscriptionGroup.user_subscription_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "UserSubscriptionGroup.group_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserSubscriptionGroup.created_at"`)}
	}
	if len(_c.mutation.SubscriptionIDs()) == 0 {
		return &ValidationError{Name: "subscription", err: errors.New(`ent: missing required edge "UserSubscriptionGroup.subscription"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "UserSubscriptionGroup.group"`)}
	}
	return nil
}

func (_c *UserSubscriptionGroupCreate) sqlSave(ctx context.Context) (*UserSubscriptionGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserSubscriptionGroupCreate) createSpec() (*UserSubscriptionGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &UserSubscriptionGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usersubscriptiongroup.Table, sqlgraph.NewFieldSpec(usersubscriptiongroup.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usersubscriptiongroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptiongroup.SubscriptionTable,
			Columns: []string{usersubscriptiongroup.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserSubscriptionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptiongroup.GroupTable,
			Columns: []string{usersubscriptiongroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserSubscriptionGroup.Create().
//		SetUserSubscriptionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserSubscriptionGroupUpsert) {
//			SetUserSubscriptionID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserSubscriptionGroupCreate) OnConflict(opts ...sql.ConflictOption) *UserSubscriptionGroupUpsertOne {
	_c.conflict = opts
	return &UserSubscriptionGroupUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserSubscriptionGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserSubscriptionGroupCreate) OnConflictColumns(columns ...string) *UserSubscriptionGroupUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserSubscriptionGroupUpsertOne{
		create: _c,
	}
}

type (
	// UserSubscriptionGroupUpsertOne is the builder for "upsert"-ing
	//  one UserSubscriptionGroup node.
	UserSubscriptionGroupUpsertOne struct {
		create *UserSubscriptionGroupCreate
	}

	// UserSubscriptionGroupUpsert is the "OnConflict" setter.
	UserSubscriptionGroupUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserSubscriptionID sets the "user_subscription_id" field.
func (u *UserSubscriptionGroupUpsert) SetUserSubscriptionID(v int64) *UserSubscriptionGroupUpsert {
	u.Set(usersubscriptiongroup.FieldUserSubscriptionID, v)
	return u
}

// UpdateUserSubscriptionID sets the "user_subscription_id" field to the value that was provided on create.
func (u *UserSubscriptionGroupUpsert) UpdateUserSubscriptionID() *UserSubscriptionGroupUpsert {
	u.SetExcluded(usersubscriptiongroup.FieldUserSubscriptionID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *UserSubscriptionGroupUpsert) SetGroupID(v int64) *UserSubscriptionGroupUpsert {
	u.Set(usersubscriptiongroup.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserSubscriptionGroupUpsert) UpdateGroupID() *UserSubscriptionGroupUpsert {
	u.SetExcluded(usersubscriptiongroup.FieldGroupID)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *UserSubscriptionGroupUpsert) SetCreatedAt(v time.Time) *UserSubscriptionGroupUpsert {
	u.Set(usersubscriptiongroup.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UserSubscriptionGroupUpsert) UpdateCreatedAt() *UserSubscriptionGroupUpsert {
	u.SetExcluded(usersubscriptiongroup.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserSubscriptionGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserSubscriptionGroupUpsertOne) UpdateNewValues() *UserSubscriptionGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserSubscriptionGroup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserSubscriptionGroupUpsertOne) Ignore() *UserSubscriptionGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserSubscriptionGroupUpsertOne) DoNothing() *UserSubscriptionGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserSubscriptionGroupCreate.OnConflict
// documentation for more info.
func (u *UserSubscriptionGroupUpsertOne) Update(set func(*UserSubscriptionGroupUpsert)) *UserSubscriptionGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserSubscriptionGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserSubscriptionID sets the "user_subscription_id" field.
func (u *UserSubscriptionGroupUpsertOne) SetUserSubscriptionID(v int64) *UserSubscriptionGroupUpsertOne {
	return u.Update(func(s *UserSubscriptionGroupUpsert) {
		s.SetUserSubscriptionID(v)
	})
}

// UpdateUserSubscriptionID sets the "user_subscription_id" field to the value that was provided on create.
func (u *UserSubscriptionGroupUpsertOne) UpdateUserSubscriptionID() *UserSubscriptionGroupUpsertOne {
	return u.Update(func(s *UserSubscriptionGroupUpsert) {
		s.UpdateUserSubscriptionID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UserSubscriptionGroupUpsertOne) SetGroupID(v int64) *UserSubscriptionGroupUpsertOne {
	return u.Update(func(s *UserSubscriptionGroupUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserSubscriptionGroupUpsertOne) UpdateGroupID() *UserSubscriptionGroupUpsertOne {
	return u.Update(func(s *UserSubscriptionGroupUpsert) {
		s.UpdateGroupID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *UserSubscriptionGroupUpsertOne) SetCreatedAt(v time.Time) *UserSubscriptionGroupUpsertOne {
	return u.Update(func(s *UserSubscriptionGroupUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UserSubscriptionGroupUpsertOne) UpdateCreatedAt() *UserSubscriptionGroupUpsertOne {
	return u.Update(func(s *UserSubscriptionGroupUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *UserSubscriptionGroupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserSubscriptionGroupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserSubscriptionGroupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserSubscriptionGroupUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserSubscriptionGroupUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserSubscriptionGroupCreateBulk is the builder for creating many UserSubscriptionGroup entities in bulk.
type UserSubscriptionGroupCreateBulk struct {
	config
	err      error
	builders []*UserSubscriptionGroupCreate
	conflict []sql.ConflictOption
}

// Save creates the UserSubscriptionGroup entities in the database.
func (_c *UserSubscriptionGroupCreateBulk) Save(ctx context.Context) ([]*UserSubscriptionGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserSubscriptionGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserSubscriptionGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserSubscriptionGroupCreateBulk) SaveX(ctx context.Context) []*UserSubscriptionGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserSubscriptionGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserSubscriptionGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserSubscriptionGroup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserSubscriptionGroupUpsert) {
//			SetUserSubscriptionID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserSubscriptionGroupCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserSubscriptionGroupUpsertBulk {
	_c.conflict = opts
	return &UserSubscriptionGroupUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserSubscriptionGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserSubscriptionGroupCreateBulk) OnConflictColumns(columns ...string) *UserSubscriptionGroupUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserSubscriptionGroupUpsertBulk{
		create: _c,
	}
}

// UserSubscriptionGroupUpsertBulk is the builder for "upsert"-ing
// a bulk of UserSubscriptionGroup nodes.
type UserSubscriptionGroupUpsertBulk struct {
	create *UserSubscriptionGroupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserSubscriptionGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserSubscriptionGroupUpsertBulk) UpdateNewValues() *UserSubscriptionGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserSubscriptionGroup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserSubscriptionGroupUpsertBulk) Ignore() *UserSubscriptionGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserSubscriptionGroupUpsertBulk) DoNothing() *UserSubscriptionGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserSubscriptionGroupCreateBulk.OnConflict
// documentation for more info.
func (u *UserSubscriptionGroupUpsertBulk) Update(set func(*UserSubscriptionGroupUpsert)) *UserSubscriptionGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserSubscriptionGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserSubscriptionID sets the "user_subscription_id" field.
func (u *UserSubscriptionGroupUpsertBulk) SetUserSubscriptionID(v int64) *UserSubscriptionGroupUpsertBulk {
	return u.Update(func(s *UserSubscriptionGroupUpsert) {
		s.SetUserSubscriptionID(v)
	})
}

// UpdateUserSubscriptionID sets the "user_subscription_id" field to the value that was provided on create.
func (u *UserSubscriptionGroupUpsertBulk) UpdateUserSubscriptionID() *UserSubscriptionGroupUpsertBulk {
	return u.Update(func(s *UserSubscriptionGroupUpsert) {
		s.UpdateUserSubscriptionID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *UserSubscriptionGroupUpsertBulk) SetGroupID(v int64) *UserSubscriptionGroupUpsertBulk {
	return u.Update(func(s *UserSubscriptionGroupUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *UserSubscriptionGroupUpsertBulk) UpdateGroupID() *UserSubscriptionGroupUpsertBulk {
	return u.Update(func(s *UserSubscriptionGroupUpsert) {
		s.UpdateGroupID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *UserSubscriptionGroupUpsertBulk) SetCreatedAt(v time.Time) *UserSubscriptionGroupUpsertBulk {
	return u.Update(func(s *UserSubscriptionGroupUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UserSubscriptionGroupUpsertBulk) UpdateCreatedAt() *UserSubscriptionGroupUpsertBulk {
	return u.Update(func(s *UserSubscriptionGroupUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *UserSubscriptionGroupUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserSubscriptionGroupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserSubscriptionGroupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserSubscriptionGroupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
