// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
	"github.com/Wei-Shaw/sub2api/ent/usersubscriptiongroup"
)

// UserSubscriptionGroupUpdate is the builder for updating UserSubscriptionGroup entities.
type UserSubscriptionGroupUpdate struct {
	config
	hooks    []Hook
	mutation *UserSubscriptionGroupMutation
}

// Where appends a list predicates to the UserSubscriptionGroupUpdate builder.
func (_u *UserSubscriptionGroupUpdate) Where(ps ...predicate.UserSubscriptionGroup) *UserSubscriptionGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserSubscriptionID sets the "user_subscription_id" field.
func (_u *UserSubscriptionGroupUpdate) SetUserSubscriptionID(v int64) *UserSubscriptionGroupUpdate {
	_u.mutation.SetUserSubscriptionID(v)
	return _u
}

// SetNillableUserSubscriptionID sets the "user_subscription_id" field if the given value is not nil.
func (_u *UserSubscriptionGroupUpdate) SetNillableUserSubscriptionID(v *int64) *UserSubscriptionGroupUpdate {
	if v != nil {
		_u.SetUserSubscriptionID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *UserSubscriptionGroupUpdate) SetGroupID(v int64) *UserSubscriptionGroupUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UserSubscriptionGroupUpdate) SetNillableGroupID(v *int64) *UserSubscriptionGroupUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserSubscriptionGroupUpdate) SetCreatedAt(v time.Time) *UserSubscriptionGroupUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserSubscriptionGroupUpdate) SetNillableCreatedAt(v *time.Time) *UserSubscriptionGroupUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription" edge to the UserSubscription entity by ID.
func (_u *UserSubscriptionGroupUpdate) SetSubscriptionID(id int64) *UserSubscriptionGroupUpdate {
	_u.mutation.SetSubscriptionID(id)
	return _u
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_u *UserSubscriptionGroupUpdate) SetSubscription(v *UserSubscription) *UserSubscriptionGroupUpdate {
	return _u.SetSubscriptionID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *UserSubscriptionGroupUpdate) SetGroup(v *Group) *UserSubscriptionGroupUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the UserSubscriptionGroupMutation object of the builder.
func (_u *UserSubscriptionGroupUpdate) Mutation() *UserSubscriptionGroupMutation {
	return _u.mutation
}

// ClearSubscription clears the "subscription" edge to the UserSubscription entity.
func (_u *UserSubscriptionGroupUpdate) ClearSubscription() *UserSubscriptionGroupUpdate {
	_u.mutation.ClearSubscription()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *UserSubscriptionGroupUpdate) ClearGroup() *UserSubscriptionGroupUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserSubscriptionGroupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserSubscriptionGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserSubscriptionGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserSubscriptionGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserSubscriptionGroupUpdate) check() error {
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserSubscriptionGroup.subscription"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserSubscriptionGroup.group"`)
	}
	return nil
}

func (_u *UserSubscriptionGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usersubscriptiongroup.Table, usersubscriptiongroup.Columns, sqlgraph.NewFieldSpec(usersubscriptiongroup.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(usersubscriptiongroup.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptiongroup.SubscriptionTable,
			Columns: []string{usersubscriptiongroup.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptiongroup.SubscriptionTable,
			Columns: []string{usersubscriptiongroup.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptiongroup.GroupTable,
			Columns: []string{usersubscriptiongroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptiongroup.GroupTable,
			Columns: []string{usersubscriptiongroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersubscriptiongroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserSubscriptionGroupUpdateOne is the builder for updating a single UserSubscriptionGroup entity.
type UserSubscriptionGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserSubscriptionGroupMutation
}

// SetUserSubscriptionID sets the "user_subscription_id" field.
func (_u *UserSubscriptionGroupUpdateOne) SetUserSubscriptionID(v int64) *UserSubscriptionGroupUpdateOne {
	_u.mutation.SetUserSubscriptionID(v)
	return _u
}

// SetNillableUserSubscriptionID sets the "user_subscription_id" field if the given value is not nil.
func (_u *UserSubscriptionGroupUpdateOne) SetNillableUserSubscriptionID(v *int64) *UserSubscriptionGroupUpdateOne {
	if v != nil {
		_u.SetUserSubscriptionID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *UserSubscriptionGroupUpdateOne) SetGroupID(v int64) *UserSubscriptionGroupUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *UserSubscriptionGroupUpdateOne) SetNillableGroupID(v *int64) *UserSubscriptionGroupUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserSubscriptionGroupUpdateOne) SetCreatedAt(v time.Time) *UserSubscriptionGroupUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserSubscriptionGroupUpdateOne) SetNillableCreatedAt(v *time.Time) *UserSubscriptionGroupUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetSubscriptionID sets the "subscription" edge to the UserSubscription entity by ID.
func (_u *UserSubscriptionGroupUpdateOne) SetSubscriptionID(id int64) *UserSubscriptionGroupUpdateOne {
	_u.mutation.SetSubscriptionID(id)
	return _u
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_u *UserSubscriptionGroupUpdateOne) SetSubscription(v *UserSubscription) *UserSubscriptionGroupUpdateOne {
	return _u.SetSubscriptionID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *UserSubscriptionGroupUpdateOne) SetGroup(v *Group) *UserSubscriptionGroupUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the UserSubscriptionGroupMutation object of the builder.
func (_u *UserSubscriptionGroupUpdateOne) Mutation() *UserSubscriptionGroupMutation {
	return _u.mutation
}

// ClearSubscription clears the "subscription" edge to the UserSubscription entity.
func (_u *UserSubscriptionGroupUpdateOne) ClearSubscription() *UserSubscriptionGroupUpdateOne {
	_u.mutation.ClearSubscription()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *UserSubscriptionGroupUpdateOne) ClearGroup() *UserSubscriptionGroupUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the UserSubscriptionGroupUpdate builder.
func (_u *UserSubscriptionGroupUpdateOne) Where(ps ...predicate.UserSubscriptionGroup) *UserSubscriptionGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserSubscriptionGroupUpdateOne) Select(field string, fields ...string) *UserSubscriptionGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserSubscriptionGroup entity.
func (_u *UserSubscriptionGroupUpdateOne) Save(ctx context.Context) (*UserSubscriptionGroup, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserSubscriptionGroupUpdateOne) SaveX(ctx context.Context) *UserSubscriptionGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserSubscriptionGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserSubscriptionGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserSubscriptionGroupUpdateOne) check() error {
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserSubscriptionGroup.subscription"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserSubscriptionGroup.group"`)
	}
	return nil
}

func (_u *UserSubscriptionGroupUpdateOne) sqlSave(ctx context.Context) (_node *UserSubscriptionGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usersubscriptiongroup.Table, usersubscriptiongroup.Columns, sqlgraph.NewFieldSpec(usersubscriptiongroup.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserSubscriptionGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usersubscriptiongroup.FieldID)
		for _, f := range fields {
			if !usersubscriptiongroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usersubscriptiongroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(usersubscriptiongroup.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptiongroup.SubscriptionTable,
			Columns: []string{usersubscriptiongroup.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptiongroup.SubscriptionTable,
			Columns: []string{usersubscriptiongroup.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptiongroup.GroupTable,
			Columns: []string{usersubscriptiongroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptiongroup.GroupTable,
			Columns: []string{usersubscriptiongroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserSubscriptionGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersubscriptiongroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
