// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplan"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
	"github.com/Wei-Shaw/sub2api/ent/usersubscriptionentitlement"
)

// UserSubscriptionEntitlement is the model entity for the UserSubscriptionEntitlement schema.
type UserSubscriptionEntitlement struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserSubscriptionID holds the value of the "user_subscription_id" field.
	UserSubscriptionID int64 `json:"user_subscription_id,omitempty"`
	// PlanID holds the value of the "plan_id" field.
	PlanID *int64 `json:"plan_id,omitempty"`
	// SourceOrderID holds the value of the "source_order_id" field.
	SourceOrderID *int64 `json:"source_order_id,omitempty"`
	// LotIndex holds the value of the "lot_index" field.
	LotIndex int `json:"lot_index,omitempty"`
	// SourceType holds the value of the "source_type" field.
	SourceType string `json:"source_type,omitempty"`
	// SourceReference holds the value of the "source_reference" field.
	SourceReference string `json:"source_reference,omitempty"`
	// PurchaseMode holds the value of the "purchase_mode" field.
	PurchaseMode string `json:"purchase_mode,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// StartsAt holds the value of the "starts_at" field.
	StartsAt time.Time `json:"starts_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// DailyLimitUsd holds the value of the "daily_limit_usd" field.
	DailyLimitUsd *float64 `json:"daily_limit_usd,omitempty"`
	// WeeklyLimitUsd holds the value of the "weekly_limit_usd" field.
	WeeklyLimitUsd *float64 `json:"weekly_limit_usd,omitempty"`
	// MonthlyLimitUsd holds the value of the "monthly_limit_usd" field.
	MonthlyLimitUsd *float64 `json:"monthly_limit_usd,omitempty"`
	// DailyWindowStart holds the value of the "daily_window_start" field.
	DailyWindowStart *time.Time `json:"daily_window_start,omitempty"`
	// WeeklyWindowStart holds the value of the "weekly_window_start" field.
	WeeklyWindowStart *time.Time `json:"weekly_window_start,omitempty"`
	// MonthlyWindowStart holds the value of the "monthly_window_start" field.
	MonthlyWindowStart *time.Time `json:"monthly_window_start,omitempty"`
	// DailyUsageUsd holds the value of the "daily_usage_usd" field.
	DailyUsageUsd float64 `json:"daily_usage_usd,omitempty"`
	// WeeklyUsageUsd holds the value of the "weekly_usage_usd" field.
	WeeklyUsageUsd float64 `json:"weekly_usage_usd,omitempty"`
	// MonthlyUsageUsd holds the value of the "monthly_usage_usd" field.
	MonthlyUsageUsd float64 `json:"monthly_usage_usd,omitempty"`
	// LifetimeUsageUsd holds the value of the "lifetime_usage_usd" field.
	LifetimeUsageUsd float64 `json:"lifetime_usage_usd,omitempty"`
	// RefundedAt holds the value of the "refunded_at" field.
	RefundedAt *time.Time `json:"refunded_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserSubscriptionEntitlementQuery when eager-loading is set.
	Edges        UserSubscriptionEntitlementEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserSubscriptionEntitlementEdges holds the relations/edges for other nodes in the graph.
type UserSubscriptionEntitlementEdges struct {
	// Subscription holds the value of the subscription edge.
	Subscription *UserSubscription `json:"subscription,omitempty"`
	// Plan holds the value of the plan edge.
	Plan *SubscriptionPlan `json:"plan,omitempty"`
	// SourceOrder holds the value of the source_order edge.
	SourceOrder *PaymentOrder `json:"source_order,omitempty"`
	// OrderLines holds the value of the order_lines edge.
	OrderLines []*SubscriptionEntitlementOrder `json:"order_lines,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// SubscriptionOrErr returns the Subscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserSubscriptionEntitlementEdges) SubscriptionOrErr() (*UserSubscription, error) {
	if e.Subscription != nil {
		return e.Subscription, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: usersubscription.Label}
	}
	return nil, &NotLoadedError{edge: "subscription"}
}

// PlanOrErr returns the Plan value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserSubscriptionEntitlementEdges) PlanOrErr() (*SubscriptionPlan, error) {
	if e.Plan != nil {
		return e.Plan, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: subscriptionplan.Label}
	}
	return nil, &NotLoadedError{edge: "plan"}
}

// SourceOrderOrErr returns the SourceOrder value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserSubscriptionEntitlementEdges) SourceOrderOrErr() (*PaymentOrder, error) {
	if e.SourceOrder != nil {
		return e.SourceOrder, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: paymentorder.Label}
	}
	return nil, &NotLoadedError{edge: "source_order"}
}

// OrderLinesOrErr returns the OrderLines value or an error if the edge
// was not loaded in eager-loading.
func (e UserSubscriptionEntitlementEdges) OrderLinesOrErr() ([]*SubscriptionEntitlementOrder, error) {
	if e.loadedTypes[3] {
		return e.OrderLines, nil
	}
	return nil, &NotLoadedError{edge: "order_lines"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserSubscriptionEntitlement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usersubscriptionentitlement.FieldDailyLimitUsd, usersubscriptionentitlement.FieldWeeklyLimitUsd, usersubscriptionentitlement.FieldMonthlyLimitUsd, usersubscriptionentitlement.FieldDailyUsageUsd, usersubscriptionentitlement.FieldWeeklyUsageUsd, usersubscriptionentitlement.FieldMonthlyUsageUsd, usersubscriptionentitlement.FieldLifetimeUsageUsd:
			values[i] = new(sql.NullFloat64)
		case usersubscriptionentitlement.FieldID, usersubscriptionentitlement.FieldUserSubscriptionID, usersubscriptionentitlement.FieldPlanID, usersubscriptionentitlement.FieldSourceOrderID, usersubscriptionentitlement.FieldLotIndex:
			values[i] = new(sql.NullInt64)
		case usersubscriptionentitlement.FieldSourceType, usersubscriptionentitlement.FieldSourceReference, usersubscriptionentitlement.FieldPurchaseMode, usersubscriptionentitlement.FieldStatus:
			values[i] = new(sql.NullString)
		case usersubscriptionentitlement.FieldStartsAt, usersubscriptionentitlement.FieldExpiresAt, usersubscriptionentitlement.FieldDailyWindowStart, usersubscriptionentitlement.FieldWeeklyWindowStart, usersubscriptionentitlement.FieldMonthlyWindowStart, usersubscriptionentitlement.FieldRefundedAt, usersubscriptionentitlement.FieldCreatedAt, usersubscriptionentitlement.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserSubscriptionEntitlement fields.
func (_m *UserSubscriptionEntitlement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usersubscriptionentitlement.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usersubscriptionentitlement.FieldUserSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_subscription_id", values[i])
			} else if value.Valid {
				_m.UserSubscriptionID = value.Int64
			}
		case usersubscriptionentitlement.FieldPlanID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field plan_id", values[i])
			} else if value.Valid {
				_m.PlanID = new(int64)
				*_m.PlanID = value.Int64
			}
		case usersubscriptionentitlement.FieldSourceOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field source_order_id", values[i])
			} else if value.Valid {
				_m.SourceOrderID = new(int64)
				*_m.SourceOrderID = value.Int64
			}
		case usersubscriptionentitlement.FieldLotIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lot_index", values[i])
			} else if value.Valid {
				_m.LotIndex = int(value.Int64)
			}
		case usersubscriptionentitlement.FieldSourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_type", values[i])
			} else if value.Valid {
				_m.SourceType = value.String
			}
		case usersubscriptionentitlement.FieldSourceReference:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_reference", values[i])
			} else if value.Valid {
				_m.SourceReference = value.String
			}
		case usersubscriptionentitlement.FieldPurchaseMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field purchase_mode", values[i])
			} else if value.Valid {
				_m.PurchaseMode = value.String
			}
		case usersubscriptionentitlement.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case usersubscriptionentitlement.FieldStartsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starts_at", values[i])
			} else if value.Valid {
				_m.StartsAt = value.Time
			}
		case usersubscriptionentitlement.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case usersubscriptionentitlement.FieldDailyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_limit_usd", values[i])
			} else if value.Valid {
				_m.DailyLimitUsd = new(float64)
				*_m.DailyLimitUsd = value.Float64
			}
		case usersubscriptionentitlement.FieldWeeklyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field weekly_limit_usd", values[i])
			} else if value.Valid {
				_m.WeeklyLimitUsd = new(float64)
				*_m.WeeklyLimitUsd = value.Float64
			}
		case usersubscriptionentitlement.FieldMonthlyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_limit_usd", values[i])
			} else if value.Valid {
				_m.MonthlyLimitUsd = new(float64)
				*_m.MonthlyLimitUsd = value.Float64
			}
		case usersubscriptionentitlement.FieldDailyWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field daily_window_start", values[i])
			} else if value.Valid {
				_m.DailyWindowStart = new(time.Time)
				*_m.DailyWindowStart = value.Time
			}
		case usersubscriptionentitlement.FieldWeeklyWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field weekly_window_start", values[i])
			} else if value.Valid {
				_m.WeeklyWindowStart = new(time.Time)
				*_m.WeeklyWindowStart = value.Time
			}
		case usersubscriptionentitlement.FieldMonthlyWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_window_start", values[i])
			} else if value.Valid {
				_m.MonthlyWindowStart = new(time.Time)
				*_m.MonthlyWindowStart = value.Time
			}
		case usersubscriptionentitlement.FieldDailyUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_usage_usd", values[i])
			} else if value.Valid {
				_m.DailyUsageUsd = value.Float64
			}
		case usersubscriptionentitlement.FieldWeeklyUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field weekly_usage_usd", values[i])
			} else if value.Valid {
				_m.WeeklyUsageUsd = value.Float64
			}
		case usersubscriptionentitlement.FieldMonthlyUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_usage_usd", values[i])
			} else if value.Valid {
				_m.MonthlyUsageUsd = value.Float64
			}
		case usersubscriptionentitlement.FieldLifetimeUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field lifetime_usage_usd", values[i])
			} else if value.Valid {
				_m.LifetimeUsageUsd = value.Float64
			}
		case usersubscriptionentitlement.FieldRefundedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field refunded_at", values[i])
			} else if value.Valid {
				_m.RefundedAt = new(time.Time)
				*_m.RefundedAt = value.Time
			}
		case usersubscriptionentitlement.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usersubscriptionentitlement.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserSubscriptionEntitlement.
// This includes values selected through modifiers, order, etc.
func (_m *UserSubscriptionEntitlement) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySubscription queries the "subscription" edge of the UserSubscriptionEntitlement entity.
func (_m *UserSubscriptionEntitlement) QuerySubscription() *UserSubscriptionQuery {
	return NewUserSubscriptionEntitlementClient(_m.config).QuerySubscription(_m)
}

// QueryPlan queries the "plan" edge of the UserSubscriptionEntitlement entity.
func (_m *UserSubscriptionEntitlement) QueryPlan() *SubscriptionPlanQuery {
	return NewUserSubscriptionEntitlementClient(_m.config).QueryPlan(_m)
}

// QuerySourceOrder queries the "source_order" edge of the UserSubscriptionEntitlement entity.
func (_m *UserSubscriptionEntitlement) QuerySourceOrder() *PaymentOrderQuery {
	return NewUserSubscriptionEntitlementClient(_m.config).QuerySourceOrder(_m)
}

// QueryOrderLines queries the "order_lines" edge of the UserSubscriptionEntitlement entity.
func (_m *UserSubscriptionEntitlement) QueryOrderLines() *SubscriptionEntitlementOrderQuery {
	return NewUserSubscriptionEntitlementClient(_m.config).QueryOrderLines(_m)
}

// Update returns a builder for updating this UserSubscriptionEntitlement.
// Note that you need to call UserSubscriptionEntitlement.Unwrap() before calling this method if this UserSubscriptionEntitlement
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserSubscriptionEntitlement) Update() *UserSubscriptionEntitlementUpdateOne {
	return NewUserSubscriptionEntitlementClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserSubscriptionEntitlement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserSubscriptionEntitlement) Unwrap() *UserSubscriptionEntitlement {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserSubscriptionEntitlement is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserSubscriptionEntitlement) String() string {
	var builder strings.Builder
	builder.WriteString("UserSubscriptionEntitlement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_subscription_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserSubscriptionID))
	builder.WriteString(", ")
	if v := _m.PlanID; v != nil {
		builder.WriteString("plan_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SourceOrderID; v != nil {
		builder.WriteString("source_order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("lot_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.LotIndex))
	builder.WriteString(", ")
	builder.WriteString("source_type=")
	builder.WriteString(_m.SourceType)
	builder.WriteString(", ")
	builder.WriteString("source_reference=")
	builder.WriteString(_m.SourceReference)
	builder.WriteString(", ")
	builder.WriteString("purchase_mode=")
	builder.WriteString(_m.PurchaseMode)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("starts_at=")
	builder.WriteString(_m.StartsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DailyLimitUsd; v != nil {
		builder.WriteString("daily_limit_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.WeeklyLimitUsd; v != nil {
		builder.WriteString("weekly_limit_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.MonthlyLimitUsd; v != nil {
		builder.WriteString("monthly_limit_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DailyWindowStart; v != nil {
		builder.WriteString("daily_window_start=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.WeeklyWindowStart; v != nil {
		builder.WriteString("weekly_window_start=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.MonthlyWindowStart; v != nil {
		builder.WriteString("monthly_window_start=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("daily_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.DailyUsageUsd))
	builder.WriteString(", ")
	builder.WriteString("weekly_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.WeeklyUsageUsd))
	builder.WriteString(", ")
	builder.WriteString("monthly_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.MonthlyUsageUsd))
	builder.WriteString(", ")
	builder.WriteString("lifetime_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.LifetimeUsageUsd))
	builder.WriteString(", ")
	if v := _m.RefundedAt; v != nil {
		builder.WriteString("refunded_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserSubscriptionEntitlements is a parsable slice of UserSubscriptionEntitlement.
type UserSubscriptionEntitlements []*UserSubscriptionEntitlement
