// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionentitlementorder"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplan"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
	"github.com/Wei-Shaw/sub2api/ent/usersubscriptionentitlement"
)

// UserSubscriptionEntitlementCreate is the builder for creating a UserSubscriptionEntitlement entity.
type UserSubscriptionEntitlementCreate struct {
	config
	mutation *UserSubscriptionEntitlementMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserSubscriptionID sets the "user_subscription_id" field.
func (_c *UserSubscriptionEntitlementCreate) SetUserSubscriptionID(v int64) *UserSubscriptionEntitlementCreate {
	_c.mutation.SetUserSubscriptionID(v)
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *UserSubscriptionEntitlementCreate) SetPlanID(v int64) *UserSubscriptionEntitlementCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_c *UserSubscriptionEntitlementCreate) SetNillablePlanID(v *int64) *UserSubscriptionEntitlementCreate {
	if v != nil {
		_c.SetPlanID(*v)
	}
	return _c
}

// SetSourceOrderID sets the "source_order_id" field.
func (_c *UserSubscriptionEntitlementCreate) SetSourceOrderID(v int64) *UserSubscriptionEntitlementCreate {
	_c.mutation.SetSourceOrderID(v)
	return _c
}

// SetNillableSourceOrderID sets the "source_order_id" field if the given value is not nil.
func (_c *UserSubscriptionEntitlementCreate) SetNillableSourceOrderID(v *int64) *UserSubscriptionEntitlementCreate {
	if v != nil {
		_c.SetSourceOrderID(*v)
	}
	return _c
}

// SetLotIndex sets the "lot_index" field.
func (_c *UserSubscriptionEntitlementCreate) SetLotIndex(v int) *UserSubscriptionEntitlementCreate {
	_c.mutation.SetLotIndex(v)
	return _c
}

// SetNillableLotIndex sets the "lot_index" field if the given value is not nil.
func (_c *UserSubscriptionEntitlementCreate) SetNillableLotIndex(v *int) *UserSubscriptionEntitlementCreate {
	if v != nil {
		_c.SetLotIndex(*v)
	}
	return _c
}

// SetPurchaseMode sets the "purchase_mode" field.
func (_c *UserSubscriptionEntitlementCreate) SetPurchaseMode(v string) *UserSubscriptionEntitlementCreate {
	_c.mutation.SetPurchaseMode(v)
	return _c
}

// SetNillablePurchaseMode sets the "purchase_mode" field if the given value is not nil.
func (_c *UserSubscriptionEntitlementCreate) SetNillablePurchaseMode(v *string) *UserSubscriptionEntitlementCreate {
	if v != nil {
		_c.SetPurchaseMode(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *UserSubscriptionEntitlementCreate) SetStatus(v string) *UserSubscriptionEntitlementCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UserSubscriptionEntitlementCreate) SetNillableStatus(v *string) *UserSubscriptionEntitlementCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetStartsAt sets the "starts_at" field.
func (_c *UserSubscriptionEntitlementCreate) SetStartsAt(v time.Time) *UserSubscriptionEntitlementCreate {
	_c.mutation.SetStartsAt(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UserSubscriptionEntitlementCreate) SetExpiresAt(v time.Time) *UserSubscriptionEntitlementCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_c *UserSubscriptionEntitlementCreate) SetDailyLimitUsd(v float64) *UserSubscriptionEntitlementCreate {
	_c.mutation.SetDailyLimitUsd(v)
	return _c
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_c *UserSubscriptionEntitlementCreate) SetNillableDailyLimitUsd(v *float64) *UserSubscriptionEntitlementCreate {
	if v != nil {
		_c.SetDailyLimitUsd(*v)
	}
	return _c
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (_c *UserSubscriptionEntitlementCreate) SetWeeklyLimitUsd(v float64) *UserSubscriptionEntitlementCreate {
	_c.mutation.SetWeeklyLimitUsd(v)
	return _c
}

// SetNillableWeeklyLimitUsd sets the "weekly_limit_usd" field if the given value is not nil.
func (_c *UserSubscriptionEntitlementCreate) SetNillableWeeklyLimitUsd(v *float64) *UserSubscriptionEntitlementCreate {
	if v != nil {
		_c.SetWeeklyLimitUsd(*v)
	}
	return _c
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (_c *UserSubscriptionEntitlementCreate) SetMonthlyLimitUsd(v float64) *UserSubscriptionEntitlementCreate {
	_c.mutation.SetMonthlyLimitUsd(v)
	return _c
}

// SetNillableMonthlyLimitUsd sets the "monthly_limit_usd" field if the given value is not nil.
func (_c *UserSubscriptionEntitlementCreate) SetNillableMonthlyLimitUsd(v *float64) *UserSubscriptionEntitlementCreate {
	if v != nil {
		_c.SetMonthlyLimitUsd(*v)
	}
	return _c
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (_c *UserSubscriptionEntitlementCreate) SetDailyWindowStart(v time.Time) *UserSubscriptionEntitlementCreate {
	_c.mutation.SetDailyWindowStart(v)
	return _c
}

// SetNillableDailyWindowStart sets the "daily_window_start" field if the given value is not nil.
func (_c *UserSubscriptionEntitlementCreate) SetNillableDailyWindowStart(v *time.Time) *UserSubscriptionEntitlementCreate {
	if v != nil {
		_c.SetDailyWindowStart(*v)
	}
	return _c
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (_c *UserSubscriptionEntitlementCreate) SetWeeklyWindowStart(v time.Time) *UserSubscriptionEntitlementCreate {
	_c.mutation.SetWeeklyWindowStart(v)
	return _c
}

// SetNillableWeeklyWindowStart sets the "weekly_window_start" field if the given value is not nil.
func (_c *UserSubscriptionEntitlementCreate) SetNillableWeeklyWindowStart(v *time.Time) *UserSubscriptionEntitlementCreate {
	if v != nil {
		_c.SetWeeklyWindowStart(*v)
	}
	return _c
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (_c *UserSubscriptionEntitlementCreate) SetMonthlyWindowStart(v time.Time) *UserSubscriptionEntitlementCreate {
	_c.mutation.SetMonthlyWindowStart(v)
	return _c
}

// SetNillableMonthlyWindowStart sets the "monthly_window_start" field if the given value is not nil.
func (_c *UserSubscriptionEntitlementCreate) SetNillableMonthlyWindowStart(v *time.Time) *UserSubscriptionEntitlementCreate {
	if v != nil {
		_c.SetMonthlyWindowStart(*v)
	}
	return _c
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (_c *UserSubscriptionEntitlementCreate) SetDailyUsageUsd(v float64) *UserSubscriptionEntitlementCreate {
	_c.mutation.SetDailyUsageUsd(v)
	return _c
}

// SetNillableDailyUsageUsd sets the "daily_usage_usd" field if the given value is not nil.
func (_c *UserSubscriptionEntitlementCreate) SetNillableDailyUsageUsd(v *float64) *UserSubscriptionEntitlementCreate {
	if v != nil {
		_c.SetDailyUsageUsd(*v)
	}
	return _c
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (_c *UserSubscriptionEntitlementCreate) SetWeeklyUsageUsd(v float64) *UserSubscriptionEntitlementCreate {
	_c.mutation.SetWeeklyUsageUsd(v)
	return _c
}

// SetNillableWeeklyUsageUsd sets the "weekly_usage_usd" field if the given value is not nil.
func (_c *UserSubscriptionEntitlementCreate) SetNillableWeeklyUsageUsd(v *float64) *UserSubscriptionEntitlementCreate {
	if v != nil {
		_c.SetWeeklyUsageUsd(*v)
	}
	return _c
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (_c *UserSubscriptionEntitlementCreate) SetMonthlyUsageUsd(v float64) *UserSubscriptionEntitlementCreate {
	_c.mutation.SetMonthlyUsageUsd(v)
	return _c
}

// SetNillableMonthlyUsageUsd sets the "monthly_usage_usd" field if the given value is not nil.
func (_c *UserSubscriptionEntitlementCreate) SetNillableMonthlyUsageUsd(v *float64) *UserSubscriptionEntitlementCreate {
	if v != nil {
		_c.SetMonthlyUsageUsd(*v)
	}
	return _c
}

// SetLifetimeUsageUsd sets the "lifetime_usage_usd" field.
func (_c *UserSubscriptionEntitlementCreate) SetLifetimeUsageUsd(v float64) *UserSubscriptionEntitlementCreate {
	_c.mutation.SetLifetimeUsageUsd(v)
	return _c
}

// SetNillableLifetimeUsageUsd sets the "lifetime_usage_usd" field if the given value is not nil.
func (_c *UserSubscriptionEntitlementCreate) SetNillableLifetimeUsageUsd(v *float64) *UserSubscriptionEntitlementCreate {
	if v != nil {
		_c.SetLifetimeUsageUsd(*v)
	}
	return _c
}

// SetRefundedAt sets the "refunded_at" field.
func (_c *UserSubscriptionEntitlementCreate) SetRefundedAt(v time.Time) *UserSubscriptionEntitlementCreate {
	_c.mutation.SetRefundedAt(v)
	return _c
}

// SetNillableRefundedAt sets the "refunded_at" field if the given value is not nil.
func (_c *UserSubscriptionEntitlementCreate) SetNillableRefundedAt(v *time.Time) *UserSubscriptionEntitlementCreate {
	if v != nil {
		_c.SetRefundedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserSubscriptionEntitlementCreate) SetCreatedAt(v time.Time) *UserSubscriptionEntitlementCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserSubscriptionEntitlementCreate) SetNillableCreatedAt(v *time.Time) *UserSubscriptionEntitlementCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserSubscriptionEntitlementCreate) SetUpdatedAt(v time.Time) *UserSubscriptionEntitlementCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserSubscriptionEntitlementCreate) SetNillableUpdatedAt(v *time.Time) *UserSubscriptionEntitlementCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSubscriptionID sets the "subscription" edge to the UserSubscription entity by ID.
func (_c *UserSubscriptionEntitlementCreate) SetSubscriptionID(id int64) *UserSubscriptionEntitlementCreate {
	_c.mutation.SetSubscriptionID(id)
	return _c
}

// SetSubscription sets the "subscription" edge to the UserSubscription entity.
func (_c *UserSubscriptionEntitlementCreate) SetSubscription(v *UserSubscription) *UserSubscriptionEntitlementCreate {
	return _c.SetSubscriptionID(v.ID)
}

// SetPlan sets the "plan" edge to the SubscriptionPlan entity.
func (_c *UserSubscriptionEntitlementCreate) SetPlan(v *SubscriptionPlan) *UserSubscriptionEntitlementCreate {
	return _c.SetPlanID(v.ID)
}

// SetSourceOrder sets the "source_order" edge to the PaymentOrder entity.
func (_c *UserSubscriptionEntitlementCreate) SetSourceOrder(v *PaymentOrder) *UserSubscriptionEntitlementCreate {
	return _c.SetSourceOrderID(v.ID)
}

// AddOrderLineIDs adds the "order_lines" edge to the SubscriptionEntitlementOrder entity by IDs.
func (_c *UserSubscriptionEntitlementCreate) AddOrderLineIDs(ids ...int64) *UserSubscriptionEntitlementCreate {
	_c.mutation.AddOrderLineIDs(ids...)
	return _c
}

// AddOrderLines adds the "order_lines" edges to the SubscriptionEntitlementOrder entity.
func (_c *UserSubscriptionEntitlementCreate) AddOrderLines(v ...*SubscriptionEntitlementOrder) *UserSubscriptionEntitlementCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOrderLineIDs(ids...)
}

// Mutation returns the UserSubscriptionEntitlementMutation object of the builder.
func (_c *UserSubscriptionEntitlementCreate) Mutation() *UserSubscriptionEntitlementMutation {
	return _c.mutation
}

// Save creates the UserSubscriptionEntitlement in the database.
func (_c *UserSubscriptionEntitlementCreate) Save(ctx context.Context) (*UserSubscriptionEntitlement, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserSubscriptionEntitlementCreate) SaveX(ctx context.Context) *UserSubscriptionEntitlement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserSubscriptionEntitlementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserSubscriptionEntitlementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserSubscriptionEntitlementCreate) defaults() {
	if _, ok := _c.mutation.LotIndex(); !ok {
		v := usersubscriptionentitlement.DefaultLotIndex
		_c.mutation.SetLotIndex(v)
	}
	if _, ok := _c.mutation.PurchaseMode(); !ok {
		v := usersubscriptionentitlement.DefaultPurchaseMode
		_c.mutation.SetPurchaseMode(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := usersubscriptionentitlement.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.DailyUsageUsd(); !ok {
		v := usersubscriptionentitlement.DefaultDailyUsageUsd
		_c.mutation.SetDailyUsageUsd(v)
	}
	if _, ok := _c.mutation.WeeklyUsageUsd(); !ok {
		v := usersubscriptionentitlement.DefaultWeeklyUsageUsd
		_c.mutation.SetWeeklyUsageUsd(v)
	}
	if _, ok := _c.mutation.MonthlyUsageUsd(); !ok {
		v := usersubscriptionentitlement.DefaultMonthlyUsageUsd
		_c.mutation.SetMonthlyUsageUsd(v)
	}
	if _, ok := _c.mutation.LifetimeUsageUsd(); !ok {
		v := usersubscriptionentitlement.DefaultLifetimeUsageUsd
		_c.mutation.SetLifetimeUsageUsd(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usersubscriptionentitlement.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := usersubscriptionentitlement.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserSubscriptionEntitlementCreate) check() error {
	if _, ok := _c.mutation.UserSubscriptionID(); !ok {
		return &ValidationError{Name: "user_subscription_id", err: errors.New(`ent: missing required field "UserSubscriptionEntitlement.user_subscription_id"`)}
	}
	if _, ok := _c.mutation.LotIndex(); !ok {
		return &ValidationError{Name: "lot_index", err: errors.New(`ent: missing required field "UserSubscriptionEntitlement.lot_index"`)}
	}
	if _, ok := _c.mutation.PurchaseMode(); !ok {
		return &ValidationError{Name: "purchase_mode", err: errors.New(`ent: missing required field "UserSubscriptionEntitlement.purchase_mode"`)}
	}
	if v, ok := _c.mutation.PurchaseMode(); ok {
		if err := usersubscriptionentitlement.PurchaseModeValidator(v); err != nil {
			return &ValidationError{Name: "purchase_mode", err: fmt.Errorf(`ent: validator failed for field "UserSubscriptionEntitlement.purchase_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UserSubscriptionEntitlement.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := usersubscriptionentitlement.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UserSubscriptionEntitlement.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartsAt(); !ok {
		return &ValidationError{Name: "starts_at", err: errors.New(`ent: missing required field "UserSubscriptionEntitlement.starts_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "UserSubscriptionEntitlement.expires_at"`)}
	}
	if _, ok := _c.mutation.DailyUsageUsd(); !ok {
		return &ValidationError{Name: "daily_usage_usd", err: errors.New(`ent: missing required field "UserSubscriptionEntitlement.daily_usage_usd"`)}
	}
	if _, ok := _c.mutation.WeeklyUsageUsd(); !ok {
		return &ValidationError{Name: "weekly_usage_usd", err: errors.New(`ent: missing required field "UserSubscriptionEntitlement.weekly_usage_usd"`)}
	}
	if _, ok := _c.mutation.MonthlyUsageUsd(); !ok {
		return &ValidationError{Name: "monthly_usage_usd", err: errors.New(`ent: missing required field "UserSubscriptionEntitlement.monthly_usage_usd"`)}
	}
	if _, ok := _c.mutation.LifetimeUsageUsd(); !ok {
		return &ValidationError{Name: "lifetime_usage_usd", err: errors.New(`ent: missing required field "UserSubscriptionEntitlement.lifetime_usage_usd"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserSubscriptionEntitlement.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserSubscriptionEntitlement.updated_at"`)}
	}
	if len(_c.mutation.SubscriptionIDs()) == 0 {
		return &ValidationError{Name: "subscription", err: errors.New(`ent: missing required edge "UserSubscriptionEntitlement.subscription"`)}
	}
	return nil
}

func (_c *UserSubscriptionEntitlementCreate) sqlSave(ctx context.Context) (*UserSubscriptionEntitlement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserSubscriptionEntitlementCreate) createSpec() (*UserSubscriptionEntitlement, *sqlgraph.CreateSpec) {
	var (
		_node = &UserSubscriptionEntitlement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usersubscriptionentitlement.Table, sqlgraph.NewFieldSpec(usersubscriptionentitlement.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.LotIndex(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldLotIndex, field.TypeInt, value)
		_node.LotIndex = value
	}
	if value, ok := _c.mutation.PurchaseMode(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldPurchaseMode, field.TypeString, value)
		_node.PurchaseMode = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StartsAt(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldStartsAt, field.TypeTime, value)
		_node.StartsAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.DailyLimitUsd(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldDailyLimitUsd, field.TypeFloat64, value)
		_node.DailyLimitUsd = &value
	}
	if value, ok := _c.mutation.WeeklyLimitUsd(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldWeeklyLimitUsd, field.TypeFloat64, value)
		_node.WeeklyLimitUsd = &value
	}
	if value, ok := _c.mutation.MonthlyLimitUsd(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldMonthlyLimitUsd, field.TypeFloat64, value)
		_node.MonthlyLimitUsd = &value
	}
	if value, ok := _c.mutation.DailyWindowStart(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldDailyWindowStart, field.TypeTime, value)
		_node.DailyWindowStart = &value
	}
	if value, ok := _c.mutation.WeeklyWindowStart(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldWeeklyWindowStart, field.TypeTime, value)
		_node.WeeklyWindowStart = &value
	}
	if value, ok := _c.mutation.MonthlyWindowStart(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldMonthlyWindowStart, field.TypeTime, value)
		_node.MonthlyWindowStart = &value
	}
	if value, ok := _c.mutation.DailyUsageUsd(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldDailyUsageUsd, field.TypeFloat64, value)
		_node.DailyUsageUsd = value
	}
	if value, ok := _c.mutation.WeeklyUsageUsd(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldWeeklyUsageUsd, field.TypeFloat64, value)
		_node.WeeklyUsageUsd = value
	}
	if value, ok := _c.mutation.MonthlyUsageUsd(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldMonthlyUsageUsd, field.TypeFloat64, value)
		_node.MonthlyUsageUsd = value
	}
	if value, ok := _c.mutation.LifetimeUsageUsd(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldLifetimeUsageUsd, field.TypeFloat64, value)
		_node.LifetimeUsageUsd = value
	}
	if value, ok := _c.mutation.RefundedAt(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldRefundedAt, field.TypeTime, value)
		_node.RefundedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usersubscriptionentitlement.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptionentitlement.SubscriptionTable,
			Columns: []string{usersubscriptionentitlement.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserSubscriptionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptionentitlement.PlanTable,
			Columns: []string{usersubscriptionentitlement.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlanID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SourceOrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   usersubscriptionentitlement.SourceOrderTable,
			Columns: []string{usersubscriptionentitlement.SourceOrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SourceOrderID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrderLinesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   usersubscriptionentitlement.OrderLinesTable,
			Columns: []string{usersubscriptionentitlement.OrderLinesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionentitlementorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserSubscriptionEntitlement.Create().
//		SetUserSubscriptionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserSubscriptionEntitlementUpsert) {
//			SetUserSubscriptionID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserSubscriptionEntitlementCreate) OnConflict(opts ...sql.ConflictOption) *UserSubscriptionEntitlementUpsertOne {
	_c.conflict = opts
	return &UserSubscriptionEntitlementUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserSubscriptionEntitlement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserSubscriptionEntitlementCreate) OnConflictColumns(columns ...string) *UserSubscriptionEntitlementUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserSubscriptionEntitlementUpsertOne{
		create: _c,
	}
}

type (
	// UserSubscriptionEntitlementUpsertOne is the builder for "upsert"-ing
	//  one UserSubscriptionEntitlement node.
	UserSubscriptionEntitlementUpsertOne struct {
		create *UserSubscriptionEntitlementCreate
	}

	// UserSubscriptionEntitlementUpsert is the "OnConflict" setter.
	UserSubscriptionEntitlementUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserSubscriptionID sets the "user_subscription_id" field.
func (u *UserSubscriptionEntitlementUpsert) SetUserSubscriptionID(v int64) *UserSubscriptionEntitlementUpsert {
	u.Set(usersubscriptionentitlement.FieldUserSubscriptionID, v)
	return u
}

// UpdateUserSubscriptionID sets the "user_subscription_id" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsert) UpdateUserSubscriptionID() *UserSubscriptionEntitlementUpsert {
	u.SetExcluded(usersubscriptionentitlement.FieldUserSubscriptionID)
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *UserSubscriptionEntitlementUpsert) SetPlanID(v int64) *UserSubscriptionEntitlementUpsert {
	u.Set(usersubscriptionentitlement.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsert) UpdatePlanID() *UserSubscriptionEntitlementUpsert {
	u.SetExcluded(usersubscriptionentitlement.FieldPlanID)
	return u
}

// ClearPlanID clears the value of the "plan_id" field.
func (u *UserSubscriptionEntitlementUpsert) ClearPlanID() *UserSubscriptionEntitlementUpsert {
	u.SetNull(usersubscriptionentitlement.FieldPlanID)
	return u
}

// SetSourceOrderID sets the "source_order_id" field.
func (u *UserSubscriptionEntitlementUpsert) SetSourceOrderID(v int64) *UserSubscriptionEntitlementUpsert {
	u.Set(usersubscriptionentitlement.FieldSourceOrderID, v)
	return u
}

// UpdateSourceOrderID sets the "source_order_id" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsert) UpdateSourceOrderID() *UserSubscriptionEntitlementUpsert {
	u.SetExcluded(usersubscriptionentitlement.FieldSourceOrderID)
	return u
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (u *UserSubscriptionEntitlementUpsert) ClearSourceOrderID() *UserSubscriptionEntitlementUpsert {
	u.SetNull(usersubscriptionentitlement.FieldSourceOrderID)
	return u
}

// SetLotIndex sets the "lot_index" field.
func (u *UserSubscriptionEntitlementUpsert) SetLotIndex(v int) *UserSubscriptionEntitlementUpsert {
	u.Set(usersubscriptionentitlement.FieldLotIndex, v)
	return u
}

// UpdateLotIndex sets the "lot_index" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsert) UpdateLotIndex() *UserSubscriptionEntitlementUpsert {
	u.SetExcluded(usersubscriptionentitlement.FieldLotIndex)
	return u
}

// AddLotIndex adds v to the "lot_index" field.
func (u *UserSubscriptionEntitlementUpsert) AddLotIndex(v int) *UserSubscriptionEntitlementUpsert {
	u.Add(usersubscriptionentitlement.FieldLotIndex, v)
	return u
}

// SetPurchaseMode sets the "purchase_mode" field.
func (u *UserSubscriptionEntitlementUpsert) SetPurchaseMode(v string) *UserSubscriptionEntitlementUpsert {
	u.Set(usersubscriptionentitlement.FieldPurchaseMode, v)
	return u
}

// UpdatePurchaseMode sets the "purchase_mode" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsert) UpdatePurchaseMode() *UserSubscriptionEntitlementUpsert {
	u.SetExcluded(usersubscriptionentitlement.FieldPurchaseMode)
	return u
}

// SetStatus sets the "status" field.
func (u *UserSubscriptionEntitlementUpsert) SetStatus(v string) *UserSubscriptionEntitlementUpsert {
	u.Set(usersubscriptionentitlement.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsert) UpdateStatus() *UserSubscriptionEntitlementUpsert {
	u.SetExcluded(usersubscriptionentitlement.FieldStatus)
	return u
}

// SetStartsAt sets the "starts_at" field.
func (u *UserSubscriptionEntitlementUpsert) SetStartsAt(v time.Time) *UserSubscriptionEntitlementUpsert {
	u.Set(usersubscriptionentitlement.FieldStartsAt, v)
	return u
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsert) UpdateStartsAt() *UserSubscriptionEntitlementUpsert {
	u.SetExcluded(usersubscriptionentitlement.FieldStartsAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserSubscriptionEntitlementUpsert) SetExpiresAt(v time.Time) *UserSubscriptionEntitlementUpsert {
	u.Set(usersubscriptionentitlement.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsert) UpdateExpiresAt() *UserSubscriptionEntitlementUpsert {
	u.SetExcluded(usersubscriptionentitlement.FieldExpiresAt)
	return u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsert) SetDailyLimitUsd(v float64) *UserSubscriptionEntitlementUpsert {
	u.Set(usersubscriptionentitlement.FieldDailyLimitUsd, v)
	return u
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsert) UpdateDailyLimitUsd() *UserSubscriptionEntitlementUpsert {
	u.SetExcluded(usersubscriptionentitlement.FieldDailyLimitUsd)
	return u
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsert) AddDailyLimitUsd(v float64) *UserSubscriptionEntitlementUpsert {
	u.Add(usersubscriptionentitlement.FieldDailyLimitUsd, v)
	return u
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsert) ClearDailyLimitUsd() *UserSubscriptionEntitlementUpsert {
	u.SetNull(usersubscriptionentitlement.FieldDailyLimitUsd)
	return u
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsert) SetWeeklyLimitUsd(v float64) *UserSubscriptionEntitlementUpsert {
	u.Set(usersubscriptionentitlement.FieldWeeklyLimitUsd, v)
	return u
}

// UpdateWeeklyLimitUsd sets the "weekly_limit_usd" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsert) UpdateWeeklyLimitUsd() *UserSubscriptionEntitlementUpsert {
	u.SetExcluded(usersubscriptionentitlement.FieldWeeklyLimitUsd)
	return u
}

// AddWeeklyLimitUsd adds v to the "weekly_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsert) AddWeeklyLimitUsd(v float64) *UserSubscriptionEntitlementUpsert {
	u.Add(usersubscriptionentitlement.FieldWeeklyLimitUsd, v)
	return u
}

// ClearWeeklyLimitUsd clears the value of the "weekly_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsert) ClearWeeklyLimitUsd() *UserSubscriptionEntitlementUpsert {
	u.SetNull(usersubscriptionentitlement.FieldWeeklyLimitUsd)
	return u
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsert) SetMonthlyLimitUsd(v float64) *UserSubscriptionEntitlementUpsert {
	u.Set(usersubscriptionentitlement.FieldMonthlyLimitUsd, v)
	return u
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsert) UpdateMonthlyLimitUsd() *UserSubscriptionEntitlementUpsert {
	u.SetExcluded(usersubscriptionentitlement.FieldMonthlyLimitUsd)
	return u
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsert) AddMonthlyLimitUsd(v float64) *UserSubscriptionEntitlementUpsert {
	u.Add(usersubscriptionentitlement.FieldMonthlyLimitUsd, v)
	return u
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsert) ClearMonthlyLimitUsd() *UserSubscriptionEntitlementUpsert {
	u.SetNull(usersubscriptionentitlement.FieldMonthlyLimitUsd)
	return u
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *UserSubscriptionEntitlementUpsert) SetDailyWindowStart(v time.Time) *UserSubscriptionEntitlementUpsert {
	u.Set(usersubscriptionentitlement.FieldDailyWindowStart, v)
	return u
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsert) UpdateDailyWindowStart() *UserSubscriptionEntitlementUpsert {
	u.SetExcluded(usersubscriptionentitlement.FieldDailyWindowStart)
	return u
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *UserSubscriptionEntitlementUpsert) ClearDailyWindowStart() *UserSubscriptionEntitlementUpsert {
	u.SetNull(usersubscriptionentitlement.FieldDailyWindowStart)
	return u
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *UserSubscriptionEntitlementUpsert) SetWeeklyWindowStart(v time.Time) *UserSubscriptionEntitlementUpsert {
	u.Set(usersubscriptionentitlement.FieldWeeklyWindowStart, v)
	return u
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsert) UpdateWeeklyWindowStart() *UserSubscriptionEntitlementUpsert {
	u.SetExcluded(usersubscriptionentitlement.FieldWeeklyWindowStart)
	return u
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *UserSubscriptionEntitlementUpsert) ClearWeeklyWindowStart() *UserSubscriptionEntitlementUpsert {
	u.SetNull(usersubscriptionentitlement.FieldWeeklyWindowStart)
	return u
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *UserSubscriptionEntitlementUpsert) SetMonthlyWindowStart(v time.Time) *UserSubscriptionEntitlementUpsert {
	u.Set(usersubscriptionentitlement.FieldMonthlyWindowStart, v)
	return u
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsert) UpdateMonthlyWindowStart() *UserSubscriptionEntitlementUpsert {
	u.SetExcluded(usersubscriptionentitlement.FieldMonthlyWindowStart)
	return u
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *UserSubscriptionEntitlementUpsert) ClearMonthlyWindowStart() *UserSubscriptionEntitlementUpsert {
	u.SetNull(usersubscriptionentitlement.FieldMonthlyWindowStart)
	return u
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsert) SetDailyUsageUsd(v float64) *UserSubscriptionEntitlementUpsert {
	u.Set(usersubscriptionentitlement.FieldDailyUsageUsd, v)
	return u
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsert) UpdateDailyUsageUsd() *UserSubscriptionEntitlementUpsert {
	u.SetExcluded(usersubscriptionentitlement.FieldDailyUsageUsd)
	return u
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsert) AddDailyUsageUsd(v float64) *UserSubscriptionEntitlementUpsert {
	u.Add(usersubscriptionentitlement.FieldDailyUsageUsd, v)
	return u
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsert) SetWeeklyUsageUsd(v float64) *UserSubscriptionEntitlementUpsert {
	u.Set(usersubscriptionentitlement.FieldWeeklyUsageUsd, v)
	return u
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsert) UpdateWeeklyUsageUsd() *UserSubscriptionEntitlementUpsert {
	u.SetExcluded(usersubscriptionentitlement.FieldWeeklyUsageUsd)
	return u
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsert) AddWeeklyUsageUsd(v float64) *UserSubscriptionEntitlementUpsert {
	u.Add(usersubscriptionentitlement.FieldWeeklyUsageUsd, v)
	return u
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsert) SetMonthlyUsageUsd(v float64) *UserSubscriptionEntitlementUpsert {
	u.Set(usersubscriptionentitlement.FieldMonthlyUsageUsd, v)
	return u
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsert) UpdateMonthlyUsageUsd() *UserSubscriptionEntitlementUpsert {
	u.SetExcluded(usersubscriptionentitlement.FieldMonthlyUsageUsd)
	return u
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsert) AddMonthlyUsageUsd(v float64) *UserSubscriptionEntitlementUpsert {
	u.Add(usersubscriptionentitlement.FieldMonthlyUsageUsd, v)
	return u
}

// SetLifetimeUsageUsd sets the "lifetime_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsert) SetLifetimeUsageUsd(v float64) *UserSubscriptionEntitlementUpsert {
	u.Set(usersubscriptionentitlement.FieldLifetimeUsageUsd, v)
	return u
}

// UpdateLifetimeUsageUsd sets the "lifetime_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsert) UpdateLifetimeUsageUsd() *UserSubscriptionEntitlementUpsert {
	u.SetExcluded(usersubscriptionentitlement.FieldLifetimeUsageUsd)
	return u
}

// AddLifetimeUsageUsd adds v to the "lifetime_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsert) AddLifetimeUsageUsd(v float64) *UserSubscriptionEntitlementUpsert {
	u.Add(usersubscriptionentitlement.FieldLifetimeUsageUsd, v)
	return u
}

// SetRefundedAt sets the "refunded_at" field.
func (u *UserSubscriptionEntitlementUpsert) SetRefundedAt(v time.Time) *UserSubscriptionEntitlementUpsert {
	u.Set(usersubscriptionentitlement.FieldRefundedAt, v)
	return u
}

// UpdateRefundedAt sets the "refunded_at" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsert) UpdateRefundedAt() *UserSubscriptionEntitlementUpsert {
	u.SetExcluded(usersubscriptionentitlement.FieldRefundedAt)
	return u
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (u *UserSubscriptionEntitlementUpsert) ClearRefundedAt() *UserSubscriptionEntitlementUpsert {
	u.SetNull(usersubscriptionentitlement.FieldRefundedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserSubscriptionEntitlementUpsert) SetUpdatedAt(v time.Time) *UserSubscriptionEntitlementUpsert {
	u.Set(usersubscriptionentitlement.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsert) UpdateUpdatedAt() *UserSubscriptionEntitlementUpsert {
	u.SetExcluded(usersubscriptionentitlement.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserSubscriptionEntitlement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserSubscriptionEntitlementUpsertOne) UpdateNewValues() *UserSubscriptionEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usersubscriptionentitlement.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserSubscriptionEntitlement.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserSubscriptionEntitlementUpsertOne) Ignore() *UserSubscriptionEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserSubscriptionEntitlementUpsertOne) DoNothing() *UserSubscriptionEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserSubscriptionEntitlementCreate.OnConflict
// documentation for more info.
func (u *UserSubscriptionEntitlementUpsertOne) Update(set func(*UserSubscriptionEntitlementUpsert)) *UserSubscriptionEntitlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserSubscriptionEntitlementUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserSubscriptionID sets the "user_subscription_id" field.
func (u *UserSubscriptionEntitlementUpsertOne) SetUserSubscriptionID(v int64) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetUserSubscriptionID(v)
	})
}

// UpdateUserSubscriptionID sets the "user_subscription_id" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertOne) UpdateUserSubscriptionID() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateUserSubscriptionID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *UserSubscriptionEntitlementUpsertOne) SetPlanID(v int64) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertOne) UpdatePlanID() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdatePlanID()
	})
}

// ClearPlanID clears the value of the "plan_id" field.
func (u *UserSubscriptionEntitlementUpsertOne) ClearPlanID() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.ClearPlanID()
	})
}

// SetSourceOrderID sets the "source_order_id" field.
func (u *UserSubscriptionEntitlementUpsertOne) SetSourceOrderID(v int64) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetSourceOrderID(v)
	})
}

// UpdateSourceOrderID sets the "source_order_id" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertOne) UpdateSourceOrderID() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateSourceOrderID()
	})
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (u *UserSubscriptionEntitlementUpsertOne) ClearSourceOrderID() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.ClearSourceOrderID()
	})
}

// SetLotIndex sets the "lot_index" field.
func (u *UserSubscriptionEntitlementUpsertOne) SetLotIndex(v int) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetLotIndex(v)
	})
}

// AddLotIndex adds v to the "lot_index" field.
func (u *UserSubscriptionEntitlementUpsertOne) AddLotIndex(v int) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.AddLotIndex(v)
	})
}

// UpdateLotIndex sets the "lot_index" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertOne) UpdateLotIndex() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateLotIndex()
	})
}

// SetPurchaseMode sets the "purchase_mode" field.
func (u *UserSubscriptionEntitlementUpsertOne) SetPurchaseMode(v string) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetPurchaseMode(v)
	})
}

// UpdatePurchaseMode sets the "purchase_mode" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertOne) UpdatePurchaseMode() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdatePurchaseMode()
	})
}

// SetStatus sets the "status" field.
func (u *UserSubscriptionEntitlementUpsertOne) SetStatus(v string) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertOne) UpdateStatus() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateStatus()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *UserSubscriptionEntitlementUpsertOne) SetStartsAt(v time.Time) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertOne) UpdateStartsAt() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserSubscriptionEntitlementUpsertOne) SetExpiresAt(v time.Time) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertOne) UpdateExpiresAt() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsertOne) SetDailyLimitUsd(v float64) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetDailyLimitUsd(v)
	})
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsertOne) AddDailyLimitUsd(v float64) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.AddDailyLimitUsd(v)
	})
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertOne) UpdateDailyLimitUsd() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateDailyLimitUsd()
	})
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsertOne) ClearDailyLimitUsd() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.ClearDailyLimitUsd()
	})
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsertOne) SetWeeklyLimitUsd(v float64) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetWeeklyLimitUsd(v)
	})
}

// AddWeeklyLimitUsd adds v to the "weekly_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsertOne) AddWeeklyLimitUsd(v float64) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.AddWeeklyLimitUsd(v)
	})
}

// UpdateWeeklyLimitUsd sets the "weekly_limit_usd" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertOne) UpdateWeeklyLimitUsd() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateWeeklyLimitUsd()
	})
}

// ClearWeeklyLimitUsd clears the value of the "weekly_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsertOne) ClearWeeklyLimitUsd() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.ClearWeeklyLimitUsd()
	})
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsertOne) SetMonthlyLimitUsd(v float64) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetMonthlyLimitUsd(v)
	})
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsertOne) AddMonthlyLimitUsd(v float64) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.AddMonthlyLimitUsd(v)
	})
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertOne) UpdateMonthlyLimitUsd() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateMonthlyLimitUsd()
	})
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsertOne) ClearMonthlyLimitUsd() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.ClearMonthlyLimitUsd()
	})
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *UserSubscriptionEntitlementUpsertOne) SetDailyWindowStart(v time.Time) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetDailyWindowStart(v)
	})
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertOne) UpdateDailyWindowStart() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateDailyWindowStart()
	})
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *UserSubscriptionEntitlementUpsertOne) ClearDailyWindowStart() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.ClearDailyWindowStart()
	})
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *UserSubscriptionEntitlementUpsertOne) SetWeeklyWindowStart(v time.Time) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetWeeklyWindowStart(v)
	})
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertOne) UpdateWeeklyWindowStart() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateWeeklyWindowStart()
	})
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *UserSubscriptionEntitlementUpsertOne) ClearWeeklyWindowStart() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.ClearWeeklyWindowStart()
	})
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *UserSubscriptionEntitlementUpsertOne) SetMonthlyWindowStart(v time.Time) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetMonthlyWindowStart(v)
	})
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertOne) UpdateMonthlyWindowStart() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateMonthlyWindowStart()
	})
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *UserSubscriptionEntitlementUpsertOne) ClearMonthlyWindowStart() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.ClearMonthlyWindowStart()
	})
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsertOne) SetDailyUsageUsd(v float64) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetDailyUsageUsd(v)
	})
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsertOne) AddDailyUsageUsd(v float64) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.AddDailyUsageUsd(v)
	})
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertOne) UpdateDailyUsageUsd() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateDailyUsageUsd()
	})
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsertOne) SetWeeklyUsageUsd(v float64) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetWeeklyUsageUsd(v)
	})
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsertOne) AddWeeklyUsageUsd(v float64) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.AddWeeklyUsageUsd(v)
	})
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertOne) UpdateWeeklyUsageUsd() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateWeeklyUsageUsd()
	})
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsertOne) SetMonthlyUsageUsd(v float64) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetMonthlyUsageUsd(v)
	})
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsertOne) AddMonthlyUsageUsd(v float64) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.AddMonthlyUsageUsd(v)
	})
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertOne) UpdateMonthlyUsageUsd() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateMonthlyUsageUsd()
	})
}

// SetLifetimeUsageUsd sets the "lifetime_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsertOne) SetLifetimeUsageUsd(v float64) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetLifetimeUsageUsd(v)
	})
}

// AddLifetimeUsageUsd adds v to the "lifetime_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsertOne) AddLifetimeUsageUsd(v float64) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.AddLifetimeUsageUsd(v)
	})
}

// UpdateLifetimeUsageUsd sets the "lifetime_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertOne) UpdateLifetimeUsageUsd() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateLifetimeUsageUsd()
	})
}

// SetRefundedAt sets the "refunded_at" field.
func (u *UserSubscriptionEntitlementUpsertOne) SetRefundedAt(v time.Time) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetRefundedAt(v)
	})
}

// UpdateRefundedAt sets the "refunded_at" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertOne) UpdateRefundedAt() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateRefundedAt()
	})
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (u *UserSubscriptionEntitlementUpsertOne) ClearRefundedAt() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.ClearRefundedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserSubscriptionEntitlementUpsertOne) SetUpdatedAt(v time.Time) *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertOne) UpdateUpdatedAt() *UserSubscriptionEntitlementUpsertOne {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserSubscriptionEntitlementUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserSubscriptionEntitlementCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserSubscriptionEntitlementUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserSubscriptionEntitlementUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserSubscriptionEntitlementUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserSubscriptionEntitlementCreateBulk is the builder for creating many UserSubscriptionEntitlement entities in bulk.
type UserSubscriptionEntitlementCreateBulk struct {
	config
	err      error
	builders []*UserSubscriptionEntitlementCreate
	conflict []sql.ConflictOption
}

// Save creates the UserSubscriptionEntitlement entities in the database.
func (_c *UserSubscriptionEntitlementCreateBulk) Save(ctx context.Context) ([]*UserSubscriptionEntitlement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserSubscriptionEntitlement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserSubscriptionEntitlementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserSubscriptionEntitlementCreateBulk) SaveX(ctx context.Context) []*UserSubscriptionEntitlement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserSubscriptionEntitlementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserSubscriptionEntitlementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserSubscriptionEntitlement.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserSubscriptionEntitlementUpsert) {
//			SetUserSubscriptionID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserSubscriptionEntitlementCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserSubscriptionEntitlementUpsertBulk {
	_c.conflict = opts
	return &UserSubscriptionEntitlementUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserSubscriptionEntitlement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserSubscriptionEntitlementCreateBulk) OnConflictColumns(columns ...string) *UserSubscriptionEntitlementUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserSubscriptionEntitlementUpsertBulk{
		create: _c,
	}
}

// UserSubscriptionEntitlementUpsertBulk is the builder for "upsert"-ing
// a bulk of UserSubscriptionEntitlement nodes.
type UserSubscriptionEntitlementUpsertBulk struct {
	create *UserSubscriptionEntitlementCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserSubscriptionEntitlement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserSubscriptionEntitlementUpsertBulk) UpdateNewValues() *UserSubscriptionEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usersubscriptionentitlement.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserSubscriptionEntitlement.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserSubscriptionEntitlementUpsertBulk) Ignore() *UserSubscriptionEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserSubscriptionEntitlementUpsertBulk) DoNothing() *UserSubscriptionEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserSubscriptionEntitlementCreateBulk.OnConflict
// documentation for more info.
func (u *UserSubscriptionEntitlementUpsertBulk) Update(set func(*UserSubscriptionEntitlementUpsert)) *UserSubscriptionEntitlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserSubscriptionEntitlementUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserSubscriptionID sets the "user_subscription_id" field.
func (u *UserSubscriptionEntitlementUpsertBulk) SetUserSubscriptionID(v int64) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetUserSubscriptionID(v)
	})
}

// UpdateUserSubscriptionID sets the "user_subscription_id" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertBulk) UpdateUserSubscriptionID() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateUserSubscriptionID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *UserSubscriptionEntitlementUpsertBulk) SetPlanID(v int64) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertBulk) UpdatePlanID() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdatePlanID()
	})
}

// ClearPlanID clears the value of the "plan_id" field.
func (u *UserSubscriptionEntitlementUpsertBulk) ClearPlanID() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.ClearPlanID()
	})
}

// SetSourceOrderID sets the "source_order_id" field.
func (u *UserSubscriptionEntitlementUpsertBulk) SetSourceOrderID(v int64) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetSourceOrderID(v)
	})
}

// UpdateSourceOrderID sets the "source_order_id" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertBulk) UpdateSourceOrderID() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateSourceOrderID()
	})
}

// ClearSourceOrderID clears the value of the "source_order_id" field.
func (u *UserSubscriptionEntitlementUpsertBulk) ClearSourceOrderID() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.ClearSourceOrderID()
	})
}

// SetLotIndex sets the "lot_index" field.
func (u *UserSubscriptionEntitlementUpsertBulk) SetLotIndex(v int) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetLotIndex(v)
	})
}

// AddLotIndex adds v to the "lot_index" field.
func (u *UserSubscriptionEntitlementUpsertBulk) AddLotIndex(v int) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.AddLotIndex(v)
	})
}

// UpdateLotIndex sets the "lot_index" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertBulk) UpdateLotIndex() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateLotIndex()
	})
}

// SetPurchaseMode sets the "purchase_mode" field.
func (u *UserSubscriptionEntitlementUpsertBulk) SetPurchaseMode(v string) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetPurchaseMode(v)
	})
}

// UpdatePurchaseMode sets the "purchase_mode" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertBulk) UpdatePurchaseMode() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdatePurchaseMode()
	})
}

// SetStatus sets the "status" field.
func (u *UserSubscriptionEntitlementUpsertBulk) SetStatus(v string) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertBulk) UpdateStatus() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateStatus()
	})
}

// SetStartsAt sets the "starts_at" field.
func (u *UserSubscriptionEntitlementUpsertBulk) SetStartsAt(v time.Time) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetStartsAt(v)
	})
}

// UpdateStartsAt sets the "starts_at" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertBulk) UpdateStartsAt() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateStartsAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserSubscriptionEntitlementUpsertBulk) SetExpiresAt(v time.Time) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertBulk) UpdateExpiresAt() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsertBulk) SetDailyLimitUsd(v float64) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetDailyLimitUsd(v)
	})
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsertBulk) AddDailyLimitUsd(v float64) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.AddDailyLimitUsd(v)
	})
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertBulk) UpdateDailyLimitUsd() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateDailyLimitUsd()
	})
}

// ClearDailyLimitUsd clears the value of the "daily_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsertBulk) ClearDailyLimitUsd() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.ClearDailyLimitUsd()
	})
}

// SetWeeklyLimitUsd sets the "weekly_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsertBulk) SetWeeklyLimitUsd(v float64) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetWeeklyLimitUsd(v)
	})
}

// AddWeeklyLimitUsd adds v to the "weekly_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsertBulk) AddWeeklyLimitUsd(v float64) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.AddWeeklyLimitUsd(v)
	})
}

// UpdateWeeklyLimitUsd sets the "weekly_limit_usd" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertBulk) UpdateWeeklyLimitUsd() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateWeeklyLimitUsd()
	})
}

// ClearWeeklyLimitUsd clears the value of the "weekly_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsertBulk) ClearWeeklyLimitUsd() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.ClearWeeklyLimitUsd()
	})
}

// SetMonthlyLimitUsd sets the "monthly_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsertBulk) SetMonthlyLimitUsd(v float64) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetMonthlyLimitUsd(v)
	})
}

// AddMonthlyLimitUsd adds v to the "monthly_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsertBulk) AddMonthlyLimitUsd(v float64) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.AddMonthlyLimitUsd(v)
	})
}

// UpdateMonthlyLimitUsd sets the "monthly_limit_usd" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertBulk) UpdateMonthlyLimitUsd() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateMonthlyLimitUsd()
	})
}

// ClearMonthlyLimitUsd clears the value of the "monthly_limit_usd" field.
func (u *UserSubscriptionEntitlementUpsertBulk) ClearMonthlyLimitUsd() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.ClearMonthlyLimitUsd()
	})
}

// SetDailyWindowStart sets the "daily_window_start" field.
func (u *UserSubscriptionEntitlementUpsertBulk) SetDailyWindowStart(v time.Time) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetDailyWindowStart(v)
	})
}

// UpdateDailyWindowStart sets the "daily_window_start" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertBulk) UpdateDailyWindowStart() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateDailyWindowStart()
	})
}

// ClearDailyWindowStart clears the value of the "daily_window_start" field.
func (u *UserSubscriptionEntitlementUpsertBulk) ClearDailyWindowStart() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.ClearDailyWindowStart()
	})
}

// SetWeeklyWindowStart sets the "weekly_window_start" field.
func (u *UserSubscriptionEntitlementUpsertBulk) SetWeeklyWindowStart(v time.Time) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetWeeklyWindowStart(v)
	})
}

// UpdateWeeklyWindowStart sets the "weekly_window_start" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertBulk) UpdateWeeklyWindowStart() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateWeeklyWindowStart()
	})
}

// ClearWeeklyWindowStart clears the value of the "weekly_window_start" field.
func (u *UserSubscriptionEntitlementUpsertBulk) ClearWeeklyWindowStart() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.ClearWeeklyWindowStart()
	})
}

// SetMonthlyWindowStart sets the "monthly_window_start" field.
func (u *UserSubscriptionEntitlementUpsertBulk) SetMonthlyWindowStart(v time.Time) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetMonthlyWindowStart(v)
	})
}

// UpdateMonthlyWindowStart sets the "monthly_window_start" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertBulk) UpdateMonthlyWindowStart() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateMonthlyWindowStart()
	})
}

// ClearMonthlyWindowStart clears the value of the "monthly_window_start" field.
func (u *UserSubscriptionEntitlementUpsertBulk) ClearMonthlyWindowStart() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.ClearMonthlyWindowStart()
	})
}

// SetDailyUsageUsd sets the "daily_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsertBulk) SetDailyUsageUsd(v float64) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetDailyUsageUsd(v)
	})
}

// AddDailyUsageUsd adds v to the "daily_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsertBulk) AddDailyUsageUsd(v float64) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.AddDailyUsageUsd(v)
	})
}

// UpdateDailyUsageUsd sets the "daily_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertBulk) UpdateDailyUsageUsd() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateDailyUsageUsd()
	})
}

// SetWeeklyUsageUsd sets the "weekly_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsertBulk) SetWeeklyUsageUsd(v float64) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetWeeklyUsageUsd(v)
	})
}

// AddWeeklyUsageUsd adds v to the "weekly_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsertBulk) AddWeeklyUsageUsd(v float64) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.AddWeeklyUsageUsd(v)
	})
}

// UpdateWeeklyUsageUsd sets the "weekly_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertBulk) UpdateWeeklyUsageUsd() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateWeeklyUsageUsd()
	})
}

// SetMonthlyUsageUsd sets the "monthly_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsertBulk) SetMonthlyUsageUsd(v float64) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetMonthlyUsageUsd(v)
	})
}

// AddMonthlyUsageUsd adds v to the "monthly_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsertBulk) AddMonthlyUsageUsd(v float64) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.AddMonthlyUsageUsd(v)
	})
}

// UpdateMonthlyUsageUsd sets the "monthly_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertBulk) UpdateMonthlyUsageUsd() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateMonthlyUsageUsd()
	})
}

// SetLifetimeUsageUsd sets the "lifetime_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsertBulk) SetLifetimeUsageUsd(v float64) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetLifetimeUsageUsd(v)
	})
}

// AddLifetimeUsageUsd adds v to the "lifetime_usage_usd" field.
func (u *UserSubscriptionEntitlementUpsertBulk) AddLifetimeUsageUsd(v float64) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.AddLifetimeUsageUsd(v)
	})
}

// UpdateLifetimeUsageUsd sets the "lifetime_usage_usd" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertBulk) UpdateLifetimeUsageUsd() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateLifetimeUsageUsd()
	})
}

// SetRefundedAt sets the "refunded_at" field.
func (u *UserSubscriptionEntitlementUpsertBulk) SetRefundedAt(v time.Time) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetRefundedAt(v)
	})
}

// UpdateRefundedAt sets the "refunded_at" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertBulk) UpdateRefundedAt() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateRefundedAt()
	})
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (u *UserSubscriptionEntitlementUpsertBulk) ClearRefundedAt() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.ClearRefundedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserSubscriptionEntitlementUpsertBulk) SetUpdatedAt(v time.Time) *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserSubscriptionEntitlementUpsertBulk) UpdateUpdatedAt() *UserSubscriptionEntitlementUpsertBulk {
	return u.Update(func(s *UserSubscriptionEntitlementUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserSubscriptionEntitlementUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserSubscriptionEntitlementCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserSubscriptionEntitlementCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserSubscriptionEntitlementUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
