#!/usr/bin/env python3
"""Full HTTP acceptance for Subscription V2 using disposable, local-only fixtures.

Start the local acceptance PostgreSQL/Redis and a server built from this checkout:
  GEILI_DECOUPLED_DB=acceptance_v2 GEILI_DECOUPLED_BASE=http://127.0.0.1:18494 \
    python3 .github/geili/decoupled-acceptance.py serve
Then run (no decoupled bootstrap required):
  python3 .github/geili/subscription-v2-acceptance.py \
    --base http://127.0.0.1:18494 --database acceptance_v2

Uses the admin password already generated by acceptance.py. It never reads
production credentials. Every user, plan, group and payment is synthetic. SQL is
restricted to a container labelled geili.acceptance=local and an acceptance_*
database. Local fixture expiry/usage adjustments stand in for waiting days.
Results stay in ignored deploy/.secrets/subscription-v2-acceptance/.
"""
import argparse
import hashlib
import http.server
import importlib.util
import ipaddress
import json
import os
from pathlib import Path
import secrets
import subprocess
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timedelta, timezone
from decimal import Decimal, ROUND_HALF_UP

ROOT = Path(__file__).resolve().parents[2]
SPEC = importlib.util.spec_from_file_location("base_acceptance", Path(__file__).with_name("acceptance.py"))
BASE_HARNESS = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(BASE_HARNESS)
BEIJING = timezone(timedelta(hours=8))
MODEL = "gpt-4.1-mini"
TIERS = {"week90": (7, 90, "12.34"), "week180": (7, 180, "23.45"),
         "month45": (30, 45, "10.01"), "month90": (30, 90, "20.02"),
         "month180": (30, 180, "40.05")}


def local_base(value):
    parsed = urllib.parse.urlsplit(value)
    if parsed.scheme != "http" or parsed.username or parsed.password or parsed.query or parsed.fragment or parsed.path not in ("", "/") or not parsed.port:
        raise ValueError("use an explicit local http://127.0.0.1:PORT base")
    if not parsed.hostname or not ipaddress.ip_address(parsed.hostname).is_loopback:
        raise ValueError("local synthetic target only")
    return value.rstrip("/")


def money(value):
    return Decimal(str(value)).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


def prorated(price, units, days, period):
    return money(Decimal(str(price)) * units * days / period)


def timestamp(value):
    return datetime.fromisoformat(value.replace("Z", "+00:00"))


def signature(params, secret):
    text = "&".join(k + "=" + str(params[k]) for k in sorted(params)
                    if k not in ("sign", "sign_type") and params[k] != "")
    return hashlib.md5((text + secret).encode()).hexdigest()


def safe_detail(value):
    if isinstance(value, dict):
        return {k: ("[redacted]" if k in {"quote_id", "access_token", "key", "password", "pkey"} else safe_detail(v)) for k, v in value.items()}
    if isinstance(value, list):
        return [safe_detail(v) for v in value]
    return value


class Fixture:
    def __init__(self, args):
        self.base = local_base(args.base)
        self.database = args.database
        if not self.database.startswith("acceptance_") or not self.database.replace("_", "").isalnum():
            raise ValueError("database must be an acceptance_* synthetic database")
        self.pg = args.project + "-postgres"
        self.guard()
        self.port = args.mock_port
        self.mock_base = f"http://127.0.0.1:{self.port}"
        self.private = ROOT / "deploy/.secrets/subscription-v2-acceptance" / (self.database + "-" + secrets.token_hex(4))
        self.private.mkdir(parents=True, mode=0o700)
        self.checks = []
        self.merchant = secrets.token_hex(24)
        self.provider_orders = {}
        self.refunds = []
        self.refund_entered = None
        self.refund_release = None
        self.lock = threading.Lock()
        self.suffix = secrets.token_hex(5)
        self.users = set()
        self.plans = {}
        self.server = None

    def guard(self):
        label = BASE_HARNESS.run(["docker", "inspect", "--format", '{{index .Config.Labels "geili.acceptance"}}', self.pg]).strip()
        if label != "local":
            raise RuntimeError("refusing a database without geili.acceptance=local")

    def sql(self, query):
        self.guard()
        output = BASE_HARNESS.run(["docker", "exec", "-i", self.pg, "psql", "-XAt", "-v", "ON_ERROR_STOP=1", "-U", "acceptance", "-d", self.database], input=query)
        return [json.loads(line) for line in output.splitlines() if line.startswith("{")]

    def request(self, path, data=None, token=None, method=None):
        headers = {"Content-Type": "application/json"}
        if token:
            headers["Authorization"] = "Bearer " + token
        req = urllib.request.Request(self.base + path, data=None if data is None else json.dumps(data).encode(), headers=headers, method=method)
        try:
            response = urllib.request.urlopen(req, timeout=45)
        except urllib.error.HTTPError as error:
            response = error
        with response:
            raw = response.read().decode()
            try:
                body = json.loads(raw)
            except ValueError:
                body = raw
            return response.status, body, dict(response.headers)

    def api(self, path, data=None, token=None, method=None):
        status, body, _ = self.request("/api/v1" + path, data, token, method)
        if status >= 400:
            raise RuntimeError(f"{path} HTTP {status}: {str(safe_detail(body))[:500]}")
        return body.get("data", body)

    def check(self, name, condition, detail=None):
        item = {"name": name, "passed": bool(condition)}
        if detail is not None:
            item["detail"] = safe_detail(detail)
        self.checks.append(item)
        target = self.private / "report.json"
        target.write_text(json.dumps({"database": self.database, "checks": self.checks}, ensure_ascii=False, indent=2))
        target.chmod(0o600)
        print(("PASS " if condition else "FAIL ") + name, flush=True)
        if not condition:
            raise AssertionError(name + ": " + str(safe_detail(detail))[:600])

    def rejects(self, name, path, payload, token, reason=None, status=400):
        result, body, _ = self.request("/api/v1" + path, payload, token)
        self.check(name, result == status and (reason is None or isinstance(body, dict) and body.get("reason") == reason), {"status": result, "body": body})

    def start_mock(self):
        fixture = self

        class Gateway(BASE_HARNESS.Mock):
            def do_POST(self):
                if self.path.startswith("/upstream/"):
                    return super().do_POST()
                values = urllib.parse.parse_qs(self.rfile.read(int(self.headers.get("Content-Length", 0))).decode())
                values = {k: v[0] for k, v in values.items()}
                if self.path.startswith("/mapi.php"):
                    if values.get("sign") != signature(values, fixture.merchant):
                        return self.reply({"code": 0, "msg": "invalid synthetic signature"}, 400)
                    with fixture.lock:
                        fixture.provider_orders[values["out_trade_no"]] = values
                    key = values["out_trade_no"]
                    return self.reply({"code": 1, "trade_no": "fixture-" + key, "payurl": fixture.mock_base + "/pay/" + key, "qrcode": "synthetic-" + key})
                if self.path.startswith("/api.php?act=refund"):
                    if values.get("key") != fixture.merchant:
                        return self.reply({"code": 0, "msg": "invalid synthetic refund credential"}, 400)
                    with fixture.lock:
                        fixture.refunds.append(values["out_trade_no"])
                    if fixture.refund_entered is not None:
                        fixture.refund_entered.set()
                        if not fixture.refund_release.wait(15):
                            return self.reply({"code": 0, "msg": "synthetic provider timed out"}, 503)
                    return self.reply({"code": 1, "msg": "ok"})
                return self.reply({"code": 0, "msg": "unsupported synthetic endpoint"}, 404)

            def do_GET(self):
                if self.path.startswith("/api.php"):
                    query = urllib.parse.parse_qs(urllib.parse.urlsplit(self.path).query)
                    key = query.get("out_trade_no", [""])[0]
                    with fixture.lock:
                        order = fixture.provider_orders.get(key, {})
                    return self.reply({"code": 1, "status": 0, "money": order.get("money", "0"), "out_trade_no": key, "trade_no": "fixture-" + key})
                return super().do_GET()

        self.server = http.server.ThreadingHTTPServer(("127.0.0.1", self.port), Gateway)
        threading.Thread(target=self.server.serve_forever, daemon=True).start()

    def setup(self):
        cfg_path = ROOT / "deploy/.secrets/acceptance/local.json"
        if not cfg_path.is_file():
            raise RuntimeError("start acceptance.py/decoupled-acceptance.py first to generate local-only credentials")
        cfg = json.loads(cfg_path.read_text())
        self.admin = self.api("/auth/login", {"email": "admin@subscription-lab.invalid", "password": cfg["admin_password"]})["access_token"]
        for provider in self.api("/admin/payment/providers", token=self.admin):
            self.check("provider credentials are synthetic", provider["name"].startswith("Synthetic "), {"provider_id": provider["id"]})
            if provider.get("enabled"):
                self.api("/admin/payment/providers/" + str(provider["id"]), {"enabled": False}, self.admin, "PUT")
        self.api("/admin/payment/providers", {"provider_key": "easypay", "name": "Synthetic V2 " + self.suffix, "config": {"pid": "fixture-merchant", "pkey": self.merchant, "apiBase": self.mock_base, "notifyUrl": self.base + "/api/v1/payment/webhook/easypay", "returnUrl": self.base + "/payment/result", "currency": "USD"}, "supported_types": ["alipay"], "enabled": True, "payment_mode": "qrcode", "refund_enabled": True, "allow_user_refund": True}, self.admin)
        self.api("/admin/payment/config", {"enabled": True, "min_amount": 0.01, "max_amount": 10000, "max_pending_orders": 20, "enabled_payment_types": ["alipay"], "cancel_rate_limit_enabled": False}, self.admin, "PUT")
        for tier, (days, quota, price) in TIERS.items():
            self.plans[tier] = self.api("/admin/payment/plans", {"name": "V2 " + tier + " " + self.suffix, "price": float(price), "daily_limit_usd": quota, "weekly_limit_usd": quota * 7, "monthly_limit_usd": quota * 30, "validity_days": days, "validity_unit": "day", "for_sale": True}, self.admin)
        self.group = self.api("/admin/groups", {"name": "V2 upstream " + self.suffix, "platform": "openai", "rate_multiplier": 1, "subscription_rate_multiplier": 1, "subscription_enabled": True, "long_context_pricing_enabled": False, "model_pricing": [{"models": [MODEL], "billing_mode": "token", "input_price": 0.000001, "output_price": 0.000002}]}, self.admin)
        self.api("/admin/accounts", {"name": "V2 mock " + self.suffix, "platform": "openai", "type": "apikey", "credentials": {"api_key": "synthetic-test-key", "base_url": self.mock_base + "/upstream", "model_mapping": {MODEL: MODEL}}, "group_ids": [self.group["id"]], "concurrency": 10, "priority": 1}, self.admin)

    def user(self, label):
        password = secrets.token_urlsafe(24)
        user = self.api("/admin/users", {"email": "v2-" + label + "-" + self.suffix + "@example.invalid", "password": password, "balance": 0, "concurrency": 10}, self.admin)
        user["token"] = self.api("/auth/login", {"email": user["email"], "password": password})["access_token"]
        self.users.add(user["id"])
        user["fixture_password"] = password
        return user

    def quote(self, user, tier, operation, units=0, periods=0):
        return self.api("/payment/subscription-quote", {"plan_id": self.plans[tier]["id"], "operation": operation, "units": units, "periods": periods}, user["token"])

    @staticmethod
    def order_payload(quote):
        return {"quote_id": quote["quote_id"], "order_type": "subscription", "payment_type": "alipay"}

    def create(self, user, quote):
        result = self.api("/payment/orders", self.order_payload(quote), user["token"])
        self.check("payment and quote amounts agree", money(result["amount"]) == money(quote["order_amount"]), {"order_id": result["order_id"], "amount": result["amount"], "quoted": quote["order_amount"]})
        return result

    def notify(self, order, bad=False):
        params = {"pid": "fixture-merchant", "out_trade_no": order["out_trade_no"], "trade_no": "fixture-" + order["out_trade_no"], "trade_status": "TRADE_SUCCESS", "money": str(order["pay_amount"]), "type": "alipay"}
        params["sign"] = "invalid" if bad else signature(params, self.merchant)
        params["sign_type"] = "MD5"
        return self.request("/api/v1/payment/webhook/easypay?" + urllib.parse.urlencode(params))

    def pay(self, user, quote):
        order = self.create(user, quote)
        status, body, _ = self.notify(order)
        self.check("signed V2 callback accepted", status == 200, {"status": status, "body": body})
        return order

    def subscription(self, user, sid=None):
        subs = self.api("/subscriptions", token=user["token"])
        if sid is not None:
            return next(sub for sub in subs if sub["id"] == sid)
        return next(sub for sub in subs if sub.get("contract", {}).get("mode") == "v2" and sub.get("status") == "active")

    def key(self, user, sid):
        return self.api("/keys", {"name": "Synthetic V2 key", "billing_source": "subscription", "subscription_id": sid, "group_id": self.group["id"]}, user["token"])

    def call(self, key):
        return self.request("/v1/chat/completions", {"model": MODEL, "messages": [{"role": "user", "content": "Synthetic acceptance"}], "max_tokens": 16}, key["key"])

    def await_usage(self, user, sid, expected):
        for _ in range(100):
            sub = self.subscription(user, sid)
            if abs(Decimal(str(sub["quota_summary"]["daily_usage_usd"])) - Decimal(str(expected))) < Decimal("0.000000001"):
                return sub
            time.sleep(0.05)
        self.check("daily settlement completed", False, {"expected": expected, "actual": sub["quota_summary"]["daily_usage_usd"]})

    def fixture_expiry(self, user, sub, seconds):
        assert user["id"] in self.users and sub["user_id"] == user["id"]
        sid = int(sub["id"])
        self.sql(f"BEGIN; SELECT id FROM user_subscriptions WHERE id={sid} FOR UPDATE; UPDATE user_subscriptions SET expires_at=NOW()+INTERVAL '{int(seconds)} seconds' WHERE id={sid}; UPDATE subscription_contracts SET expires_at=(SELECT expires_at FROM user_subscriptions WHERE id={sid}),revision=revision+1 WHERE subscription_id={sid}; UPDATE subscription_contract_terms SET expires_at=(SELECT expires_at FROM user_subscriptions WHERE id={sid}) WHERE term_id=(SELECT term_id FROM subscription_contracts WHERE subscription_id={sid}); UPDATE user_subscription_entitlements SET expires_at=(SELECT expires_at FROM user_subscriptions WHERE id={sid}) WHERE user_subscription_id={sid} AND status='active'; COMMIT;")
        return self.subscription(user, sid)

    def verify_tiers(self):
        acquired = {}
        for tier, (days, daily, price) in TIERS.items():
            user = self.user(tier)
            units = 2 if tier == "month45" else 1
            quote = self.quote(user, tier, "purchase", units=units)
            remaining = (timestamp(quote["expires_at"]) - datetime.now(timezone.utc)).total_seconds()
            contract = quote["projected_contract"]
            self.check(tier + " signed quote schema and five-minute lifetime", bool(quote["quote_id"]) and 285 < remaining <= 300 and quote["billable_days"] == days and contract["quantity"] == units and contract["unit_daily_usd"] == daily and money(quote["order_amount"]) == money(Decimal(price) * units))
            order = self.create(user, quote)
            if tier == "month45":
                self.check("invalid payment signature rejected", self.notify(order, True)[0] == 400)
            self.check(tier + " payment accepted", self.notify(order)[0] == 200)
            sub = self.subscription(user)
            contract = sub["contract"]
            self.check(tier + " contract and shared daily quota", contract["mode"] == "v2" and contract["kind"] == ("week" if days == 7 else "month") and contract["quantity"] == units and bool(contract["term_id"]) and contract["revision"] >= 1 and sub["quota_summary"]["daily_limit_usd"] == daily * units and sub["quota_summary"].get("weekly_limit_usd") is None and sub["quota_summary"].get("monthly_limit_usd") is None)
            self.check(tier + " validity starts at fulfillment", abs((timestamp(contract["expires_at"]) - timestamp(contract["starts_at"])).total_seconds() - days * 86400) < 0.001)
            acquired[tier] = (user, sub, order)
            if tier == "month180":
                fixture = self.private / "browser-user.json"
                fixture.write_text(json.dumps({"base": self.base, "database": self.database, "email": user["email"], "password": user["fixture_password"], "subscription_id": sub["id"], "plan_ids": {name: p["id"] for name, p in self.plans.items()}}, indent=2))
                fixture.chmod(0o600)
        return acquired

    def verify_changes(self, acquired):
        user, sub, first = acquired["month45"]
        sid = sub["id"]
        term = sub["contract"]["term_id"]
        with ThreadPoolExecutor(max_workers=5) as pool:
            statuses = list(pool.map(lambda _: self.notify(first)[0], range(5)))
        self.check("parallel duplicate callbacks grant once", statuses == [200] * 5 and self.subscription(user)["contract"] == sub["contract"])
        key = self.key(user, sid)
        self.check("purchased subscription request succeeds", self.call(key)[0] == 200)
        sub = self.await_usage(user, sid, "0.0012")
        sub = self.fixture_expiry(user, sub, 2 * 86400 + 3600)
        end = sub["contract"]["expires_at"]
        before_usage = sub["quota_summary"]["daily_usage_usd"]
        quote = self.quote(user, "month45", "stack", units=2)
        stale = self.quote(user, "month45", "renew", periods=1)
        self.check("three billed days prorate two stacked units once", quote["billable_days"] == 3 and money(quote["order_amount"]) == prorated("10.01", 2, 3, 30) and quote["projected_contract"]["expires_at"] == end and quote["projected_contract"]["quantity"] == 4)
        self.pay(user, quote)
        stacked = self.subscription(user, sid)
        self.check("stack keeps ID term expiry and today's usage", stacked["id"] == sid and stacked["contract"]["term_id"] == term and stacked["contract"]["expires_at"] == end and stacked["quota_summary"]["daily_usage_usd"] == before_usage and stacked["quota_summary"]["daily_limit_usd"] == 180)
        self.rejects("changed contract invalidates prior quote", "/payment/orders", self.order_payload(stale), user["token"], "SUBSCRIPTION_QUOTE_CHANGED", 409)
        quote = self.quote(user, "month45", "renew", periods=2)
        self.check("renew bills every current unit", money(quote["order_amount"]) == money(Decimal("10.01") * 4 * 2) and quote["projected_contract"]["quantity"] == 4 and (timestamp(quote["projected_contract"]["expires_at"]) - timestamp(end)).total_seconds() == 60 * 86400)
        self.pay(user, quote)
        extended = self.subscription(user, sid)
        self.check("renew preserves daily usage and original key", extended["quota_summary"]["daily_usage_usd"] == before_usage and extended["id"] == sid and extended["contract"]["term_id"] == term)
        long_stack = self.quote(user, "month45", "stack", units=1)
        self.check("prepaid stack covers more than one full period", long_stack["billable_days"] == 63 and money(long_stack["order_amount"]) == prorated("10.01", 1, 63, 30))
        quote = self.quote(user, "month180", "upgrade")
        self.check("direct 45-to-180 upgrade prorates all four units over full term", quote["billable_days"] == 63 and money(quote["order_amount"]) == prorated(Decimal("40.05") - Decimal("10.01"), 4, 63, 30) and quote["projected_contract"]["expires_at"] == extended["contract"]["expires_at"])
        self.pay(user, quote)
        upgraded = self.subscription(user, sid)
        self.check("upgrade keeps key owner term quantity and usage", upgraded["id"] == sid and upgraded["contract"]["term_id"] == term and upgraded["contract"]["quantity"] == 4 and upgraded["quota_summary"]["daily_limit_usd"] == 720 and upgraded["quota_summary"]["daily_usage_usd"] == before_usage)
        self.check("existing key follows upgraded contract", self.call(key)[0] == 200)
        self.await_usage(user, sid, "0.0024")
        for operation in ("stack", "renew", "upgrade"):
            payload = {"plan_id": self.plans["week180"]["id"], "operation": operation, "units": 1 if operation == "stack" else 0, "periods": 1 if operation == "renew" else 0}
            self.rejects("active month rejects cross-type " + operation, "/payment/subscription-quote", payload, user["token"], "SUBSCRIPTION_TYPE_MISMATCH")
        self.rejects("active contract rejects downgrade", "/payment/subscription-quote", {"plan_id": self.plans["month90"]["id"], "operation": "upgrade"}, user["token"], "SUBSCRIPTION_TIER_MISMATCH")
        for operation in ("stack", "renew"):
            payload = {"plan_id": self.plans["month90"]["id"], "operation": operation, "units": 1 if operation == "stack" else 0, "periods": 1 if operation == "renew" else 0}
            self.rejects("different tier rejects " + operation, "/payment/subscription-quote", payload, user["token"], "SUBSCRIPTION_TIER_MISMATCH")
        self.rejects("zero stack units rejected", "/payment/subscription-quote", {"plan_id": self.plans["month180"]["id"], "operation": "stack", "units": 0}, user["token"])
        self.rejects("eleven renew periods rejected", "/payment/subscription-quote", {"plan_id": self.plans["month180"]["id"], "operation": "renew", "periods": 11}, user["token"])
        self.fixture_expiry(user, upgraded, 3600)
        quote = self.quote(user, "month180", "stack", units=1)
        self.check("less than one remaining day bills one day", quote["billable_days"] == 1 and money(quote["order_amount"]) == prorated("40.05", 1, 1, 30))

    def verify_concurrency(self):
        user = self.user("concurrent")
        quote = self.quote(user, "week90", "purchase", units=1)
        with ThreadPoolExecutor(max_workers=4) as pool:
            replies = list(pool.map(lambda _: self.request("/api/v1/payment/orders", self.order_payload(quote), user["token"]), range(4)))
        successes = [body["data"] for status, body, _ in replies if status == 200]
        failures = [(status, body.get("reason")) for status, body, _ in replies if status != 200]
        count = self.sql(f"SELECT json_build_object('n',COUNT(*)) FROM payment_orders WHERE user_id={user['id']} AND order_type='subscription';")[0]["n"]
        self.check("one subscription order wins concurrent creation", len(successes) == 1 and count == 1 and failures == [(409, "SUBSCRIPTION_ORDER_PENDING")] * 3, {"orders": count, "failures": failures})
        self.check("winning concurrent order fulfills", self.notify(successes[0])[0] == 200)
        self.check("concurrent winner grants one unit", self.subscription(user)["contract"]["quantity"] == 1)
        other = self.user("quote-owner")
        self.rejects("quote cannot be used by another user", "/payment/orders", self.order_payload(quote), other["token"], "SUBSCRIPTION_QUOTE_INVALID")
        self.rejects("subscription order requires authoritative quote", "/payment/orders", {"order_type": "subscription", "payment_type": "alipay", "plan_id": self.plans["week90"]["id"]}, other["token"], "SUBSCRIPTION_QUOTE_INVALID")
        quote = self.quote(other, "week90", "purchase", units=1)
        self.api("/admin/payment/plans/" + str(self.plans["week90"]["id"]), {"price": 13.34}, self.admin, "PUT")
        self.rejects("sale-price change invalidates quote", "/payment/orders", self.order_payload(quote), other["token"], "SUBSCRIPTION_QUOTE_CHANGED", 409)
        fresh = self.quote(other, "week90", "purchase", units=1)
        order = self.create(other, fresh)
        self.api("/admin/payment/plans/" + str(self.plans["week90"]["id"]), {"price": 14.34}, self.admin, "PUT")
        self.check("paid order honors locked price despite later repricing", self.notify(order)[0] == 200 and money(order["amount"]) == money("13.34") and self.subscription(other)["contract"]["unit_daily_usd"] == 90)

    def verify_refund(self, acquired):
        user, sub, original = acquired["week180"]
        quote = self.quote(user, "week180", "renew", periods=1)
        order = self.pay(user, quote)
        result = self.api("/admin/payment/orders/" + str(order["order_id"]) + "/refund", {"amount": float(quote["order_amount"]), "reason": "synthetic unchanged renewal", "deduct_balance": True}, self.admin)
        restored = self.subscription(user, sub["id"])
        self.check("unused last contract change refunds precisely", result["success"] and restored["contract"]["expires_at"] == sub["contract"]["expires_at"] and restored["contract"]["quantity"] == 1 and restored["quota_summary"]["daily_limit_usd"] == 180 and len(self.refunds) == 1)
        key = self.key(user, sub["id"])
        self.check("refunded renewal leaves original quota usable", self.call(key)[0] == 200)
        self.await_usage(user, sub["id"], "0.0012")
        status, body, _ = self.request("/api/v1/admin/payment/orders/" + str(original["order_id"]) + "/refund", {"amount": original["amount"], "reason": "synthetic used contract", "force": True, "deduct_balance": True}, self.admin)
        self.check("used contract refund requires manual review even with force", status == 409 and len(self.refunds) == 1, {"status": status, "body": body})

    def verify_refund_freeze(self):
        user = self.user("refund-freeze")
        self.pay(user, self.quote(user, "month45", "purchase", units=1))
        before = self.subscription(user)
        sid = before["id"]
        order = self.pay(user, self.quote(user, "month45", "renew", periods=1))
        self.refund_entered, self.refund_release = threading.Event(), threading.Event()
        try:
            with ThreadPoolExecutor(max_workers=1) as pool:
                future = pool.submit(self.request, "/api/v1/admin/payment/orders/" + str(order["order_id"]) + "/refund", {"amount": order["amount"], "reason": "synthetic slow provider", "deduct_balance": True}, self.admin)
                try:
                    self.check("refund freezes rights before provider call", self.refund_entered.wait(10))
                    attempts = [("extend", f"/admin/subscriptions/{sid}/extend", {"days": 30}, None), ("reset", f"/admin/subscriptions/{sid}/reset-quota", {"daily": True}, None), ("revoke", f"/admin/subscriptions/{sid}/revoke", {}, None), ("restore", f"/admin/subscriptions/{sid}/restore", {}, None), ("delete", f"/admin/subscriptions/{sid}", None, "DELETE")]
                    for label, path, payload, method in attempts:
                        status, body, _ = self.request("/api/v1" + path, payload, self.admin, method)
                        self.check("in-flight refund blocks admin " + label, status == 409, {"status": status, "body": body})
                finally:
                    self.refund_release.set()
                status, body, _ = future.result(timeout=20)
                restored = self.subscription(user, sid)
                self.check("provider success restores exact original expiry after blocked admin changes", status == 200 and body["data"]["success"] and restored["contract"]["expires_at"] == before["contract"]["expires_at"] and restored["contract"]["quantity"] == before["contract"]["quantity"] and restored["status"] == "active", {"status": status, "body": body})
        finally:
            self.refund_entered, self.refund_release = None, None

    def verify_paid_conflict_and_expiry(self, acquired):
        user, sub, _ = acquired["month90"]
        order = self.create(user, self.quote(user, "month90", "renew", periods=1))
        self.sql(f"UPDATE subscription_contracts SET revision=revision+1 WHERE subscription_id={sub['id']} AND user_id={user['id']};")
        status, body, _ = self.notify(order)
        detail = self.api("/admin/payment/orders/" + str(order["order_id"]), token=self.admin)["order"]
        unchanged = self.subscription(user, sub["id"])
        self.check("paid revision conflict remains visible without changing entitlement", status == 200 and detail["status"] == "FAILED" and bool(detail.get("paid_at")) and unchanged["contract"]["expires_at"] == sub["contract"]["expires_at"] and unchanged["contract"]["quantity"] == sub["contract"]["quantity"], {"callback_status": status, "order_status": detail["status"], "paid_at": detail.get("paid_at")})
        status, body, _ = self.request("/api/v1/payment/orders/" + str(order["order_id"]) + "/refund-request", {"reason": "synthetic paid fulfillment conflict"}, user["token"])
        self.check("paid unassigned conflict retains user refund request", status == 200, {"status": status, "body": body})
        user, sub, _ = acquired["week90"]
        self.fixture_expiry(user, sub, -1)
        self.pay(user, self.quote(user, "month45", "purchase", units=1))
        next_term = self.subscription(user)
        self.check("natural expiry permits different type with fresh term and usage", next_term["contract"]["kind"] == "month" and next_term["contract"]["term_id"] != sub["contract"]["term_id"] and next_term["quota_summary"]["daily_usage_usd"] == 0 and next_term["quota_summary"]["daily_limit_usd"] == 45)

    def verify_migration_edge_cases(self):
        legacy_plan = self.api("/admin/payment/plans", {"name": "V2 legacy-recognized " + self.suffix, "price": 10, "daily_limit_usd": 45, "validity_days": 30, "validity_unit": "day", "for_sale": False}, self.admin)
        self.sql(f"UPDATE subscription_plans SET is_legacy_compat=TRUE WHERE id={legacy_plan['id']};")
        user = self.user("legacy-recognized")
        sid = self.sql(f"INSERT INTO user_subscriptions(user_id,plan_id,starts_at,expires_at,status) VALUES({user['id']},{legacy_plan['id']},NOW()-INTERVAL '1 day',NOW()+INTERVAL '3 days','active') RETURNING json_build_object('id',id);")[0]["id"]
        self.sql(f"INSERT INTO user_subscription_entitlements(user_subscription_id,plan_id,starts_at,expires_at,daily_limit_usd,status) VALUES({sid},{legacy_plan['id']},NOW()-INTERVAL '1 day',NOW()+INTERVAL '3 days',45,'active');")
        self.sql((ROOT / "backend/migrations/253_subscription_contract_v2.sql").read_text())
        self.check("recognized historical compatibility plan stays legacy during migration", self.subscription(user, sid)["contract"]["mode"] == "legacy_daily")
        siblings = self.user("legacy-siblings")
        parents = self.sql(f"INSERT INTO user_subscriptions(user_id,plan_id,starts_at,expires_at,status,daily_window_start,daily_usage_usd) SELECT {siblings['id']},plan_id,NOW()-INTERVAL '1 day',NOW()+INTERVAL '3 days','active',date_trunc('day',NOW() AT TIME ZONE 'Asia/Shanghai') AT TIME ZONE 'Asia/Shanghai',spent FROM (VALUES({self.plans['month45']['id']},12.345),({self.plans['month90']['id']},4.567)) AS fixtures(plan_id,spent) RETURNING json_build_object('id',id,'plan_id',plan_id,'daily_usage_usd',daily_usage_usd);")
        with_lot = next(parent for parent in parents if parent["plan_id"] == self.plans["month90"]["id"])
        self.sql(f"INSERT INTO user_subscription_entitlements(user_subscription_id,plan_id,starts_at,expires_at,daily_limit_usd,status,daily_window_start,daily_usage_usd) VALUES({with_lot['id']},{with_lot['plan_id']},NOW()-INTERVAL '1 day',NOW()+INTERVAL '3 days',90,'active',date_trunc('day',NOW() AT TIME ZONE 'Asia/Shanghai') AT TIME ZONE 'Asia/Shanghai',4.567);")
        self.sql((ROOT / "backend/migrations/253_subscription_contract_v2.sql").read_text())
        migrated = self.sql(f"SELECT json_build_object('id',c.subscription_id,'mode',c.mode,'used',d.used_usd) FROM subscription_contracts c JOIN subscription_daily_usage d ON d.subscription_id=c.subscription_id AND d.term_id=c.term_id WHERE c.user_id={siblings['id']} AND d.usage_date=(NOW() AT TIME ZONE 'Asia/Shanghai')::DATE;")
        expected = {parent["id"]: Decimal(str(parent["daily_usage_usd"])) for parent in parents}
        self.check("sibling subscriptions stay legacy and preserve parent-only daily baseline", len(migrated) == 2 and all(row["mode"] == "legacy_daily" and Decimal(str(row["used"])) == expected[row["id"]] for row in migrated), migrated)
        owner = self.user("historical-upgrade")
        self.pay(owner, self.quote(owner, "month45", "purchase", units=1))
        current = self.subscription(owner)
        target = self.plans["month90"]["id"]
        expired = self.sql(f"INSERT INTO user_subscriptions(user_id,plan_id,starts_at,expires_at,status) VALUES({owner['id']},{target},NOW()-INTERVAL '31 days',NOW()-INTERVAL '1 day','expired') RETURNING json_build_object('id',id);")[0]["id"]
        self.sql(f"INSERT INTO user_subscription_entitlements(user_subscription_id,plan_id,starts_at,expires_at,daily_limit_usd,status) VALUES({expired},{target},NOW()-INTERVAL '31 days',NOW()-INTERVAL '1 day',90,'expired');")
        self.pay(owner, self.quote(owner, "month90", "upgrade"))
        upgraded = self.subscription(owner, current["id"])
        history = self.subscription(owner, expired)
        self.check("upgrade into historically owned target retains active identity and old history", upgraded["id"] == current["id"] and upgraded["contract"]["plan_id"] == target and upgraded["contract"]["term_id"] == current["contract"]["term_id"] and history["id"] == expired and history["status"] == "expired")
        quote = self.quote(owner, "month90", "renew", periods=1)
        self.sql(f"UPDATE user_subscriptions SET status='suspended' WHERE id={current['id']} AND user_id={owner['id']};")
        before = self.sql(f"SELECT json_build_object('n',COUNT(*)) FROM payment_orders WHERE user_id={owner['id']};")[0]["n"]
        self.rejects("suspended contract invalidates quote before charging", "/payment/orders", self.order_payload(quote), owner["token"], "SUBSCRIPTION_QUOTE_CHANGED", 409)
        self.check("suspended quote creates no payment order", self.sql(f"SELECT json_build_object('n',COUNT(*)) FROM payment_orders WHERE user_id={owner['id']};")[0]["n"] == before)

    def verify_legacy_day_ledger(self):
        user = self.user("legacy-day90")
        uid, pid = user["id"], self.plans["month45"]["id"]
        sid = self.sql(f"INSERT INTO user_subscriptions(user_id,plan_id,starts_at,expires_at,status,daily_window_start,weekly_window_start,monthly_window_start,daily_usage_usd,weekly_usage_usd,monthly_usage_usd) VALUES({uid},{pid},NOW()-INTERVAL '10 days',NOW()+INTERVAL '5 days','active',date_trunc('day',NOW() AT TIME ZONE 'Asia/Shanghai') AT TIME ZONE 'Asia/Shanghai',NOW()-INTERVAL '6 days',NOW()-INTERVAL '10 days',87.04857312,451.224,451.224) RETURNING json_build_object('id',id);")[0]["id"]
        self.sql(f"INSERT INTO user_subscription_entitlements(user_subscription_id,plan_id,lot_index,purchase_mode,status,starts_at,expires_at,daily_limit_usd,weekly_limit_usd,monthly_limit_usd,daily_window_start,weekly_window_start,monthly_window_start,daily_usage_usd,weekly_usage_usd,monthly_usage_usd,lifetime_usage_usd) SELECT {sid},{pid},lot_index,'stack','active',NOW()-INTERVAL '10 days',NOW()+duration,45,315,1350,date_trunc('day',NOW() AT TIME ZONE 'Asia/Shanghai') AT TIME ZONE 'Asia/Shanghai',NOW()-INTERVAL '6 days',NOW()-INTERVAL '10 days',daily_used,weekly_used,weekly_used,weekly_used FROM (VALUES(0,INTERVAL '3 days',41.92257312,315),(1,INTERVAL '5 days',45.126,136.224)) AS lots(lot_index,duration,daily_used,weekly_used);")
        before = self.sql(f"SELECT row_to_json(x) FROM (SELECT id,plan_id,expires_at,daily_usage_usd,weekly_usage_usd,monthly_usage_usd FROM user_subscription_entitlements WHERE user_subscription_id={sid} ORDER BY id) x;")
        migration = (ROOT / "backend/migrations/253_subscription_contract_v2.sql").read_text()
        self.sql(migration)
        sub = self.subscription(user, sid)
        summary = sub["quota_summary"]
        self.check("legacy two-lot migration recovers exact daily remainder", sub["contract"]["mode"] == "legacy_daily" and summary["daily_limit_usd"] == 90 and Decimal(str(summary["daily_usage_usd"])) == Decimal("87.04857312") and Decimal(str(summary["remaining_usd"])) == Decimal("2.95142688") and summary.get("weekly_limit_usd") is None and summary.get("monthly_limit_usd") is None, summary)
        after = self.sql(f"SELECT row_to_json(x) FROM (SELECT id,plan_id,expires_at,daily_usage_usd,weekly_usage_usd,monthly_usage_usd FROM user_subscription_entitlements WHERE user_subscription_id={sid} ORDER BY id) x;")
        self.check("migration preserves old lots dates and financial evidence", before == after)
        initial_contract = sub["contract"]
        self.sql(migration)
        self.check("migration replay preserves term identity and daily baseline", self.subscription(user, sid)["contract"] == initial_contract and self.subscription(user, sid)["quota_summary"] == summary)
        key = self.key(user, sid)
        self.check("old weekly cap and individual daily cap no longer block shared daily remainder", self.call(key)[0] == 200)
        self.await_usage(user, sid, "87.04977312")
        for operation in ("purchase", "stack", "renew", "upgrade"):
            self.rejects("legacy compatibility blocks self-service " + operation, "/payment/subscription-quote", {"plan_id": self.plans["month90"]["id"], "operation": operation, "units": 1 if operation in ("purchase", "stack") else 0, "periods": 1 if operation == "renew" else 0}, user["token"], "SUBSCRIPTION_COMPATIBILITY_MODE", 409)
        # Financial settlement now precedes durable detail delivery. Wait for
        # this synthetic user's prior work, then compare authoritative money and
        # idempotency evidence rather than a timing-sensitive usage_logs count.
        def pending_financial_details():
            return self.sql(f"SELECT json_build_object('n',COUNT(*)) FROM usage_settlement_receipts WHERE user_id={uid} AND (state='pending' OR (record_source='live' AND record_completeness='complete' AND delivered_at IS NULL));")[0]["n"]
        deadline = time.monotonic() + 15
        while pending_financial_details() and time.monotonic() < deadline:
            time.sleep(0.05)
        self.check("prior legacy request receipt and detail delivery drained", pending_financial_details() == 0)
        def financial_state():
            return self.sql(f"""SELECT json_build_object(
                'balance',(SELECT balance::text FROM users WHERE id={uid}),
                'key', (SELECT json_build_object('quota_used',quota_used::text,'usage_5h',usage_5h::text,'usage_1d',usage_1d::text,'usage_7d',usage_7d::text) FROM api_keys WHERE id={int(key['id'])}),
                'ledger',(SELECT json_agg(x ORDER BY x.term_id,x.usage_date) FROM (SELECT term_id,usage_date,used_usd::text FROM subscription_daily_usage WHERE subscription_id={sid}) x),
                'allocations',(SELECT json_agg(x ORDER BY x.id) FROM (SELECT a.id,a.request_key,a.entitlement_id,a.cost_usd::text FROM subscription_usage_allocations a JOIN subscription_requests r ON r.request_key=a.request_key WHERE r.subscription_id={sid}) x),
                'receipts',(SELECT json_agg(x ORDER BY x.id) FROM (SELECT id,request_id,state,charged_amount::text FROM usage_settlement_receipts WHERE user_id={uid}) x),
                'dedup',(SELECT json_agg(x ORDER BY x.request_id) FROM (SELECT request_id,request_fingerprint FROM usage_billing_dedup WHERE api_key_id={int(key['id'])}) x)
            );""")[0]
        self.sql(f"UPDATE subscription_daily_usage SET used_usd=90 WHERE subscription_id={sid} AND term_id=(SELECT term_id FROM subscription_contracts WHERE subscription_id={sid}) AND usage_date=(NOW() AT TIME ZONE 'Asia/Shanghai')::DATE;")
        before_rejection = financial_state()
        status, body, headers = self.call(key)
        lowered = {k.lower(): v for k, v in headers.items()}
        expected_reset = (datetime.now(BEIJING).replace(hour=0, minute=0, second=0, microsecond=0) + timedelta(days=1))
        retry = int(lowered.get("retry-after", "0"))
        self.check("daily exhaustion reports 429 with code reset metadata and Retry-After", status == 429 and "DAILY_LIMIT_EXCEEDED" in json.dumps(body) and "window_resets_at" in json.dumps(body) and abs(retry - (expected_reset - datetime.now(BEIJING)).total_seconds()) <= 3, {"status": status, "body": body, "retry_after": retry})
        after_rejection = financial_state()
        self.check("quota rejection produces no extra debit", after_rejection == before_rejection, {"before": before_rejection, "after": after_rejection})
        # Move only this synthetic exhausted bucket to yesterday, preserving history.
        self.sql(f"UPDATE subscription_daily_usage SET usage_date=usage_date-1 WHERE subscription_id={sid} AND term_id=(SELECT term_id FROM subscription_contracts WHERE subscription_id={sid}) AND usage_date=(NOW() AT TIME ZONE 'Asia/Shanghai')::DATE;")
        reset = self.subscription(user, sid)
        self.check("new Beijing date projects unused shared daily quota", reset["quota_summary"]["daily_usage_usd"] == 0 and reset["quota_summary"]["remaining_usd"] == 90)
        self.check("new date admits existing subscription key", self.call(key)[0] == 200)
        self.await_usage(user, sid, "0.0012")

    def run(self):
        self.start_mock()
        try:
            self.setup()
            acquired = self.verify_tiers()
            self.verify_changes(acquired)
            self.verify_concurrency()
            self.verify_refund(acquired)
            self.verify_refund_freeze()
            self.verify_paid_conflict_and_expiry(acquired)
            self.verify_legacy_day_ledger()
            self.verify_migration_edge_cases()
            print(f"Subscription V2 synthetic HTTP acceptance: {len(self.checks)} checks passed", flush=True)
            print("Report: " + str(self.private / "report.json"), flush=True)
        finally:
            if self.server:
                self.server.shutdown()
                self.server.server_close()


def arguments():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--base", default=os.getenv("GEILI_V2_BASE", "http://127.0.0.1:18494"))
    parser.add_argument("--database", default=os.getenv("GEILI_V2_DB", "acceptance_v2"))
    parser.add_argument("--project", default=os.getenv("GEILI_ACCEPTANCE_PROJECT", "geili-acceptance-local"))
    parser.add_argument("--mock-port", type=int, default=19013)
    return parser.parse_args()


if __name__ == "__main__":
    Fixture(arguments()).run()
