// Code generated by ent, DO NOT EDIT.

package subscriptionentitlementorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the subscriptionentitlementorder type in the database.
	Label = "subscription_entitlement_order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEntitlementID holds the string denoting the entitlement_id field in the database.
	FieldEntitlementID = "entitlement_id"
	// FieldOrderID holds the string denoting the order_id field in the database.
	FieldOrderID = "order_id"
	// FieldLotIndex holds the string denoting the lot_index field in the database.
	FieldLotIndex = "lot_index"
	// FieldOperation holds the string denoting the operation field in the database.
	FieldOperation = "operation"
	// FieldDaysAdded holds the string denoting the days_added field in the database.
	FieldDaysAdded = "days_added"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeEntitlement holds the string denoting the entitlement edge name in mutations.
	EdgeEntitlement = "entitlement"
	// EdgeOrder holds the string denoting the order edge name in mutations.
	EdgeOrder = "order"
	// Table holds the table name of the subscriptionentitlementorder in the database.
	Table = "subscription_entitlement_orders"
	// EntitlementTable is the table that holds the entitlement relation/edge.
	EntitlementTable = "subscription_entitlement_orders"
	// EntitlementInverseTable is the table name for the UserSubscriptionEntitlement entity.
	// It exists in this package in order to avoid circular dependency with the "usersubscriptionentitlement" package.
	EntitlementInverseTable = "user_subscription_entitlements"
	// EntitlementColumn is the table column denoting the entitlement relation/edge.
	EntitlementColumn = "entitlement_id"
	// OrderTable is the table that holds the order relation/edge.
	OrderTable = "subscription_entitlement_orders"
	// OrderInverseTable is the table name for the PaymentOrder entity.
	// It exists in this package in order to avoid circular dependency with the "paymentorder" package.
	OrderInverseTable = "payment_orders"
	// OrderColumn is the table column denoting the order relation/edge.
	OrderColumn = "order_id"
)

// Columns holds all SQL columns for subscriptionentitlementorder fields.
var Columns = []string{
	FieldID,
	FieldEntitlementID,
	FieldOrderID,
	FieldLotIndex,
	FieldOperation,
	FieldDaysAdded,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLotIndex holds the default value on creation for the "lot_index" field.
	DefaultLotIndex int
	// OperationValidator is a validator for the "operation" field. It is called by the builders before save.
	OperationValidator func(string) error
	// DefaultDaysAdded holds the default value on creation for the "days_added" field.
	DefaultDaysAdded int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the SubscriptionEntitlementOrder queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEntitlementID orders the results by the entitlement_id field.
func ByEntitlementID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntitlementID, opts...).ToFunc()
}

// ByOrderID orders the results by the order_id field.
func ByOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderID, opts...).ToFunc()
}

// ByLotIndex orders the results by the lot_index field.
func ByLotIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLotIndex, opts...).ToFunc()
}

// ByOperation orders the results by the operation field.
func ByOperation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperation, opts...).ToFunc()
}

// ByDaysAdded orders the results by the days_added field.
func ByDaysAdded(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDaysAdded, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByEntitlementField orders the results by entitlement field.
func ByEntitlementField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEntitlementStep(), sql.OrderByField(field, opts...))
	}
}

// ByOrderField orders the results by order field.
func ByOrderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrderStep(), sql.OrderByField(field, opts...))
	}
}
func newEntitlementStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EntitlementInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EntitlementTable, EntitlementColumn),
	)
}
func newOrderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OrderTable, OrderColumn),
	)
}
