// Code generated by ent, DO NOT EDIT.

package subscriptionentitlementorder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldLTE(FieldID, id))
}

// EntitlementID applies equality check predicate on the "entitlement_id" field. It's identical to EntitlementIDEQ.
func EntitlementID(v int64) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldEQ(FieldEntitlementID, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v int64) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldEQ(FieldOrderID, v))
}

// LotIndex applies equality check predicate on the "lot_index" field. It's identical to LotIndexEQ.
func LotIndex(v int) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldEQ(FieldLotIndex, v))
}

// Operation applies equality check predicate on the "operation" field. It's identical to OperationEQ.
func Operation(v string) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldEQ(FieldOperation, v))
}

// DaysAdded applies equality check predicate on the "days_added" field. It's identical to DaysAddedEQ.
func DaysAdded(v int) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldEQ(FieldDaysAdded, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// EntitlementIDEQ applies the EQ predicate on the "entitlement_id" field.
func EntitlementIDEQ(v int64) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldEQ(FieldEntitlementID, v))
}

// EntitlementIDNEQ applies the NEQ predicate on the "entitlement_id" field.
func EntitlementIDNEQ(v int64) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldNEQ(FieldEntitlementID, v))
}

// EntitlementIDIn applies the In predicate on the "entitlement_id" field.
func EntitlementIDIn(vs ...int64) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldIn(FieldEntitlementID, vs...))
}

// EntitlementIDNotIn applies the NotIn predicate on the "entitlement_id" field.
func EntitlementIDNotIn(vs ...int64) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldNotIn(FieldEntitlementID, vs...))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v int64) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v int64) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...int64) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...int64) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldNotIn(FieldOrderID, vs...))
}

// LotIndexEQ applies the EQ predicate on the "lot_index" field.
func LotIndexEQ(v int) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldEQ(FieldLotIndex, v))
}

// LotIndexNEQ applies the NEQ predicate on the "lot_index" field.
func LotIndexNEQ(v int) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldNEQ(FieldLotIndex, v))
}

// LotIndexIn applies the In predicate on the "lot_index" field.
func LotIndexIn(vs ...int) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldIn(FieldLotIndex, vs...))
}

// LotIndexNotIn applies the NotIn predicate on the "lot_index" field.
func LotIndexNotIn(vs ...int) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldNotIn(FieldLotIndex, vs...))
}

// LotIndexGT applies the GT predicate on the "lot_index" field.
func LotIndexGT(v int) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldGT(FieldLotIndex, v))
}

// LotIndexGTE applies the GTE predicate on the "lot_index" field.
func LotIndexGTE(v int) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldGTE(FieldLotIndex, v))
}

// LotIndexLT applies the LT predicate on the "lot_index" field.
func LotIndexLT(v int) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldLT(FieldLotIndex, v))
}

// LotIndexLTE applies the LTE predicate on the "lot_index" field.
func LotIndexLTE(v int) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldLTE(FieldLotIndex, v))
}

// OperationEQ applies the EQ predicate on the "operation" field.
func OperationEQ(v string) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldEQ(FieldOperation, v))
}

// OperationNEQ applies the NEQ predicate on the "operation" field.
func OperationNEQ(v string) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldNEQ(FieldOperation, v))
}

// OperationIn applies the In predicate on the "operation" field.
func OperationIn(vs ...string) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldIn(FieldOperation, vs...))
}

// OperationNotIn applies the NotIn predicate on the "operation" field.
func OperationNotIn(vs ...string) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldNotIn(FieldOperation, vs...))
}

// OperationGT applies the GT predicate on the "operation" field.
func OperationGT(v string) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldGT(FieldOperation, v))
}

// OperationGTE applies the GTE predicate on the "operation" field.
func OperationGTE(v string) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldGTE(FieldOperation, v))
}

// OperationLT applies the LT predicate on the "operation" field.
func OperationLT(v string) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldLT(FieldOperation, v))
}

// OperationLTE applies the LTE predicate on the "operation" field.
func OperationLTE(v string) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldLTE(FieldOperation, v))
}

// OperationContains applies the Contains predicate on the "operation" field.
func OperationContains(v string) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldContains(FieldOperation, v))
}

// OperationHasPrefix applies the HasPrefix predicate on the "operation" field.
func OperationHasPrefix(v string) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldHasPrefix(FieldOperation, v))
}

// OperationHasSuffix applies the HasSuffix predicate on the "operation" field.
func OperationHasSuffix(v string) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldHasSuffix(FieldOperation, v))
}

// OperationEqualFold applies the EqualFold predicate on the "operation" field.
func OperationEqualFold(v string) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldEqualFold(FieldOperation, v))
}

// OperationContainsFold applies the ContainsFold predicate on the "operation" field.
func OperationContainsFold(v string) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldContainsFold(FieldOperation, v))
}

// DaysAddedEQ applies the EQ predicate on the "days_added" field.
func DaysAddedEQ(v int) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldEQ(FieldDaysAdded, v))
}

// DaysAddedNEQ applies the NEQ predicate on the "days_added" field.
func DaysAddedNEQ(v int) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldNEQ(FieldDaysAdded, v))
}

// DaysAddedIn applies the In predicate on the "days_added" field.
func DaysAddedIn(vs ...int) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldIn(FieldDaysAdded, vs...))
}

// DaysAddedNotIn applies the NotIn predicate on the "days_added" field.
func DaysAddedNotIn(vs ...int) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldNotIn(FieldDaysAdded, vs...))
}

// DaysAddedGT applies the GT predicate on the "days_added" field.
func DaysAddedGT(v int) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldGT(FieldDaysAdded, v))
}

// DaysAddedGTE applies the GTE predicate on the "days_added" field.
func DaysAddedGTE(v int) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldGTE(FieldDaysAdded, v))
}

// DaysAddedLT applies the LT predicate on the "days_added" field.
func DaysAddedLT(v int) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldLT(FieldDaysAdded, v))
}

// DaysAddedLTE applies the LTE predicate on the "days_added" field.
func DaysAddedLTE(v int) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldLTE(FieldDaysAdded, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// HasEntitlement applies the HasEdge predicate on the "entitlement" edge.
func HasEntitlement() predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EntitlementTable, EntitlementColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEntitlementWith applies the HasEdge predicate on the "entitlement" edge with a given conditions (other predicates).
func HasEntitlementWith(preds ...predicate.UserSubscriptionEntitlement) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(func(s *sql.Selector) {
		step := newEntitlementStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOrder applies the HasEdge predicate on the "order" edge.
func HasOrder() predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OrderTable, OrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrderWith applies the HasEdge predicate on the "order" edge with a given conditions (other predicates).
func HasOrderWith(preds ...predicate.PaymentOrder) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(func(s *sql.Selector) {
		step := newOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionEntitlementOrder) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionEntitlementOrder) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionEntitlementOrder) predicate.SubscriptionEntitlementOrder {
	return predicate.SubscriptionEntitlementOrder(sql.NotPredicates(p))
}
